.github/workflows/ci.yml
README.md
package.json
yarn.lock

Replace npm commands by yarn in CI workflow

---

README.md
apps/web-app-e2e/project.json
apps/web-app-e2e/src/support/commands.ts
apps/web-app/README.md
apps/web-app/project.json
apps/web-app/src/app/app.component.spec.ts
apps/web-app/src/app/app.module.ts
apps/web-app/src/decl.d.ts
package.json
workspace.json

Create project `web-app`

---

apps/api-db/project.json
apps/web-app-react/src/app/app.tsx
apps/web-app/src/app/app.component.ts
libs/shared/web-components/.babelrc
libs/shared/web-components/.eslintrc.json
libs/shared/web-components/README.md
libs/shared/web-components/jest.config.js
libs/shared/web-components/project.json
libs/shared/web-components/src/index.ts
libs/shared/web-components/src/lib/shared-web-components.ts
libs/shared/web-components/src/lib/welcome.element.ts
libs/shared/web-components/tsconfig.json
libs/shared/web-components/tsconfig.lib.json
libs/shared/web-components/tsconfig.spec.json
tsconfig.base.json
workspace.json

Add Web Components (WC) component example

---

LICENSE.txt
README.md

Document how to start the web app with Docker

---

docs/legacy.md

Add docs/legacy.md

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
README.md

Add Code Of Conduct and Contributing Guide

---

README.md

Use . ./dev-env.sh to support both bash and zsh

---

docker-compose.yml

Set docker service name of web-app

---

.devcontainer/devcontainer.json

Mirror VS Code settings to dev container config

---

apps/web-app/src/app/app-sections.ts
apps/web-app/src/app/app.component.html
apps/web-app/src/app/app.component.ts
libs/web/pages/angular-white-transparent.svg
libs/web/ui/src/index.ts
libs/web/ui/src/lib/navbar/navbar-section.ts
libs/web/ui/src/lib/navbar/navbar.component.html
libs/web/ui/src/lib/navbar/navbar.component.ts
libs/web/ui/src/lib/navbar/navbar.module.ts

Add sections to navbar

---

.github/workflows/ci.yml

Cache node_modules in CI workflow

---

.github/workflows/ci.yml
libs/shared/style/src/_variables.scss

Make use of Node.js cache in CI workflow

---

apps/api/tox.ini
tools/coverage-merger.js

Fix api coverage

---

apps/api/tox.ini

Fix API coverage file paths

---

docs/app-styles-themes-assets.md

Document how to add a theme to a component

---

.devcontainer/devcontainer.json

See https://github.com/Sage-Bionetworks/vscode-dev-containers/pull/4

Update dev container to v0.1.0

---

.github/CODE_OF_CONDUCT.md

Fixes #130 
Update CoC based on the latest version from Sage.

Use Sage Code of Conduct

---

.devcontainer/devcontainer.json
.vscode/extensions.json

Use dev container image `sagebionetworks/python-3-node:0.2.0`

---

.devcontainer/devcontainer.json
.vscode/extensions.json

This extension [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) for VS Code enables to:
- easily checkout PRs
- manage issues and PRs (e.g. list of issues/PRs assigned, list of PRs to review)

Add vscode extension to manage GH PRs

---

.github/workflows/ci.yml

Use devcontainer in CI/CD workflow

---

README.md
apps/api-db/project.json
apps/api/project.json
apps/keycloak/project.json
apps/web-app/project.json
dev-env.sh
package.json

Rename project task `docker` to `build-image`

---

apps/keycloak-db/docker-compose.yml
apps/keycloak/README.md
apps/keycloak/docker-compose.yml
apps/keycloak/project.json
docker-compose.yml

Fixes #196 
- Add services `keycloak` and `keycloak-db`
- Use more descriptive name for the existing services. For example, `web-app` becomes `challenge-registry-web-app`.
- Starting the full stack with development KC data is done this way:
```console
nx import-dev-data keycloak
docker compose up
```

Update workspace docker compose

---

docs/develop-on-a-remote-host.md

Anonymize the data in the doc "Develop on a remote Docker host".
EDIT: Issue/PR #200! 🎉
EDIT: I'm considering sharing this document more broadly at Sage and possibly outside of Sage (could make a good LinkedIn post), which is why I anonymized the names.

Update remote host setup doc

---

.devcontainer/devcontainer.json
.vscode/extensions.json

Add VS Code extensions for Java

---

apps/challenge-api-gateway/Dockerfile
apps/challenge-api-gateway/pom.xml
apps/challenge-api-gateway/requests.http
apps/challenge-api-gateway/src/main/java/org/sagebionetworks/challenge/configuration/SecurityConfiguration.java
apps/challenge-api-gateway/src/main/resources/application.yml
apps/challenge-keycloak/README.md
apps/challenge-keycloak/data/import/master-realm.json
apps/challenge-keycloak/data/import/test-realm.json
apps/challenge-keycloak/data/import/test-users-0.json
apps/challenge-keycloak/docker-compose.yml
apps/challenge-keycloak/project.json
apps/challenge-service-registry/Dockerfile
apps/challenge-user-service/Dockerfile

- Fixes #246
- Register OAuth 2.0 client `challenge-core-client`.
- Can now get OAuth 2.0 access token via the API gateway.
- Update `requests.http` to test the new endpoints.
- Made preparation to access `/user/api/v1/register`.

Integrate keycloak to microserve infra

---

.devcontainer/devcontainer.json
.github/workflows/build-devcontainer-image.yml
tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile
tools/devcontainers/challenge-devcontainer/.devcontainer/devcontainer.json

- Fixes #183 
- Fixes #257
- Fixes #263

Fix devcontainer definition

---

.devcontainer/devcontainer.json

Update to this [devcontainer](https://hub.docker.com/layers/226310991/sagebionetworks/challenge-devcontainer/5ad791b9/images/sha256-2c4d0584921e8cc70044818fccb3a01e09f414759a1628d09f6ec77e5bde8a0b?context=repo)

Use challenge-devcontainer:5ad791b9

---

apps/challenge-keycloak/data/import/test-realm.json
apps/challenge-keycloak/data/import/test-users-0.json

Remove Google identity provider data

---

apps/challenge-keycloak/.env.example
apps/challenge-keycloak/docker-compose.export.yml
apps/challenge-keycloak/docker-compose.import.yml
apps/challenge-keycloak/project.json

Use `docker run` to import and export KC data

---

tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile
tools/devcontainers/challenge-devcontainer/build-image.sh

Source dev-env.sh if found in current directory

---

.devcontainer/devcontainer.json
.vscode/extensions.json
.vscode/settings.json
tools/devcontainers/challenge-devcontainer/.devcontainer/devcontainer.json

Remove duplicated vs code settings

---

README.md

Add badge to open repo in devcontainer

---

.devcontainer/devcontainer.json
.vscode/extensions.json

Remove extension `orta.vscode-jest`

---

dev-env.sh

- Fixes #291 
See terminal panel in VS Code.

Add install alias

---

dev-env.sh
tools/add-hostnames.sh
tools/add-hosts.sh
tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile

Needed for #305 to map docker service names to 127.0.0.1.
- Need to create a new PR to make use of the new devcontainer image

Create app hostnames

---

.devcontainer/devcontainer.json
apps/challenge-api-gateway/.env.example
apps/challenge-api-gateway/Dockerfile
apps/challenge-api-gateway/docker-compose.yml
apps/challenge-api-gateway/pom.xml
apps/challenge-api-gateway/project.json
apps/challenge-api-gateway/requests.http
apps/challenge-api-gateway/src/main/java/org/sagebionetworks/challenge/configuration/SecurityConfiguration.java
apps/challenge-api-gateway/src/main/resources/application.yml
apps/challenge-keycloak/docker-compose.yml
apps/challenge-mariadb/docker-compose.yml
apps/challenge-mongodb/docker-compose.yml
apps/challenge-postgresql/docker-compose.yml
apps/challenge-service-registry/.env.example
apps/challenge-service-registry/Dockerfile
apps/challenge-service-registry/docker-compose.yml
apps/challenge-service-registry/pom.xml
apps/challenge-service-registry/project.json
apps/challenge-service-registry/requests.http
apps/challenge-service-registry/src/main/resources/application.yml
apps/challenge-user-service/.env.example
apps/challenge-user-service/Dockerfile
apps/challenge-user-service/docker-compose.yml
apps/challenge-user-service/project.json
apps/challenge-user-service/requests.http
apps/challenge-user-service/src/main/resources/application.yml

Fix docker networking issues

---

dev-env.sh
tools/add-hostnames.sh
tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile

Move hostname definitions

---

.github/workflows/ci.yml

Setup maven cache in CI workflow

---

.devcontainer/devcontainer.json
.vscode/extensions.json

Fix lombok extension

---

.devcontainer/devcontainer.json
.vscode/settings.json

Fix error 130

---

.vscode/settings.json

Disable lombok support for Red Hat VS Code extension

---

.vscode/settings.json
README.md
docs/app-styles-themes-assets.md
docs/cheat-sheet.md
docs/devcontainer.md
docs/develop-on-a-remote-host.md
docs/drawio/README.md
docs/faq.md
docs/legacy-repositories.md
docs/libraries.md
docs/nx-readme.md
docs/stack-monitoring.md
docs/using-nx.md

Fixes #418 
- Set max line width to 100 chars in Rewrap.
- Display vertical line at 100 chars in VS Code editor.
- Rewrap docs/**/*.md files.
Before (80 char):
After (100 chars):

Set max line width to 100 in Rewrap

---

package.json
yarn.lock

Upgrade webhint to the latest version

---

.husky/post-checkout
.husky/post-merge
.husky/post-rewrite
package.json
yarn.lock

Auto-install npm dependencies when switching branches

---

apps/challenge-registry/src/app/app-sections.ts

Fix navbar Challenges button

---

README.md

Add `--no-single-branch` to gitt clone command

---

package.json
yarn.lock

Install webpack bundle analyzer

---

.prettierrc
.vscode/settings.json
libs/challenge-registry/ui/src/_lib-theme.scss

Add scss formatting and set prettier max line width to 100

---

apps/challenge-registry/project.json
apps/challenge-registry/src/_app-theme.scss
apps/challenge-registry/src/app/app.component.html
apps/challenge-registry/src/app/app.module.ts
libs/challenge-registry/home/src/lib/home.component.html
libs/challenge-registry/home/src/lib/home.module.ts
libs/shared/util/.eslintrc.json
libs/shared/util/README.md
libs/shared/util/jest.config.ts
libs/shared/util/project.json
libs/shared/util/src/index.ts
libs/shared/util/src/lib/directives/app-shell-no-render.directive.spec.ts.off
libs/shared/util/src/lib/directives/app-shell-no-render.directive.ts
libs/shared/util/src/lib/directives/app-shell-render.directive.spec.ts.off
libs/shared/util/src/lib/directives/app-shell-render.directive.ts
libs/shared/util/src/lib/shared-util.module.ts
libs/shared/util/src/test-setup.ts
libs/shared/util/tsconfig.json
libs/shared/util/tsconfig.lib.json
libs/shared/util/tsconfig.spec.json
tsconfig.base.json
workspace.json

Add appShellRender and appShellNoRender directives

---

.devcontainer/devcontainer.json
tools/devcontainers/challenge-devcontainer/.devcontainer/devcontainer.json

Set devcontainer container name

---

apps/challenge-registry/project.json
libs/shared/assets/src/robots.txt

Add robots.txt

---

apps/challenge-registry/project.json
apps/challenge-registry/src/humans.txt

Add humans.txt to the challenge registry

---

tools/generate-sitemap.js

Undoing a commit I made by mistake while working on #493 .

Restore sitemap generator config

---

tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile

Add `act` to the devcontainer

---

README.md
dev-env.sh
tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile

Remove reference to the term "challenge" from the devcontainer to make it more friendly to use in a different projects.

Update dev env init method

---

dev-env.sh

Remove terminal message about `yarn.lock`

---

.vscode/settings.json
libs/challenge-registry/about/src/lib/about.component.html

Format HTML files on save with Prettier

---

.github/workflows/lint-pr.yml

Add GH workflow that lint PR titles

---

tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile

feat: Add ngrok to the dev container

---

libs/challenge-registry/user-profile/src/index.ts
libs/challenge-registry/user-profile/src/lib/mock-user-profiles.ts
libs/challenge-registry/user-profile/src/lib/user-profile-routing.module.ts
libs/challenge-registry/user-profile/src/lib/user-profile.component.ts
libs/challenge-registry/user-profile/src/lib/user-profile.module.ts
libs/challenge-registry/user-profile/src/lib/user-profile.resolver.spec.ts
libs/challenge-registry/user-profile/src/lib/user-profile.resolver.ts
libs/challenge-registry/user-profile/src/lib/user-profile.ts

feat: Get user profile object using State Transfer API

---

.github/workflows/build-devcontainer-image.yml
tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile
tools/devcontainers/challenge-devcontainer/.devcontainer/devcontainer.json

Related to #543
- Add the env var `DEVCONTAINER_VERSION` to the dev container.

feat: Set DEVCONTAINER_VERSION

---

.devcontainer/devcontainer.json
.husky/post-checkout
.husky/post-merge
.husky/post-rewrite
package.json
tools/check-devcontainer-version.js

feat: Notify the developer when a different dev container must be used

---

tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile

chore: Add JDK to the dev container

---

apps/challenge-api-gateway/project.json
apps/challenge-auth-service/project.json
apps/challenge-config-service/project.json
apps/challenge-core-service/project.json
apps/challenge-service-registry/project.json
apps/challenge-user-service/project.json

chore: Cache Maven build artifacts with Nx

---

.devcontainer/devcontainer.json
tools/check-devcontainer-version.js

Fixes #561
cc: @vpchung @rrchai

fix: Prevent git hooks from failing when dev container requirements are not met

---

.devcontainer/devcontainer.json
.vscode/extensions.json

fixes #476
An autofill example:

feat: Add angular language service extension

---

docs/app-styles-themes-assets.md

docs: Define colors and typography styles to add in `*_theme.scss`

---

libs/challenge-registry/ui/src/lib/challenge-card/_challenge-card-theme.scss

feat: add shadow to challenge card

---

.github/workflows/ci.yml

chore: Cache gradle dependencies in CI workflow

---

libs/challenge-registry/user-profile/src/lib/user-profile-stats/_user-profile-stats-theme.scss
libs/challenge-registry/user-profile/src/lib/user-profile-stats/user-profile-stats.component.scss

feat: add more definitions to border

---

tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile

feat: add `hyperfine` to the dev container

---

package.json
yarn.lock

chore: upgrade Nx plugin `@nxrocks/nx-spring-boot`

---

.github/workflows/build-devcontainer-image.yml
tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile
tools/devcontainers/challenge-devcontainer/build-image.sh

fix: fix devcontainer build

---

README.md
docs/projects.md

docs: Document the list of projects

---

libs/challenge-registry/user-profile/src/lib/_user-profile-theme.scss
libs/challenge-registry/user-profile/src/lib/user-profile.component.html
libs/challenge-registry/user-profile/src/lib/user-profile.component.scss

fix: sidenav links behavior

---

package.json
yarn.lock

fix: Upgrade to @nxrocks/nx-spring-boot@5.0.2

---

README.md
docs/collect-challenge-logs-and-system-metrics.md

docs: Recommend partial clone over shallow clone

---

.devcontainer/devcontainer.json

fix: Silence port forwarding dialogs in VS Code dev container

---

.github/workflows/build-devcontainer-image.yml
tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile

Contributes to #637
- It looks like [this PR](https://github.com/devcontainers/cli/issues/144) fixes the issue where `devcontainer` returns a success code even when failing.

feat: Build new devcontainer base image

---

.devcontainer/devcontainer.json

fix: Use devcontainer image `b09b7315`

---

.devcontainer/devcontainer.json
.vscode/extensions.json

feat: Add VS Code extension Live Server

---

README.md

docs: Fix readme requirements

---

apps/challenge-user-service/project.json

Restore project dependencies commented out by #705.

fix(user-service): restore project dependencies

---

.github/workflows/ci.yml
apps/challenge-api-gateway/.gitignore
apps/challenge-auth-service/.gitignore
apps/challenge-config-service/.gitignore
apps/challenge-core-service/.gitignore
apps/challenge-service-registry/.gitignore
apps/challenge-user-service/.gitignore
dev-env.sh
docs/java-cheat-sheet.md
libs/shared-java/challenge-util/.gitignore

chore: remove Maven from the workspace

---

.github/renovate.json

feat(deps): ignore local packages in renovate config

---

.github/renovate.json
.github/workflows/renovate-config-validator.yml

- Restore global `schedule` now that the entire workspace has been updated.
- Add GH workflow that validates Renovate configuration.

feat(deps): setup workflow that validates Renovate config

---

.github/workflows/ci.yml

fix(deps): try avoiding multiple renovate workflow run

---

tools/devcontainers/challenge/.devcontainer/Dockerfile
tools/devcontainers/challenge/.devcontainer/devcontainer.json

chore(devcontainer): update devcontainer base image and tools

---

.devcontainer/devcontainer.json
tools/devcontainers/challenge/.devcontainer/devcontainer.json

chore(devcontainer): update docker-in-docker

---

libs/challenge-registry/about/src/lib/_about-theme.scss
libs/challenge-registry/about/src/lib/about.component.html
libs/challenge-registry/about/src/lib/about.component.scss

fix(ui): apply typography config to page

---

.github/workflows/build-devcontainer-image.yml
tools/devcontainers/challenge/.devcontainer/Dockerfile

feat: Add devcontainer CLI to the devcontainer

---

docs/faq.md

docs: Document how to fix `no space left on device`

---

docs/enable-sso-with-keycloak.md
libs/challenge-registry/ui/src/lib/navbar/navbar.component.html

docs: Document how to enable Google SSO with Keycloak

---

apps/challenge-keycloak/docker-compose.yml
apps/challenge-keycloak/themes/challenge-registry/README.md
apps/challenge-keycloak/themes/challenge-registry/login/terms.ftl
apps/challenge-keycloak/themes/challenge-registry/login/theme.properties

feat: Add Keycloak theme challenge-registry (not applied)

---

docs/create-a-new-angular-component.md
docs/create-a-new-component.md
docs/figma-to-code.md

Addresses #197.
Note that the original contents of `figma-to-code.md` has been moved to a new file: `create-a-new-component.md` (which will probably require some modification as well).

docs: Figma-to-code docs

---

.github/workflows/build-devcontainer-image.yml
.github/workflows/ci.yml

fix(ci): Replace deprecated`::set-output`

---

.devcontainer/devcontainer.json

chore: Update devcontainer to `6c35430`

---

docs/update-dependencies.md

docs: Document how to manage dependency updates

---

apps/challenge-service/requests.http
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/api/ChallengeApi.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/api/ChallengeApiDelegate.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/api/ChallengeApiDelegateImpl.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/ChallengeFilter.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/ChallengeRepositoryCustomImpl.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/service/ChallengeService.java
apps/challenge-service/src/main/resources/openapi.yaml
libs/api-spec/build/challenge.openapi.yaml
libs/api-spec/build/openapi.yaml
libs/api-spec/src/components/parameters/query/challenge/difficulties.yaml
libs/api-spec/src/paths/challenges.yaml

fix: Use plural for query parameters that accept an array of values

---

apps/challenge-service/.openapi-generator/FILES
apps/challenge-service/requests.http
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/api/ChallengeApi.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/api/ChallengeApiDelegate.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/api/ChallengeApiDelegateImpl.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/configuration/EnumConverterConfiguration.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeDto.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeSubmissionTypeDto.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/ChallengeSubmissionTypeEntity.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/mapper/ChallengeMapper.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/ChallengeFilter.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/ChallengeRepositoryCustomImpl.java
apps/challenge-service/src/main/java/org/sagebionetworks/challenge/service/ChallengeService.java
apps/challenge-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
apps/challenge-service/src/main/resources/db/migration/V1.1.0__insert_data.sql
apps/challenge-service/src/main/resources/openapi.yaml
libs/api-spec/build/challenge.openapi.yaml
libs/api-spec/build/openapi.yaml
libs/api-spec/src/components/parameters/query/challenge/submissionTypes.yaml
libs/api-spec/src/components/schemas/Challenge.yaml
libs/api-spec/src/components/schemas/ChallengeSubmissionType.yaml
libs/api-spec/src/paths/challenges.yaml
libs/api-spec/src/paths/parameters/challenge/submissionTypes.yaml

Fixes #1040 
Filter challenges by submission type
```console
GET {{basePath}}/challenges?submissionTypes=container_image
{
"number": 0,
"size": 100,
"totalElements": 2,
{
"id": 1,
"name": "The Digital Mammography DREAM Challenge",
"status": "upcoming",
"difficulty": "good_for_beginners",
"platform": {
"id": 1,
"name": "synapse",
"displayName": "Synapse"
},
"incentives": [
"monetary",
"publication"
],
"submissionTypes": [
"container_image",
"prediction_file"
],
"createdAt": "2022-12-24T21:40:49Z",
"updatedAt": "2022-12-24T21:40:49Z"
},
{
"id": 2,
"name": "Patient Mortality EHR DREAM Challenge",
"status": "active",
"difficulty": "intermediate",
"platform": {
"id": 1,
"name": "synapse",
"displayName": "Synapse"
}, …
```

feat: Filter challenges by submission types

---

tools/devcontainers/challenge/.devcontainer/Dockerfile

Fixes #1059 
- Add Poetry to the dev container
Here I'm using the same version as the one used by Schematic in its CI/CD workflow.
```console
$ poetry --version
Poetry (version 1.2.0rc1)
```

feat: Add Poetry to the dev container

---

tools/devcontainers/challenge/.devcontainer/Dockerfile

feat: Install Poetry globally in the dev container

---

.devcontainer/devcontainer.json
.github/workflows/ci.yml

feat: Use sage devcontainer

---

apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/ChallengeRepository.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/CustomChallengeRepository.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/CustomChallengeRepositoryImpl.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/service/ChallengeService.java

feat: JPA repository now extends custom repository

---

apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeDto.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/ChallengeEntity.java
apps/challenge-registry/challenge-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
apps/challenge-registry/challenge-service/src/main/resources/db/migration/V1.1.0__insert_data.sql
apps/challenge-registry/challenge-service/src/main/resources/openapi.yaml
libs/challenge-registry/api-description/build/challenge.openapi.yaml
libs/challenge-registry/api-description/build/openapi.yaml
libs/challenge-registry/api-description/src/components/schemas/Challenge.yaml
libs/challenge-registry/api-description/src/components/schemas/ChallengeCreateRequest.yaml
libs/challenge-registry/api-description/src/components/schemas/ChallengeDescription.yaml
libs/challenge-registry/api-description/src/components/schemas/ChallengeHeadline.yaml

- Fixes #1119 
- Fixes #1120 
- Add the property `Challenge.headline`
- The recommended length in this article is 60 chars. Here I give a bit more room and set the max length to 80 chars.
- Add the property `Challenge.description`
- The recommended length in this article is between 150 and 160 characters. Here I set it to 280 (tweet length).
- 280 chars is a compromise between a suitable description for Google SEO and a longer description that contribute to the relevance of results when using text search.
- Happy to revisit this decision if additional considerations are available.
List the challenges:
```console
GET {{basePath}}/challenges
{
"number": 0,
"size": 100,
"totalElements": 3,
{
"id": 1,
"name": "The …
```

feat: Add Challenge headline and description

---

apps/challenge-registry/challenge-service/.openapi-generator/FILES
apps/challenge-registry/challenge-service/project.json
apps/challenge-registry/challenge-service/requests.http
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/configuration/EnumConverterConfiguration.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeDirectionDto.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeSearchQueryDto.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeSortDto.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/ChallengeEntity.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/ChallengeStar.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/CollectionSizeBridge.java
apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/CustomChallengeRepositoryImpl.java
apps/challenge-registry/challenge-service/src/main/resources/openapi.yaml
libs/challenge-registry/api-description/build/challenge.openapi.yaml
libs/challenge-registry/api-description/build/openapi.yaml
libs/challenge-registry/api-description/src/components/schemas/ChallengeDirection.yaml
libs/challenge-registry/api-description/src/components/schemas/ChallengeSearchQuery.yaml
libs/challenge-registry/api-description/src/components/schemas/ChallengeSort.yaml

Fixes #1142 
- List of challenges can be sorted according to the challenge creation date (default) and number of stars.
- Define a value bridge to index the size of the list of challenge stars.
- The name of the properties indexed in elasticsearch are now in snake case.
- The project "challenge-registry-elasticsearch" is now a dependency of "challenge-registry-challenge-service".
- An OA enum must be defined in its own file for the Java OpenAPI generator to generate a converter bean for this enum.
Sort the challenges by their starred count in desc oder:
```console
GET {{basePath}}/challenges?sort=starred&direction=desc
{
"number": 0,
"size": 100,
"totalElements": 3,
{
"id": 1,
"name": "The Digital Mammography DREAM …
```

feat: Update OA descriptionto include sort and direction

---

libs/challenge-registry/challenge-search/src/lib/challenge-search.component.scss
libs/challenge-registry/challenge/src/lib/challenge-overview/challenge-overview.component.scss
libs/challenge-registry/challenge/src/lib/challenge.component.scss
libs/challenge-registry/home/src/lib/challenge-host-list/challenge-host-list.component.scss
libs/challenge-registry/home/src/lib/challenge-registration/challenge-registration.component.html
libs/challenge-registry/home/src/lib/challenge-registration/challenge-registration.component.scss
libs/challenge-registry/home/src/lib/challenge-search/challenge-search.component.scss
libs/challenge-registry/home/src/lib/sponsor-list/sponsor-list.component.scss
libs/challenge-registry/home/src/lib/statistics-viewer/statistics-viewer.component.scss
libs/challenge-registry/login/src/lib/login.component.scss
libs/challenge-registry/org-profile/src/lib/org-profile.component.scss
libs/challenge-registry/styles/src/lib/_general.scss
libs/challenge-registry/user-profile/src/lib/user-profile.component.scss

This PR will add some common CSS definitions to `_general.scss`.  For now, I have extracted styles related to the grid layout, some text, and buttons.
Note that for the styles related to `mat-button`, `!important` was required so that our custom values will be applied (and not ignored).

style(ui): Global styles

---

libs/challenge-registry/challenge-search/src/lib/challenge-search.component.scss
libs/challenge-registry/challenge/src/lib/challenge-overview/challenge-overview.component.scss
libs/challenge-registry/challenge/src/lib/challenge.component.scss
libs/challenge-registry/home/src/lib/challenge-host-list/challenge-host-list.component.scss
libs/challenge-registry/home/src/lib/challenge-registration/challenge-registration.component.html
libs/challenge-registry/home/src/lib/challenge-registration/challenge-registration.component.scss
libs/challenge-registry/home/src/lib/challenge-search/challenge-search.component.scss
libs/challenge-registry/home/src/lib/sponsor-list/sponsor-list.component.scss
libs/challenge-registry/home/src/lib/statistics-viewer/statistics-viewer.component.scss
libs/challenge-registry/login/src/lib/login.component.scss
libs/challenge-registry/org-profile/src/lib/org-profile.component.scss
libs/challenge-registry/styles/src/lib/_general.scss
libs/challenge-registry/ui/src/lib/footer/_footer-theme.scss
libs/challenge-registry/ui/src/lib/footer/footer.component.html
libs/challenge-registry/ui/src/lib/footer/footer.component.scss
libs/challenge-registry/user-profile/src/lib/user-profile.component.scss
libs/shared/typescript/styles/src/lib/_general.scss

This PR will address #1149:
Ideally, this should be merged after #1150, as some styles are dependent on those defined in `_general`.

fix(ui): Fix footer

---

apps/challenge-registry/app/src/app/app-sections.ts
apps/challenge-registry/app/src/app/app.component.ts
apps/challenge-registry/app/src/index.html
libs/challenge-registry/ui/src/lib/navbar/navbar.component.html
libs/challenge-registry/ui/src/lib/user-button/_user-button-theme.scss
libs/challenge-registry/ui/src/lib/user-button/user-button.component.scss

Addresses #1186 :
The most notable change is updating the brand to "OpenChallenges" in the navbar as well as the page title.
I was also thinking of changing the language for signing up to "Join" to make it more... personable?  But happy to revert back if desired.

style(ui): Fix navbar

---

apps/openchallenges/api-gateway/src/main/java/org/sagebionetworks/challenge/configuration/SecurityConfiguration.java
apps/openchallenges/api-gateway/src/main/resources/application.yml

- Configure the API gateway to handle requests sent to `/api/v1/challengeInputDataTypes`

feat: Allow API gateway to fetch challenge input data types

---

libs/openchallenges/challenge-search/src/lib/challenge-search-filters-values.ts
libs/openchallenges/challenge-search/src/lib/challenge-search-filters.ts
libs/openchallenges/challenge-search/src/lib/challenge-search.component.html
libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
libs/openchallenges/ui/src/lib/checkbox-filter/filter.model.ts
libs/openchallenges/ui/src/lib/search-dropdown-filter/search-dropdown-filter.component.html
libs/openchallenges/ui/src/lib/search-dropdown-filter/search-dropdown-filter.component.ts

feat: enable the input data types filter using `challengeService` and `ChallengeInputDataTypeService`

---

apps/openchallenges/challenge-service/build.gradle
apps/openchallenges/challenge-service/src/main/resources/application.yml
apps/openchallenges/organization-service/build.gradle
apps/openchallenges/organization-service/project.json
apps/openchallenges/organization-service/src/main/resources/application.yml

feat: Add distributed tracing to the organization service

---

apps/openchallenges/challenge-service/project.json
apps/openchallenges/challenge-service/requests.http
apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeSortDto.java
apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/CustomChallengeRepositoryImpl.java
apps/openchallenges/challenge-service/src/main/resources/openapi.yaml
libs/openchallenges/api-client-angular/src/lib/model/challengeSearchQuery.ts
libs/openchallenges/api-client-angular/src/lib/model/challengeSort.ts
libs/openchallenges/api-description/build/challenge.openapi.yaml
libs/openchallenges/api-description/build/openapi.yaml
libs/openchallenges/api-description/src/components/schemas/ChallengeSort.yaml

Fixes #1207 
- Add the following value to the challenge sort enum: `recently_started`, `recently_ended`.
- Regenerate the API client for Angular.
Sort the challenges by how recently they have started.
> **Note** With this sorting strategy, only challenges with a start date in the past are returned. The default order shows challenges that have started recently first and challenges that have started less recently further down in the list. This order can be changed with the `direction` query parameter.
```console
GET {{basePath}}/challenges?sort=recently_started
HTTP/1.1 200 
{
"number": 0,
"size": 100,
"totalElements": 4,
{
"id": 4,
"name": "Awesome Challenge 2023",
"headline": "Example headline",
"description": …
```

feat: Sort challenges by Recently Started and Recently Closed (backend)

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/story.yml

feat: Add issue form for creating Stories

---

.github/ISSUE_TEMPLATE/story.yml

feat: Improve Story form

---

apps/openchallenges/app/project.json
docs/develop-on-a-remote-host.md

feat: Document how to use GitHub Codespaces

---

tools/devcontainers/sage/.devcontainer/Dockerfile

feat: Add `jq` to the dev container

---

apps/openchallenges/challenge-service/project.json
apps/openchallenges/config-server/project.json
apps/openchallenges/organization-service/project.json
apps/openchallenges/organization-service/src/main/resources/application.yml

The OC app now starts successfully and challenges are displayed on the search page.

fix: Fix OC project dependencies

---

apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengeSubmissionTypeDto.java
apps/openchallenges/challenge-service/src/main/resources/openapi.yaml
libs/openchallenges/api-description/build/challenge.openapi.yaml

feat(data): add `notebook` to challenge model

---

dev-env.sh
docs/develop-on-a-remote-host.md

docs: Update docs to setup remote dev instance

---

libs/openchallenges/about/src/lib/about.component.html
libs/openchallenges/challenge-search/src/lib/challenge-search.component.html
libs/openchallenges/challenge/src/lib/challenge.component.html
libs/openchallenges/home/src/lib/home.component.html
libs/openchallenges/login/src/lib/login.component.html
libs/openchallenges/not-found/src/lib/not-found.component.html
libs/openchallenges/org-profile/src/lib/org-profile.component.html
libs/openchallenges/org-search/src/lib/org-search.component.html
libs/openchallenges/signup/src/lib/signup.component.html
libs/openchallenges/styles/src/lib/_constants.scss
libs/openchallenges/styles/src/lib/_general.scss
libs/openchallenges/team/src/lib/team.component.html
libs/openchallenges/ui/src/lib/footer/footer.component.html
libs/openchallenges/ui/src/lib/footer/footer.component.scss
libs/openchallenges/ui/src/lib/navbar/navbar.component.scss

- fixes #1270 
The issue was the content of each component is not taking full height pf the page. Each page now is applied the "base" class (defined in `libs/openchallenges/styles/src/lib/_general.scss`), which is used to set proper height of content (you could ignore html changes), so that the footer will be always sticky at the bottom.

feat(ui): Make footer sticky at the bottom

---

apps/openchallenges/config-server/README.md

docs: Document how to configure the config server

---

docker/openchallenges/serve-detach.sh
docker/openchallenges/services/grafana.yml
docker/openchallenges/services/prometheus.yml
docker/openchallenges/volumes.yml

fix: Store Prometheus and Grafana data to Docker volumes

---

apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.1__insert_temp_data.sql

Addressing [this issue](https://github.com/Sage-Bionetworks/sage-monorepo/pull/1376#issuecomment-1468910992), related to the newline characters in the descriptions. I checked both the challenge-service and organization-service.

fix(data): remove \n from descriptions

---

libs/openchallenges/org-search/src/lib/org-search-filters-values.ts

feat(angular): Enable to sort by challenge count

---

libs/openchallenges/ui/src/lib/organization-card/organization-card.component.html
libs/openchallenges/ui/src/lib/organization-card/organization-card.component.ts

Without or with challenges supported:

feat: update challengeCount in org card

---

tools/devcontainers/sage/.devcontainer/Dockerfile

feat: Add terraform CLI to the devcontainer

---

tools/devcontainers/sage/.devcontainer/Dockerfile

feat: Add AWS CLI to the dev container

---

.devcontainer/devcontainer.json

feat: Update dev container tag

---

apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.1__insert_temp_data.sql

This PR will officially close #1411.

feat(data): Add logos

---

apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.1__insert_temp_data.sql

* A few organizations have been "removed" from the database, due to their role as technically platform rather than challenge contributor (ie, Kaggle).  Our "new" total in the registry is 235 organizations.
* Character limit for `organization.description` has been increased from 280 to 1000
No organizations have been removed from our tracking sheet.  Instead, there is now a new private column called public, that will flag whether an organization should be added to the database or not.

fix(data): organization data and table updates

---

libs/openchallenges/challenge/src/lib/_challenge-theme.scss
libs/openchallenges/org-profile/src/lib/_org-profile-theme.scss
libs/openchallenges/styles/src/lib/_general.scss
libs/openchallenges/ui/src/lib/organization-card/_organization-card-theme.scss

Update layout and text size inside the avatar logo for:
* profile pages
Before | After
--|--
* organization cards
Before | After
--|--

fix(ui): adjust layout and font family of text inside avatar logos

---

libs/openchallenges/styles/src/lib/_general.scss
libs/openchallenges/ui/src/lib/footer/_footer-theme.scss
libs/openchallenges/ui/src/lib/footer/footer.component.html
libs/openchallenges/ui/src/lib/footer/footer.component.scss

Fixes #1540
* Add "Report a Bug" that will link to our GH issue page
* Include "-beta" to our app version
* General SCSS updates to improve responsiveness

feat(ui): add "Report a Bug"; update version; scss updates for responsiveness

---

.github/PULL_REQUEST_TEMPLATE/default.md

Closes #1539 
> **Note** Multiple template can be added to a repository.
- Add a template that matches the one used by the OC team

feat: Add Pull Request template

---

libs/openchallenges/challenge/src/lib/challenge-organizers/challenge-organizers.component.scss
libs/openchallenges/challenge/src/lib/challenge-sponsors/challenge-sponsors.component.scss
libs/openchallenges/challenge/src/lib/challenge-stargazers/challenge-stargazers.component.scss
libs/openchallenges/challenge/src/lib/challenge.component.html
libs/openchallenges/org-profile/src/lib/org-profile-challenges/org-profile-challenges.component.scss
libs/openchallenges/org-profile/src/lib/org-profile-members/org-profile-members.component.scss
libs/openchallenges/org-profile/src/lib/org-profile-overview/org-profile-overview.component.html
libs/openchallenges/org-profile/src/lib/org-profile-overview/org-profile-overview.component.scss
libs/openchallenges/org-profile/src/lib/org-profile-overview/org-profile-overview.component.ts
libs/openchallenges/org-profile/src/lib/org-profile.component.html
libs/openchallenges/user-profile/src/lib/user-profile-challenges/user-profile-challenges.component.scss
libs/openchallenges/user-profile/src/lib/user-profile-overview/user-profile-overview.component.scss
libs/openchallenges/user-profile/src/lib/user-profile-starred/user-profile-starred.component.scss
libs/openchallenges/user-profile/src/lib/user-profile-stats/user-profile-stats.component.html
libs/openchallenges/user-profile/src/lib/user-profile.component.html

Fixes #1532
* Add acronym to Details section on organization profile pages; if none found, print "Not available"
* Add top padding to section header on both profile pages (to align with side nav)
* Update the layout of user profile page

feat(ui): general profile UI updates

---

libs/openchallenges/styles/src/lib/_general.scss
libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.html
libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.scss
libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.ts

* Increase body height of challenge card (to better accommodate for challenges with long titles, descriptions, etc)
* Fix footer so that items are center-aligned
Before | After
-- | --

fix(ui): challenge card update

---

tools/devcontainers/sage/.devcontainer/Dockerfile

Fixes #1575
- Update the devcontainer
- Setup locale
- Install pyenv

feat: Setup locale and add pyenv

---

.devcontainer/devcontainer.json

chore: Update devcontainer to `c793c92`

---

.github/workflows/ci.yml

This is required to enable the new Python setup to run the test correctly (schematic project)

chore: Update the devcontainer used by the CI/CD workflow

---

tools/devcontainers/sage/.devcontainer/Dockerfile

chore: Add Python 3.10.0 to the devcontainer

---

apps/openchallenges/challenge-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
apps/openchallenges/challenge-service/src/main/resources/db/migration/V1.0.1__insert_temp_data.sql

Fixes #1614 
* update property name from `avatar_url` to `avatar_key`
* update mock URLs with object key from S3

feat(data): add platform logos

---

apps/openchallenges/infra/src/preview-instance/preview-instance.ts

feat: Specify storage space for an EC2 instance created with CDKTF

---

libs/openchallenges/org-profile/src/lib/org-profile-challenges/org-profile-challenges.component.html
libs/openchallenges/org-profile/src/lib/org-profile-challenges/org-profile-challenges.component.ts

- fixes #1530 
- retrieve only challenges that are relevant to the org, instead of all challenges.

feat(fix): Add default pageSize in Org Profile

---

apps/openchallenges/app/src/index.html

Fixes #1642 
* add back in a key line to `index.html` (was accidentally removed and pushed during a debugging process)

fix(ui): Revert one change

---

apps/openchallenges/app/src/app/app.module.ts

fix: Disable Keycloak initialization in the OC app

---

apps/openchallenges/app/Dockerfile
apps/openchallenges/app/docker/nginx/templates/http.conf.template

Closes #1640
- Add `/health` endpoint to the NGINX config of the web app
- Add `HEALTHCHECK` instruction to the image of the app
cc: @linglp

feat: Add HEALTHCHECK to the Docker image of the app

---

apps/openchallenges/organization-service/.openapi-generator/FILES
apps/openchallenges/organization-service/requests.http
apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/configuration/EnumConverterConfiguration.java
apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/model/dto/ChallengeContributionRoleDto.java
apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/model/dto/OrganizationSearchQueryDto.java
apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/model/repository/CustomOrganizationRepositoryImpl.java
apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/service/OrganizationService.java
apps/openchallenges/organization-service/src/main/resources/openapi.yaml

chore: Update the organization service to enable fetching contributions

---

.devcontainer/devcontainer.json
.github/workflows/ci.yml

The new image adds R to the dev container

chore: Update the devcontainer image to `7f9d3e3`

---

.github/workflows/ci.yml
tools/devcontainers/sage/.devcontainer/Dockerfile

chore: Update devcontainer CLI to v0.49.0

---

.devcontainer/devcontainer.json

- Update the dev container image in `devcontainer.json` to version `b397cf3`

chore: Update dev container image to `b397cf3`

---

docker/openchallenges/services/apex.yml
docker/openchallenges/services/api-gateway.yml
docker/openchallenges/services/app.yml
docker/openchallenges/services/challenge-service.yml
docker/openchallenges/services/config-server.yml
docker/openchallenges/services/elasticsearch.yml
docker/openchallenges/services/grafana.yml
docker/openchallenges/services/image-service.yml
docker/openchallenges/services/mariadb.yml
docker/openchallenges/services/minio.yml
docker/openchallenges/services/mysqld-exporter.yml
docker/openchallenges/services/organization-service.yml
docker/openchallenges/services/prometheus.yml
docker/openchallenges/services/rstudio.yml
docker/openchallenges/services/service-registry.yml
docker/openchallenges/services/thumbor.yml
docker/openchallenges/services/vault.yml
docker/openchallenges/services/zipkin.yml

fix: Fix typo in env var name `OPENCHALLENGES_VERION`

---

apps/openchallenges/app/.env.example

chore: Remove `API_GATEWAY_*` config params from the app

---

.github/workflows/ci.yml
dev-env.sh

Mitigate #1784
This is a temporary solution to enable the merging of other PRs.

fix: Exclude `schematic-api` from CI/CD

---

apps/openchallenges/apex/Dockerfile
apps/openchallenges/apex/templates/http.conf.template

Closes #1681
```console
$ docker ps -a --format="table {{.Names}}\t{{.Status}}"
NAMES                                 STATUS
openchallenges-apex                   Up 2 minutes (healthy)
```

feat: Add `HEALTHCHECK` to the apex image

---

apps/schematic/api-docs/redocly.yaml
docker/schematic/services/api.yml
docker/synapse/services/rstudio.yml
libs/schematic/api-description/build/openapi.yaml

- Rename `*_VERION` env vars to `*_VERSION`

fix: Rename `VERION` to `VERSION`

---

apps/schematic/api-docs/project.json

fix: Set schematic-api-docs dev server port to 7010

---

.github/workflows/scan-images.yml

chore: Scan all images when pushing to `main`

---

libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.ts
libs/openchallenges/home/src/lib/featured-challenge-list/featured-challenge-list.component.ts
libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.ts
libs/openchallenges/org-profile/src/lib/org-profile-challenges/org-profile-challenges.component.ts
libs/openchallenges/org-search/src/lib/org-search.component.ts
libs/openchallenges/user-profile/src/lib/user-profile-challenges/user-profile-challenges.component.ts
libs/openchallenges/user-profile/src/lib/user-profile-starred/user-profile-starred.component.ts

fix(bug): Fix key name for contribution role in the OrganizationSearchQuery

---

.github/workflows/scan-images.yml
.github/workflows/scan-repo.yml

fix: Trivy Action is ignore the option severity

---

.github/workflows/build-devcontainer-image.yml

chore: Push devcontainer image to GHCR

---

.github/workflows/build-devcontainer-image.yml

fix: Push devcontainer image to GHCR

---

libs/openchallenges/home/src/lib/sponsor-list/sponsor-list.component.html
libs/openchallenges/home/src/lib/sponsor-list/sponsor-list.component.ts

Fixes #1829 - addresses UI/UX feedback by Sage Design
* remove AWS logo
* use alternative ITCR logo
* use Sage logo with organization name

fix(ui): update list of logos on the homepage

---

libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.html

Closes #1827
- Make the OC intro paragraph shorter and more impactful.

fix: Make OC description on home page more impactful

---

package.json
yarn.lock

fix: Upgrade `Primeng`

---

docker/openchallenges/services/api-docs.yml

fix: Fix deployment of non-local OC API docs container

---

libs/openchallenges/team/src/lib/team.component.html

docs: Remove Amy from the Team page per her request

---

libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.html
libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.scss
libs/openchallenges/challenge/src/lib/challenge-organizers/challenge-organizers.component.html
libs/openchallenges/challenge/src/lib/challenge-organizers/challenge-organizers.component.scss
libs/openchallenges/org-profile/src/lib/_org-profile-theme.scss
libs/openchallenges/org-profile/src/lib/org-profile-members/org-profile-members.component.html
libs/openchallenges/org-profile/src/lib/org-profile-members/org-profile-members.component.scss

feat(ui): Still display tab description when data is unavailable

---

libs/openchallenges/home/src/_lib-theme.scss
libs/openchallenges/home/src/lib/_home-theme.scss
libs/openchallenges/home/src/lib/home.component.html
libs/openchallenges/home/src/lib/home.component.scss

feat(ui): Add announcement box in the home page

---

.github/workflows/ci.yml

Fixes a bug introduced in #1982

fix: Patch publish-image in CI workflow

---

package.json
yarn.lock

Fix [CVE-2023-3696](https://avd.aquasec.com/nvd/cve-2023-3696)

chore: Remove mongoose Node.js package

---

dev-env.sh

fix: Remove tput dependency from dev-env.sh

---

tools/devcontainers/sage/.devcontainer/Dockerfile

- Add [pnpm](https://pnpm.io/installation) to the devcontainer

chore(tools): Add pnpm to the devcontainer

---

tools/devcontainers/sage/.devcontainer/Dockerfile

- Update the Dev Container CLI
- Update most of the tools installed in the dev container

chore: Update Dev Container CLI

---

apps/schematic/api/schematic_api/controllers/storage_controller.py
apps/schematic/api/schematic_api/controllers/storage_controller_impl.py
apps/schematic/api/schematic_api/openapi/openapi.yaml
apps/schematic/api/schematic_api/test/test_storage_controller_endpoints.py
apps/schematic/api/schematic_api/test/test_storage_controller_impl.py
libs/schematic/api-description/build/openapi.yaml
libs/schematic/api-description/src/components/schemas/AssetViewJson.yaml
libs/schematic/api-description/src/openapi.yaml
libs/schematic/api-description/src/paths/assetTypes/@{assetType}/assetViews/@{assetViewId}/json.yaml

fixes [fds-766](https://sagebionetworks.jira.com/browse/FDS-766)

feat: Add /assetTypes/{assetType}/assetViews/{assetViewId}/json endpoint

---

.gitignore
apps/openchallenges/app/project.json
tools/sonar-scanner.sh

Closes #2051 
- Create the tool `tools/sonar-scanner.sh`
- Add the task `sonar` to the project `openchallenges-app`
The environment variable `SONAR_TOKEN` needs to be set to run Sonar and push the results to SonarCloud.
```console
$ nx sonar openchallenges-app
> nx run openchallenges-app:sonar
Project key: openchallenges-app
Sources: src/
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarScanner 5.0.1.3006
INFO: Java 17.0.8 Private Build (64-bit)
INFO: Linux 4.14.320-243.544.amzn2.x86_64 amd64
INFO: User cache: /opt/sonar-scanner/.sonar/cache
INFO: Analyzing on SonarCloud
INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
INFO: Load global settings
INFO: Load …
```

feat: Scan OC Angular app with Sonar

---

.github/ISSUE_TEMPLATE/1-bug.yml
.github/ISSUE_TEMPLATE/2-feature.yml
.github/ISSUE_TEMPLATE/3-documentation.yml
.github/ISSUE_TEMPLATE/4-story.yml

docs: Update the list of products in GH issue templates

---

apps/openchallenges/organization-service/build.gradle
apps/openchallenges/organization-service/gradle.properties
apps/openchallenges/organization-service/project.json

- Add the task `sonar` to the project `openchallenges-organization-service`
- Use `{projectRoot}` and `{projectName}` in `project.json` when possible

ci: Configure sonar for OC organization service

---

package.json
yarn.lock

fix: Update IBM OpenAPI Validator to v1.7.0

---

apps/schematic/api/schematic_api/controllers/schema_controller.py
apps/schematic/api/schematic_api/controllers/schema_controller_impl.py
apps/schematic/api/schematic_api/openapi/openapi.yaml
apps/schematic/api/schematic_api/test/test_schema_controller_endpoints.py
apps/schematic/api/schematic_api/test/test_schema_controller_impl.py
libs/schematic/api-description/build/openapi.yaml
libs/schematic/api-description/src/openapi.yaml
libs/schematic/api-description/src/paths/nodes/@{nodeDisplay}/isRequired.yaml

fixes [fds-822](https://sagebionetworks.jira.com/browse/FDS-822)

feat: add /nodes/{nodeDisplay}/isRequired endpoint

---

dev-env.sh

fix: Fix Unknown command-line option '--tag'

---

apps/openchallenges/challenge-service/project.json
apps/openchallenges/challenge-to-elasticsearch-service/project.json
apps/openchallenges/image-service/project.json
apps/openchallenges/kaggle-to-kafka-service/project.json
apps/openchallenges/organization-service/project.json
apps/openchallenges/user-service/project.json
apps/schematic/api/project.json
libs/openchallenges/api-client-angular/project.json
libs/openchallenges/api-client-r/project.json
libs/schematic/api-client-angular/project.json
libs/schematic/api-client-python/project.json

- Closes #2110
- Depends on #2104

refactor: Rename the task openapi-generate to generate

---

apps/schematic/api/schematic_api/controllers/storage_controller.py
apps/schematic/api/schematic_api/controllers/storage_controller_impl.py
apps/schematic/api/schematic_api/openapi/openapi.yaml
apps/schematic/api/schematic_api/test/test_storage_controller_endpoints.py
apps/schematic/api/schematic_api/test/test_storage_controller_impl.py
libs/schematic/api-description/build/openapi.yaml
libs/schematic/api-description/src/openapi.yaml

fixes [fds-900](https://sagebionetworks.jira.com/browse/FDS-900)

feat: Add /assetTypes/{assetType}/assetViews/{assetViewId}/datasets/{datasetId}/manifestJson endpoint

---

apps/openchallenges/challenge-service/src/main/resources/db/migration/V1.0.1__insert_temp_data.sql
apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.1__insert_temp_data.sql

Fixes #2131
* Added:
* 1 platform: EvalAI
* 3 organizations, including Kaggle (set its `public` flag to TRUE)
* Updated:
* challenge-platform relationships
* challenge counts
**New platform added: EvalAI**
**Kaggle as an organization**

fix(data): additional data updates/fixes

---

apps/schematic/api/.openapi-generator-ignore
apps/schematic/api/.openapi-generator/FILES
apps/schematic/api/schematic_api/controllers/versions_controller.py
apps/schematic/api/schematic_api/controllers/versions_controller_impl.py
apps/schematic/api/schematic_api/openapi/openapi.yaml
apps/schematic/api/schematic_api/test/test_version_endpoints.py
libs/schematic/api-description/build/openapi.yaml
libs/schematic/api-description/src/openapi.yaml
libs/schematic/api-description/src/paths/schematicVersion.yaml

fixes [fds-1025](https://sagebionetworks.jira.com/browse/FDS-1025)

feat: add /schematicVersion endpoint

---

libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.html
libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.spec.ts
libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.ts

fix(ui): fix metric bugs

---

libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.ts
libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.ts
libs/openchallenges/org-search/src/lib/org-search.component.ts

- fixes #2117 
- Stop sending a request to the image service when the image key is not present

fix(angular): stop requesting image url if key is not present

---

apps/openchallenges/challenge-service/.env.example
apps/openchallenges/organization-service/.env.example

* Add option `allowLoadLocalInfile=true` to `DB_URL`
* Fix typo
* Fix typo

feat: Add option `allowLoadLocalInfile=true` to `DB_URL`

---

libs/openchallenges/home/src/lib/home.component.html

refactor: Update OC Home banner content

---

libs/openchallenges/home/src/lib/home.component.html

refactor: Update OC banner text (take 2)

---

libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.ts
libs/openchallenges/challenge/src/lib/challenge-organizers/challenge-organizers.component.ts
libs/openchallenges/challenge/src/lib/challenge-overview/challenge-overview.component.ts
libs/openchallenges/challenge/src/lib/challenge-stargazers/challenge-stargazers.component.ts
libs/openchallenges/challenge/src/lib/challenge-stats/challenge-stats.component.ts
libs/openchallenges/org-profile/src/lib/org-profile-challenges/org-profile-challenges.component.ts
libs/openchallenges/org-profile/src/lib/org-profile-members/org-profile-members.component.ts
libs/openchallenges/org-profile/src/lib/org-profile-overview/org-profile-overview.component.ts
libs/openchallenges/org-profile/src/lib/org-profile-stats/org-profile-stats.component.ts
libs/openchallenges/ui/src/lib/avatar/avatar.component.ts
libs/openchallenges/ui/src/lib/button-github/button-github.component.ts
libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.ts
libs/openchallenges/ui/src/lib/checkbox-filter/checkbox-filter.component.ts
libs/openchallenges/ui/src/lib/navbar/navbar.component.ts
libs/openchallenges/ui/src/lib/organization-card/organization-card.component.ts
libs/openchallenges/ui/src/lib/paginator/paginator.component.ts
libs/openchallenges/ui/src/lib/person-card/person-card.component.ts
libs/openchallenges/ui/src/lib/search-dropdown-filter/search-dropdown-filter.component.ts
libs/openchallenges/ui/src/lib/user-button/user-button.component.ts
libs/openchallenges/user-profile/src/lib/user-profile-challenges/user-profile-challenges.component.ts
libs/openchallenges/user-profile/src/lib/user-profile-overview/user-profile-overview.component.ts
libs/openchallenges/user-profile/src/lib/user-profile-starred/user-profile-starred.component.ts
libs/openchallenges/user-profile/src/lib/user-profile-stats/user-profile-stats.component.ts

- closes #1966 
- add whether @input is required (all inputs are changed to `true` as long as it won't break the app, otherwise use `false`)

feat(angular): Add require for @input

---

libs/openchallenges/home/src/lib/challenge-registration/challenge-registration.component.scss
libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.html
libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.scss

Fixes #2193 
**Metrics section**
| <img width="416" alt="Screenshot 2023-10-04 at 1 39 46 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/ceb27f8c-3e87-45c3-9b48-c81f3e3262a7"> | <img width="410" alt="Screenshot 2023-10-04 at 1 41 20 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/7ec33182-5c76-42e2-b05b-e7efe9083476"> |
|-|-|
**Add a Challenge section**
| <img width="414" alt="Screenshot 2023-10-04 at 1 56 25 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/d2ae10cd-0001-47b0-b221-09178aedbe00"> | <img width="418" alt="Screenshot 2023-10-04 at 1 54 11 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/30938874-090f-45e9-95ce-d44aab05b4d4"> |
|-|-|

fix(ui): fix home page mobile-responsiveness

---

apps/openchallenges/app/project.json

Closes #2203
- Reduce the size of any Angular components to 10kb
- Check that we are indeed using ahead-of-time compilation (AOT)
- We are already using the default production config, which comes with the most important optimizations.
- AOT is used by default since Angular 9 (source)
- Use [`source-map-explorer`](https://www.npmjs.com/package/source-map-explorer) to analyze the content of the JS bundle
- Good watch: [Source Map Explorer, Totally Tooling Tips (S3, E13)](https://youtu.be/7aY9BoMEpG8?feature=shared)
Source maps are only generated with the development config.
```console
nx build openchallenges-app --configuration=development
```
```console
source-map-explorer dist/apps/openchallenges/app/browser/browser/main.370643f4d61747af.js --html output.html
```
```console
$ …
```

chore: Review and optimize OC web app bundle size

---

libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.html

This goes hand-in-hand with the recent DB update (#2234), where a new platform has been added.
**Landscape**
**Platforms section**
(Updated [Figma here](https://www.figma.com/file/kjlOBxTQpJY79hUju4LVUT/OC-Platforms?type=design&node-id=3-2&mode=design&t=EfduBwV0FckXDVIH-0))

fix(openchallenges): update platforms

---

apps/openchallenges/app/.env.example
apps/openchallenges/app/src/config/config.json
apps/openchallenges/app/src/config/config.json.template

- Add a missing `,` in `config.json.template`
- Sort config options with alphanumeric order

fix(openchallenges): fix typo in OC app config json file

---

libs/openchallenges/ui/src/lib/discord-button/discord-button.component.ts

Set the label of the button to "Join us on Discord" as proposed in #2283.

refactor(openchallenges): update the label of the Discord button

---

.vscode/settings.json

Closes #2292
- Enable Format on Save for JSON
- Enable Format on Save for JSON with Comments (jsonc)

feat(sage-monorepo): enable Format on Save for JSON and JSON with Comments

---

libs/openchallenges/challenge/src/lib/challenge.component.html

refactor(openchallenges): move the challenge section "Organizers" last

---

libs/openchallenges/home/src/lib/challenge-registration/_challenge-registration-theme.scss

Fixes #2311 
* set button text color to white
* add uppercase transformation
* formatting cleanup
This will update the section to match what is currently in production:

fix(openchallenges): fix button on home page

---

libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.html

Closes #2322
- Fix the layout of sponsor cards on the challenge page

fix(openchallenges): fix the layout of sponsor cards on the challenge page

---

apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/CustomChallengeRepositoryImpl.java

fix(openchallenges): fix challenge sorter by start date

---

.github/workflows/ci.yml

ci(openchallenges): replace `run-many` by `affected`

---

.github/CODEOWNERS

Closes #2247
- Add @gaiaandreoletti  as code owner of the OC data
- Remove @rrchai as code owner of the OC data
- Added @gaiaandreoletti and @milen-sage as team member with write access to this repo to make the CODE OWNERS file valid

chore(openchallenges): add Gaia as a code owner of the OC data

---

.github/ISSUE_TEMPLATE/1-bug.yml
.github/ISSUE_TEMPLATE/2-feature.yml
.github/ISSUE_TEMPLATE/3-documentation.yml
.github/ISSUE_TEMPLATE/4-story.yml
.github/workflows/lint-pr.yml
README.md
apps/iatlas/api/README.md

Closes #2405
- Add iAtlas to the list of products in the issue templates
- List iAtlas on the repo README
- Add the PR title scope "iatlas"
- Create empty project folder for `iatlas-api`

chore(sage-monorepo): create product workspace for iAtlas

---

apps/openchallenges/app/src/app/app.component.html

Contributes to #2439
Once merged, I will check where the list of GitHub "checks" for the commit merged to `main` include a dedicated Sonar check like shown in #2439.

ci(sage-monorepo): touch `openchallenges-app` to learn more about Sonar

---

.github/workflows/ci.yml

ci(sage-monorepo): restore sonar scan in CI workflow

---

apps/openchallenges/app/src/app/app.component.html

Contributes to https://github.com/Sage-Bionetworks/sage-monorepo/issues/2439

ci(sage-monorepo): undo openchallenges-app touch

---

.github/workflows/ci.yml

fix(sage-monorepo): add developer-friendly name to the new composite action

---

.github/workflows/sonar-scan.yml
apps/openchallenges/app/src/app/app.component.html

ci(sage-monorepo): try sonar scan trigger

---

.github/workflows/sonar-scan.yml
apps/openchallenges/app/src/app/app.component.html

ci(sage-monorepo): test sonar scan from PR from fork

---

.github/workflows/sonar-scan.yml
apps/openchallenges/app/src/app/app.component.html
apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/OrganizationServiceApplication.java

Contributes to #2450
- Update the sonar workflow to require Sonar to run before merging the PR

ci(sage-monorepo): test Sonar workflow with label-based approval

---

.vscode/settings.json

chore(sage-monorepo): disable Jest tests to watch changes by default

---

apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/service/ChallengeAnalyticsService.java
apps/openchallenges/db-update/update_db_csv.py

Temporary fix for #2499 (but we will probably want a more permanent fix)
* add to script so that the static plot data is also updated with the CSV files
> [!NOTE]
> ### [Preview of latest changes can be seen here](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2504#issuecomment-1947526943)

fix(openchallenges): update static plot numbers

---

libs/openchallenges/challenge-search/src/lib/challenge-search-filters.ts

Add-on to #2511
I got trigger happy, and merged in the PR before pushing in the final commit :woman_facepalming:

fix(openchallenges): reorder Submission Type facet values

---

.github/workflows/sonar-scan.yml

chore(sage-monorepo): patch Sonar GitHub workflow

---

docs/developers-guide/co-author.md
docs/developers-guide/creating-a-commit-with-multiple-authors.md
mkdocs.yml

- document how to add co-authors to commits

docs(sage-monorepo): add docs about co-authors

---

libs/openchallenges/team/src/lib/team.component.html
libs/openchallenges/team/src/lib/team.component.ts
libs/openchallenges/ui/src/lib/footer/footer.component.html
libs/openchallenges/ui/src/lib/footer/footer.component.ts

> [!IMPORTANT]
> To be merged _after_ March 4th!
* use Sage's new logo 
* remove `height` specifications; since the new logos are smaller than the previous logos, specifying the heights made the logos looked blurry, so they have been removed
* **Footer**
* **Meet the Team page**
* **Sage profile**

feat(openchallenges): update Sage logo

---

.devcontainer/devcontainer.json
dev-env.sh

- use the latest version of the dev container
- update the min required version of VS Code
- review of the VS Code extensions installed in the dev container

chore(sage-monorepo): update devcontainer version and min VS Code version

---

apps/openchallenges/edam-etl/Dockerfile
apps/openchallenges/edam-etl/docker-entrypoint.sh

fix(openchallenges): fix openchallenges-edam-etl image

---

.github/workflows/sonar-scan-pull-request.yml
.github/workflows/sonar-scan-push.yml

fix(sage-monorepo): enable Sonar to run on PRs

---

.github/workflows/sonar-scan-pull-request.yml

chore(sage-monorepo): simplify the sonar PR workflow

---

.devcontainer/devcontainer.json

Update the reference of the active devcontainer.
- performed additional tests on OpenChallenges manually in the new devcontainer

chore(sage-monorepo): update active devcontainer

---

dev-env.sh

fix(sage-monorepo): resolve "Corepack is about to download"

---

libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts

- fixes #2686 
The same function is used for challenge search bar (searchType = "challenges") and dropdown filter search bars, but some variables used for dropdown filters is never defined for "challenges". 
Moving those variables into the dropdown filter logics.

fix(openchallenges): fix bug in search bar on challenge search page

---

.github/CODEOWNERS

chore(sage-monorepo): remove Mialy from code owners

---

apps/openchallenges/challenge-service/build.gradle
apps/openchallenges/mariadb/Dockerfile
apps/openchallenges/organization-service/build.gradle
docker/openchallenges/services/mariadb.yml

Closes #2727
- Copy the folder that include init scripts to the MariaDB image
- Remove unused Flyway config

refactor(openchallenges): add init script to MariaDB image

---

apps/agora/data/project.json

Removes sonar target for `agora-data`
Fixes #2731
- Removes sonar target for `agora-data`

fix(agora): removes sonar target for agora-data

---

README.md
dev-env.sh

- Update the min version of VS Code to 1.92.1
- Invite to star the project sooner in the README

chore(sage-monorepo): update min VS Code version

---

apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/configuration/EurekaInstanceConfiguration.java
apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/configuration/EurekaInstanceConfiguration.java
libs/openchallenges/app-config-data/src/main/java/org/sagebionetworks/openchallenges/app/config/data/ChallengeServiceConfigData.java
libs/openchallenges/app-config-data/src/main/java/org/sagebionetworks/openchallenges/app/config/data/OrganizationServiceConfigData.java
oc-challenge-522.html

This PR implements two different solutions to make the challenge and organization services AWS aware. Hopefully at least one of them will enable the service to properly register its IP address to the service registry when deployed with AWS ECS.
Cc: @zaro0508 
- implement [a solution](https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/#using-eureka-on-aws) to make the challenge service AWS aware
- implement [another solution](https://medium.com/@harsugangwar/microservices-with-eureka-on-aws-ecs-a-guide-to-service-discovery-and-ci-with-aws-codebuild-0478a4a71ba2) to make the organization service AWS aware
Enable the feature in the challenge service with an environment variable:
```
OPENCHALLENGES_CHALLENGE_SERVICE_IS_DEPLOYED_ON_AWS=true
```
Enable the feature in the …

fix(openchallenges): make the challenge and organization services AWS aware (IT-3800)

---

.devcontainer/devcontainer.json

- Update the dev container used by the monorepo
- Update the Docker engine installed in the dev container

chore(sage-monorepo): update active dev container and Docker engine

---

.devcontainer/devcontainer.json
tools/devcontainers/sage/README.md

- Update the version of the dev container to fix `hadolint`
- Update the documentation to build and test the dev container locally

chore(sage-monorepo): update dev container to `fb4a44a` to fix `hadolint`

---

apps/openchallenges/thumbor/Dockerfile

An attempt to solve https://github.com/beeyev/thumbor-s3-docker/issues/35

chore(openchallenges): update Thumbor Docker image

---

apps/openchallenges/thumbor/Dockerfile

Fixes [IT-3919](https://sagebionetworks.jira.com/browse/IT-3919)
[IT-3919]: https://sagebionetworks.jira.com/browse/IT-3919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(openchallenges): switch back to non-slim Thumbor image (IT-3919)

---

.eslintrc.json
apps/sandbox/angular-app/.eslintrc.json
package.json
pnpm-lock.yaml

Contributes to https://sagebionetworks.jira.com/browse/ARCH-294
- Add the Tailwind CSS plugin for ESLint
- Update the root config of ESLint and the config of `sandbox-angular-app`

feat(sage-monorepo): add the Tailwind CSS plugin for ESLint (ARCH-294) 

---

.github/workflows/release.yml

Contributes to https://sagebionetworks.jira.com/browse/ARCH-304

feat(openchallenges): remove the `if:` constraint from the release workflow

---

.github/workflows/release.yml
apps/openchallenges/apex/project.json

Close https://sagebionetworks.jira.com/browse/ARCH-306

feat(sage-monorepo): release all the images of the specified product (ARCH-306)

---

lint-staged.config.js

- Test the projects affected by the staged files

feat(sage-monorepo): test the projects affected by the staged files

---

.github/CODEOWNERS

Please remove team members on temporary leave from the code owners file to prevent them from receiving unnecessary notifications from GitHub.

chore(sage-monorepo): update code owners

---

.github/workflows/scan-repo.yml

- Pin the version of several components (ubuntu, actions)
- Add manual and weekly trigger

chore(sage-monorepo): update Trivy repo scanning workflow (ARCH-320)

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/1-bug.yml
.github/ISSUE_TEMPLATE/2-feature.yml
.github/ISSUE_TEMPLATE/3-documentation.yml
.github/ISSUE_TEMPLATE/4-story.yml
.github/workflows/lint-dockerfiles.yml
.github/workflows/lint-pr.yml
.github/workflows/sonar-scan-push.yml
apps/sage/README.md
libs/sage/README.md
lint-staged.config.js

Closes https://sagebionetworks.jira.com/browse/ARCH-323
- Create folders `apps/sage` and `libs/sage`
- Update GitHub issue templates
- Update the configuration of the GitHub workflow that lint PR titles
- Update CODEOWNERS
- Fix staged-lint config to identify the Dockerfiles to lint

feat(sage-monorepo): create "sage" product space (ARCH-323)

---

apps/agora/apex/Dockerfile

Closes https://sagebionetworks.jira.com/browse/ARCH-327

chore(agora): add Caddyfile to the Docker image (ARCH-327)

---

.github/workflows/ci.yml
.github/workflows/release.yml
libs/sage-monorepo/nx-plugin/src/plugins/build-image-target.ts

Contributes to https://sagebionetworks.jira.com/browse/ARCH-336

fix(sage-monorepo): update task `build-image` configurations

---

apps/openchallenges/mariadb/project.json

Contributes to https://sagebionetworks.jira.com/browse/ARCH-336

fix(openchallenges): enable task inference for `openchallenges-mariadb:build-image`

---

apps/openchallenges/challenge-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
apps/openchallenges/nifi-registry/nifi_demo-version-2.json
apps/openchallenges/nifi/Dockerfile
apps/openchallenges/nifi/input/nifi_demo.csv
docker/openchallenges/services/nifi.yml

Closes https://sagebionetworks.jira.com/browse/ARCH-332
- Add the MySQL JDBC driver to the `openchallenges-nifi` Docker image.
- Add data flow that reads data from a CSV file and stores it in a SQL table.
Build all the OC Docker images:
```console
```
Start the OC stack:
```console
```
Build the Docker images:
```console
nx run-many -t build-image -p openchallenges-{nifi,nifi-registry}
```
Start NiFi and its registry:
```console
nx serve-detach openchallenges-nifi
```
1. In your browser, navigate to `http://localhost:18080/nifi-registry`.
2. Create a bucket named `openchallenges`.
3. Upload the JSON file of the PG as shown below.
1. Navigate to `https://localhost:8443/nifi/` (note the `https://` protocol).
2. Follow the …

feat(openchallenges): create data integration POC with Apache NiFi (ARCH-332)

---

apps/openchallenges/apex/Caddyfile

Contributes to [ARCH-371](https://sagebionetworks.jira.com/browse/ARCH-371)
- Remove the debug mode from the Caddyfile
- Format the Caddyfile with `caddy fmt --overwrite`
[ARCH-371]: https://sagebionetworks.jira.com/browse/ARCH-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(openchallenges): format Caddyfile

---

apps/openchallenges/apex/Caddyfile
apps/openchallenges/apex/Dockerfile
docker/openchallenges/services/apex.yml

Fixes https://sagebionetworks.jira.com/browse/ARCH-371

fix(openchallenges): configure OC apex to run on port 8000 again (ARCH-371)

---

nx.json

Closes https://sagebionetworks.jira.com/browse/ARCH-375

chore: remove Nx legacy cache (ARCH-375)

---

libs/agora/not-found/src/lib/not-found.component.html
libs/agora/not-found/src/lib/not-found.component.scss
libs/agora/not-found/src/lib/not-found.component.ts

Changing the design of the 404 page with design elements from the News page.

feat(agora): update not found page design (AG-1590)

---

dev-env.sh
tools/workspace-nuke.sh

- Create the script `tools/workspace-nuke.sh`.
- Prepare Python projects one at a time to prevent potential concurrency issue.

chore: create workspace-nuke script (SMR-3)

---

dev-env.sh

Closes https://sagebionetworks.jira.com/browse/SMR-5
Including or excluding projects based on tags is done differently for `nx run-many` and `nx affected`.
- https://nx.dev/nx-api/nx/documents/run-many
- https://nx.dev/nx-api/nx/documents/affected

fix: fix install commands in dev-env.sh (SMR-5)

---

.devcontainer/devcontainer.json
dev-env.sh
tools/workspace-install.sh

Closes https://sagebionetworks.jira.com/browse/SMR-14

chore: prepare Python projects in parallel and update active dev container (SMR-14)

---

.vscode/settings.json

Closes https://sagebionetworks.jira.com/browse/SMR-7

chore: prevent Gradle background tasks from running for too long (SMR-7)

---

libs/agora/home/src/lib/home.component.html

feat(agora): update copy (AG-1634)

---

apps/agora/app/src/app/app.routes.ts

/genes route not redirecting to home page.
/genes and /genes/gene-router have been migrated

fix(agora): fix routing (AG-1645)

---

.github/.devcontainer/Dockerfile

Contributes to https://sagebionetworks.jira.com/browse/SMR-23
Build the dev container Docker image locally.
```console
devcontainer build   --workspace-folder .github   --image-name ghcr.io/sage-bionetworks/sage-monorepo-devcontainer:local
```
Scan the image for CVEs.
```console
$ trivy image --severity CRITICAL ghcr.io/sage-bionetworks/sage-monorepo-devcontainer:local
...
ghcr.io/sage-bionetworks/sage-monorepo-devcontainer:local (ubuntu 24.04)
Total: 0 (CRITICAL: 0)
```

chore: update the tools installed within the dev container (SMR-23)

---

apps/amp-als/dataset-service-next/build.gradle.kts
apps/amp-als/dataset-service-next/gradle/libs.versions.toml
apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/configuration/HibernateSearchIndexBuild.java
apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/entity/DatasetEntity.java
apps/amp-als/dataset-service-next/src/main/resources/application.yml
docker/amp-als/services/opensearch.yml

Closes https://sagebionetworks.jira.com/browse/SMR-64
- Add JPA, Hibernate Search and Lombok dependencies.
- Add `DatasetEntity`.
- Add `HibernateSearchIndexBuild.java` to index mock dataset into OpenSearch at startup.
- Disable OpenSearch security plugin to simplify local development.
An index is automatically created in OpenSearch as soon as Hibernate Search is configured and the `DatasetEntity` class is defined. Initially, the index is empty.
```console
$ curl -X GET "http://amp-als-opensearch:8406/amp-als-dataset-000001/_search?pretty"
{
"took" : 2,
"timed_out" : false,
"_shards" : {
"total" : 1,
"successful" : 1,
"skipped" : 0,
"failed" : 0
},
"hits" : {
"total" : {
"value" : 0,
"relation" : "eq"
},
"max_score" : null,
"hits" : [ ]
}
}
```
The index contains three datasets after …

feat(amp-als): integrate Spring Boot 3 stub with OpenSearch and index mock datasets at startup (SMR-64)

---

apps/openchallenges/app/.env.example
apps/openchallenges/app/docker-entrypoint.d/10-envsubst-on-app-config-template.sh
apps/openchallenges/app/src/config/config.json
apps/openchallenges/app/src/config/config.json.template
libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
libs/openchallenges/config/src/lib/app.config.ts
libs/openchallenges/home/src/lib/home.component.html
libs/openchallenges/home/src/lib/home.component.ts

closes https://sagebionetworks.jira.com/browse/SMR-26
Adding config (`showAnnouncement`) to toggle for the home page announcement banner as needed in the future.
- Add `showAnnouncement` config and disable the announcement banner on Home page

feat(openchallenges): add config to toggle the home page announcement banner (SMR-26)

---

.devcontainer/devcontainer.json

Closes https://sagebionetworks.jira.com/browse/SMR-74

chore(sage-monorepo): update active dev container image with Java 21 (SMR-74)

---

apps/amp-als/dataset-service/build.gradle.kts
apps/model-ad/api/gradle.properties
apps/openchallenges/challenge-service/gradle.properties
apps/openchallenges/challenge-to-elasticsearch-service/gradle.properties
apps/openchallenges/kaggle-to-kafka-service/gradle.properties
apps/openchallenges/organization-service/gradle.properties
libs/amp-als/app-config-data/gradle.properties
libs/openchallenges/app-config-data/gradle.properties
libs/openchallenges/kafka-admin/gradle.properties
libs/openchallenges/kafka-consumer/gradle.properties
libs/openchallenges/kafka-model/build.gradle
libs/openchallenges/kafka-producer/gradle.properties
libs/sage/README.md
libs/shared/java/util/build.gradle

Closes https://sagebionetworks.jira.com/browse/SMR-75

fix(sage-monorepo): update Lombok to fix issue with JDK 21

---

.github/.devcontainer/Dockerfile

Closes https://sagebionetworks.jira.com/browse/SMR-76

chore(sage-monorepo): add ktlint to the dev container and update other tools (SMR-76)

---

.devcontainer/devcontainer.json

Closes https://sagebionetworks.jira.com/browse/SMR-76

chore(sage-monorepo): update active dev container with ktlint (SMR-76)

---

apps/amp-als/dataset-service/build.gradle.kts
lint-staged.config.js

Closes https://sagebionetworks.jira.com/browse/SMR-68

chore(sage-monorepo): format Kotlin files (SMR-68)

---

libs/agora/ui/src/lib/components/footer/footer.component.html
libs/agora/ui/src/lib/components/footer/footer.component.spec.ts
libs/agora/ui/src/lib/components/footer/footer.component.ts

Update footer logic to use Angular 16+ methods for handling subscriptions.
Code involves the use of:
`.pipe(takeUntilDestroyed())`
This ensures that there won't be memory leaks.

fix(agora): update footer logic (AG-1775)

---

dev-env.sh

A small improvement upon #3119.

chore(sage-monorepo): simplify `workspace-install-java-lib-projects`

---

libs/openchallenges/api-client-angular/src/test-setup.ts

This file was taken from a newly created Angular library: `nx g @nx/angular:lib libs/my-lib`.

chore(openchallenges): update `test-setup.ts` of the Angular API client for OC

---

apps/openchallenges/mcp-server/build.gradle.kts
apps/openchallenges/mcp-server/gradle/libs.versions.toml

- Closes https://sagebionetworks.jira.com/browse/SMR-105

refactor(openchallenges): update the OC MCP server to use Gradle Version Catalogs (SMR-105)

---

.devcontainer/devcontainer.json

- Closes https://sagebionetworks.jira.com/browse/SMR-111

chore(sage-monorepo): update dev container to bring GraalVM JDK distrib (SMR-111)

---

.devcontainer/devcontainer.json

- Closes https://sagebionetworks.jira.com/browse/SMR-113

chore(sage-monorepo): update active dev container to provide musl (SMR-113)

---

libs/amp-als/api-description/openapi-merge.yaml
libs/amp-als/api-description/openapi/dataset.openapi.yaml
libs/amp-als/api-description/openapi/openapi.yaml
libs/amp-als/api-description/openapi/user.openapi.yaml
libs/amp-als/api-description/project.json
libs/amp-als/api-description/src/components/schemas/HealthCheck.yaml
libs/amp-als/api-description/src/paths/healthCheck.yaml
libs/amp-als/api-description/src/user.openapi.yaml

- https://sagebionetworks.jira.com/browse/SMR-132

feat(amp-als): create placeholder API description for the upcoming AMP-ALS User Service

---

libs/explorers/util/src/index.ts
libs/explorers/util/src/lib/loading-container/loading-container.component.html
libs/explorers/util/src/lib/loading-container/loading-container.component.scss
libs/explorers/util/src/lib/loading-container/loading-container.component.spec.ts
libs/explorers/util/src/lib/loading-container/loading-container.component.ts
libs/explorers/util/src/lib/loading-icon/loading-icon.component.html
libs/explorers/util/src/lib/loading-icon/loading-icon.component.scss
libs/explorers/util/src/lib/loading-icon/loading-icon.component.ts

This PR creates a loading container that display the number of results.  See [Figma link](https://www.figma.com/design/GtUYqZBxoOnPtjV1hLcTgw/Model-AD-Explorer-Designs?node-id=798-11035&t=Du2yf5D1NVZ2NLEd-0)
This also makes the loading-icon component's colors configurable.
[link](https://sagebionetworks.jira.com/jira/software/c/projects/MG/boards/243?selectedIssue=MG-225)
https://www.loom.com/share/39e646724bb34b4995467a15166c5ef2

feat(model-ad): created loading-container and configurable loading-icon (MG-225)

---

apps/openchallenges/mcp-server/README.md

closes https://sagebionetworks.jira.com/browse/SMR-117
- Add Mermaid diagram of the OC MCP server infrastructure

feat(openchallenges): create Mermaid diagram of the OC MCP server infrastructure (SMR-117)

---

apps/agora/data/src/main.py

The last two [Agora e2e test runs timed out](https://github.com/Sage-Bionetworks/sage-monorepo/actions/runs/15565230651/job/43837832225?pr=3152) while downloading the team_images from Synapse. Since we plan to remove team_images from Agora in a future release, we will stop downloading these files in our local and CI environments and see if that fixes the CI timeout issue.
- [AG-1800](https://sagebionetworks.jira.com/browse/AG-1800)
- Stops downloading team_images in Agora `data`
- Maintains `team_images_id` in dataversion collection to stay aligned with the latest Agora data release
[AG-1800]: https://sagebionetworks.jira.com/browse/AG-1800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(agora): stop downloading team_images in local and CI environments (AG-1800)

---

.github/copilot-instructions.md
.github/instructions/angular/llms.md

Adds `copilot-instructions.md` for the monorepo using [Angular's llms.txt](https://github.com/angular/angular/blob/main/adev/src/content/ai/develop-with-ai.md) as a resource. 
> [!NOTE]
> Does not add `llms-full.txt` to `copilot_instructions.md`, because providing such a large document as context to every request (which may be unrelated to an Angular project) may slow down Copilot unnecessarily. We could consider creating a [separate instructions file](https://code.visualstudio.com/docs/copilot/copilot-customization#_use-instructionsmd-files) that will provide context to chats related to a subset of files or creating [a prompt](https://code.visualstudio.com/docs/copilot/copilot-customization#_prompt-files-experimental) that uses this document in the future.
- …

feat(sage): add copilot-instructions (SMR-172)

---

.eslintrc.json
libs/agora/genes/src/lib/components/gene-table/gene-table.component.html
libs/openchallenges/challenge/src/lib/challenge-stargazers/challenge-stargazers.component.html
libs/openchallenges/challenge/src/lib/challenge.component.html
libs/openchallenges/home/src/lib/featured-challenge-list/featured-challenge-list.component.html
libs/openchallenges/home/src/lib/topics-viewer/topics-viewer.component.html
libs/openchallenges/org-profile/src/lib/org-profile-stats/org-profile-stats.component.html
libs/openchallenges/ui/src/lib/navbar/navbar.component.html
libs/openchallenges/ui/src/lib/person-card/person-card.component.html
libs/openchallenges/ui/src/lib/user-button/user-button.component.html

- [SMR-33](https://sagebionetworks.jira.com/browse/SMR-33)
- [SMR-34](https://sagebionetworks.jira.com/browse/SMR-34)
- [AG-1734](https://sagebionetworks.jira.com/browse/AG-1734)
- [MG-272](https://sagebionetworks.jira.com/browse/MG-272)
- Replace Angular deprecated directives to the new control flow in all Angular projects.
- Update ESLint rule to require the use of Angular control flow.
[SMR-33]: https://sagebionetworks.jira.com/browse/SMR-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SMR-34]: https://sagebionetworks.jira.com/browse/SMR-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AG-1734]: https://sagebionetworks.jira.com/browse/AG-1734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

refactor(sage-monorepo): require the use of Angular control flow (SMR-33, SMR-34, AG-1734, MG-272)

---

apps/agora/data/pyproject.toml
apps/agora/data/src/main.py
apps/agora/data/uv.lock
apps/model-ad/data/.env.example
apps/model-ad/data/pyproject.toml
apps/model-ad/data/src/main.py
apps/model-ad/data/uv.lock

We intermittently see timeouts while downloading Agora data from Synapse for e2e tests in CI. Here, we improve our logging to help with debugging and update the synapseclient to v4.8.0.
Note: does not enable debug logging for synapseclient, since presigned URLs are logged and we upload the logs as public artifacts. However, the newer synapseclient version includes a progress bar of download progress, which should be helpful for debugging.
- [AG-11814](https://sagebionetworks.jira.com/browse/AG-1814)
- [AG-1527](https://sagebionetworks.jira.com/browse/AG-1527)
- Uses `logger` to log messages in `model-ad-data` and `agora-data` with timestamp
- Updates synapseclient to v4.8.0 for `model-ad-data` and `agora-data`
I ran the agora e2e job [4x on this …

fix(agora): update synapseclient to latest version (AG-1814), improve log message style (AG-1527)

---

.github/instructions/weekly-update.instructions.md

This PR adds initial instructions to generate a summary about the PRs merged into the monorepo over the last week.
- Depends on #3295
July 5-12, 2025
This week saw significant progress across multiple projects in the sage-monorepo, with improvements to data infrastructure, API enhancements, and technical modernization efforts.
The Model-AD team made significant progress updating their data infrastructure:
- **Data Version Upgrade**: Data release updated to version 63, with improved collection organization and indexing (@hallieswan)
- **MongoDB Schema Tools**: Added new tooling to generate schema files for improved documentation and validation (@sagely1)
- **UI Improvements**: Fixed style issues in the header components to ensure consistent rendering across devices (@sagely1)
- **Angular …

feat(sage-monorepo): add instructions to generate weekly updates about the PRs merged

---

apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/service/ChallengeService.java

Update only the incentives that have changed in the DB.
- [SMR-365](https://sagebionetworks.jira.com/browse/SMR-365)
- Update only the incentives that have changed in the DB.
[SMR-365]: https://sagebionetworks.jira.com/browse/SMR-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(openchallenges): update only the incentives that have changed in the DB (SMR-365)

---

.devcontainer/devcontainer.json

Add Microsoft PostgreSQL VS Code extension. The motivation is to ultimately replace SQLTools, which is less responsive.
This new extension provides an MCP server that we can use to explore data as well as generate ER diagrams.
> [!NOTE]
> This extension is available as a Preview. This [comment](https://github.com/microsoft/vscode-pgsql/issues/133#issuecomment-3189141285) mentions that it doesn't fully support project `settings.json` yet.
> [!WARNING]
> The settings provided bellow must be added to the user settings file, not the workspace settings.
- [SMR-391](https://sagebionetworks.jira.com/browse/SMR-391)
- Add Microsoft's PostgreSQL VS Code extension to the dev container.
The following configuration works only when added to the user `settings.json`, not the project (workspace) …

feat(sage-monorepo): add Microsoft PostgreSQL VS Code extension (SMR-391)

---

README.md

Redesign the main README.
- [SMR-496](https://sagebionetworks.jira.com/browse/SMR-496)
- Redesign the main README.
Visualize the README using GitHub preview.
[SMR-496]: https://sagebionetworks.jira.com/browse/SMR-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(sage-monorepo): redesign the main README (SMR-496)

---

.github/workflows/update-synapse-api.yml

Add missing single quote.
- [SMR-435](https://sagebionetworks.jira.com/browse/SMR-435)
- Fix GitHub workflow that updates Synapse API.
[SMR-435]: https://sagebionetworks.jira.com/browse/SMR-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(synapse): fix GitHub workflow that updates Synapse API - Take 3 (SMR-435)

---

.github/workflows/update-synapse-api.yml

Fix issue because of missing GitHub env var inside the dev container.

fix(synapse): fix issue because of missing GitHub env var inside the dev container

---

.github/workflows/update-synapse-api.yml

Pass env var `GITHUB_TOKEN` to the dev container in the workflow that updates Synapse API.

fix(synapse): pass env var `GITHUB_TOKEN` to the dev container in the workflow that updates Synapse API

---

.github/workflows/update-synapse-api.yml

Rewrite the Synapse update workflow to be much simpler and easier to maintain. Now using the GH action `peter-evans/create-pull-request@v7`.

refactor(synapse): rewrite the Synapse update workflow
