Sage-Bionetworks/sage-monorepo

- README.md
Fixes #51 
- Add required Node.js version
- Add `pipenv` as a requirement under the section README > Development
> Update required node version + add pipenv requirement

- libs/web/ui/.eslintrc.json
- libs/web/ui/src/lib/button-github/button-github.component.html
- libs/web/ui/src/lib/button-github/button-github.component.spec.ts
- libs/web/ui/src/lib/button-github/button-github.component.ts
- libs/web/ui/src/lib/footer/footer.component.spec.ts
- libs/web/ui/src/lib/navbar/navbar.component.spec.ts
- package.json
- yarn.lock
- Add support for Jest unit tests in the ESLint configuration of the project `web-ui`
- Restore unit test files for the three components in `web-ui`
```console
nx test web-ui
> nx run web-ui:test
PASS   web-ui  libs/web/ui/src/lib/navbar/navbar.component.spec.ts
PASS   web-ui  libs/web/ui/src/lib/footer/footer.component.spec.ts
PASS   web-ui  libs/web/ui/src/lib/button-github/button-github.component.spec.ts
Test Suites: 3 passed, 3 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        2.313 s
Ran all test suites.
———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
>  NX   Successfully ran target test for project web-ui
See Nx Cloud run …
```
> Configure ESLint to work with Jest in the project `web-ui`

- nx.json
- Enable caching for several tasks
- Enable the `scan` option to push the log output of cacheable tasks to Nx cloud
> Enable nx scan option

- apps/web-app/Dockerfile
For some reason, cloning this repo using the `git://` protocol failed for Rong. Instead, we are now cloning using the `https://` protocol.
> Fix web-app docker issue related to CA

- apps/web-app/src/app/app-routing.module.ts
- apps/web-app/src/app/app-sections.ts
- libs/web/challenges/.eslintrc.json
- libs/web/challenges/README.md
- libs/web/challenges/jest.config.js
- libs/web/challenges/project.json
- libs/web/challenges/src/index.ts
- libs/web/challenges/src/lib/challenges.component.html
- libs/web/challenges/src/lib/challenges.component.spec.ts.off
- libs/web/challenges/src/lib/challenges.component.ts
- libs/web/challenges/src/lib/challenges.module.ts
- libs/web/challenges/src/test-setup.ts
- libs/web/challenges/tsconfig.json
- libs/web/challenges/tsconfig.lib.json
- libs/web/challenges/tsconfig.spec.json
- libs/web/org-profile/project.json
- libs/web/org-profile/src/lib/org-profile.component.html
- tsconfig.base.json
- workspace.json
Adds the Challenges page, previously called "Search" page. The new name and route (`/challenges`) is more descriptive. This change is motivated by our plan to add another "search" page to search for people, organizations and sponsors.
This search page is currently empty. Its original content will be restored in the near future.
> Add Challenges page

- apps/web-app/src/app/app-routing.module.ts
- libs/web/org-search/.eslintrc.json
- libs/web/org-search/README.md
- libs/web/org-search/jest.config.js
- libs/web/org-search/project.json
- libs/web/org-search/src/index.ts
- libs/web/org-search/src/lib/org-search.component.html
- libs/web/org-search/src/lib/org-search.component.spec.ts
- libs/web/org-search/src/lib/org-search.component.ts
- libs/web/org-search/src/lib/org-search.module.ts
- libs/web/org-search/src/test-setup.ts
- libs/web/org-search/tsconfig.json
- libs/web/org-search/tsconfig.lib.json
- libs/web/org-search/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
Add org search page. This PR adds the route `/orgs`. The page is currently empty.
> Add org search page

- .github/workflows/ci.yml
Fixes #143 
Cache is retained for only [7 days](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy). The cache is now no longer poisoned.
> Restore pipenv cache in CI/CD workflow

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- .vscode/settings.json
- fixes #154 
---
❌  force the extension to run jest testing via nx 
```json
"jest.jestCommandLine": "bash -c '. ./dev-env.sh && challenge-registry-test'",
```
The test can run successfully, but the UI is not displayed properly: 1. pass/fail icons not showing anymore 2. folder is not able to expand 3. the test result (0/0 passed) is not right. Not sure how to make this extension fit our nx config yet. 
I just use default settings for now, the caveat is that it will not benefit from the nx caches. The `--runInBand` is enabled by default setting of this extension, so the overall speed is not bad.
> Add GUI plugin in vscode for jest

- apps/web-app/README.md
Fixes #166 
- Describe how to start the challenge registry REST API before starting to contribute to the challenge registry web app.
- The challenge registry REST API already includes instructions on how to start the MongoDB instance required to develop the REST API.
> Describe how to start api before contributing to the web-app

- .devcontainer/devcontainer.json
- apps/web-app/README.md
- docker-compose.yml
- tools/devcontainers/challenge-devcontainer/.devcontainer/devcontainer.json
- Fixes #261 
- Fixes #279
The issue was that the web app is requiring Keycloak (KC) to be up and running. Another reason may have been that the KC port may not have been forwarded to the host (see #279).
I may have said that the web app was not yet depending on KC, which is not true. Running the following commands solves the issue should enable to start the backend components with Docker + start the web app in development mode:
```console
challenge-registry-prepare
yarn build-images
docker compose up challenge-registry-api challenge-keycloak -d
nx serve web-app
```
Navigate to http://localhost:4200
Note: The commands listed above work for this commit. They are expected to be renamed in future PRs.
> Fix challenge registry blank page

- dev-env.sh
The projects that compose the backend have now the task `serve-detach` that starts the project using docker. For example, running `challenge-registry-serve` automatically starts all the required backend services using docker.
I currently need to often stop all the containers using `docker stop $(docker ps -q)`. It's not a complicated command but I could use an alias, which is what this PR suggests. The alias is `challenge-docker-stop`.
> Add alias `challenge-docker-stop` to stop running containers

- docs/develop-on-a-remote-host.md
In an effort to move away from the soon-to-be-deprecated shared AWS Sandbox account, I went through the steps of deploying an EC2 with the Service Catalog instead.  Success!:
I made note of the steps I took and have updated the doc page accordingly.
> Update docs for developing on a remote host

- apps/challenge-api-gateway/docker-compose.yml
- apps/challenge-api-gateway/requests.http
- apps/challenge-keycloak/docker-compose.yml
- apps/challenge-mariadb/docker-compose.yml
- apps/challenge-mongodb/docker-compose.yml
- apps/challenge-postgresql/docker-compose.yml
- apps/challenge-service-registry/docker-compose.yml
- apps/challenge-user-service/docker-compose.yml
- apps/challenge-user-service/src/main/resources/application.yml
- tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile
- Fixes #338 
- Fixes #336 
- This PR does not replace all the occurrences of `localhost`. This is fine as the remaining occurrences will be replaced when the respective apps are updated.
- Place ELK+ apps in docker network `challenge-elk`.
- Place backend apps in docker network `challenge`.
- Configure user service to register to Eureka using its IP address instead of its hostname (solves the `localhost` issue).
- Use hostnames aliases instead of `localhost` in `requests.http` of the API gateway.
- Add the command `ip` to the devcontainer to get host and docker IP addresses.
> Restore docker networks

- .github/workflows/ci.yml
Test again all the projects in the CI workflow instead of just the affected projects. Since we are using Nx Cloud, the CI workflow should be able to leverage the remote cache instead of effectively running the tests for all the projects.
> Fix coverage in CI workflow

- .vscode/settings.json
Fixes #420 
This PR configure the Java formatter (RedHat) to use Google Style configuration file already located in the root folder. This configuration specifies that the max line length is 100.
> Configure Java formatter to use Google Style

- .github/workflows/ci.yml
- apps/challenge-api-gateway/project.json
- apps/challenge-auth-service/project.json
- apps/challenge-config-service/project.json
- apps/challenge-core-service/pom.xml
- apps/challenge-core-service/project.json
- apps/challenge-service-registry/project.json
- apps/challenge-user-service/project.json
- libs/shared-java/challenge-util/project.json
- Fixes #422 
- Fixes #503 
- Install sequentially the maven binary required by each Java project.
- Install sequentially the dependencies of the Java projects.
> Install Maven and Java project dependencies sequentially

- .husky/post-checkout
- .husky/post-merge
- .husky/post-rebase
- .husky/post-rewrite
Fixes #564
I adopt the same approach as we use to install the Node.js dependencies: I configured the git hooks to install all the Java dependencies one by one to avoid the concurrency issue.
> fix: Fix issue that arises when downloading Java dependencies concurrently

- .devcontainer/devcontainer.json
- package.json
- tools/check-devcontainer-version.js
> fix: `check-devcontainer-version.js` no longer needs non-native Node packages

- tools/check-java-packages.js
> fix: No longer rely on CHALLENGE_DIR in git hooks

- libs/challenge-registry/user-profile/src/lib/user-profile.component.scss
fixes #533
I stretch the width to 100% on the user profile page to match navbar and footer, which are using 100% width. The font sizes in the user profile page will remain relatively larger since it's configured using wider predefined screen width - I will leave it for now.
> feat(ui): Fix width of user profile page

- yarn.lock.readme.md
Fixes #633 
- This PR aims to clarify how to add, remove and update npm dependencies. It also provide the main motivations for using `yarn.lock` in this project.
> docs: Add `yarn.lock.readme.md`

- apps/challenge-user-service/build.gradle
- apps/challenge-user-service/project.json
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/ChallengeUserServiceApplication.java
Fixes #701 
- Running `nx serve challenge-user-service` now starts two processes:
- `./gradlew build --continuous` rebuild the app upon saving files.
- `./gradlew bootRun` in combination with `spring-boot-devtools` reload the Spring Boot app when build files have changed.
```console
$ nx serve challenge-user-service
...
> Task :check
> Task :build
BUILD SUCCESSFUL in 8s
8 actionable tasks: 5 executed, 3 up-to-date
Waiting for changes to input files...
```
> feat(java): Serve Spring Boot apps in watch mode with Gradle

- apps/challenge-user-service/build.gradle
- apps/challenge-user-service/project.json
Fixes #758 
- Fix how the docker image is built for this first Java project with Gradle.
Start the Challenge User API service and all its dependencies (e.g. dockerized MariaDB instance) with:
```console
nx serve-detach challenge-user-service
``
Open your browser and navigate to http://localhost:8083 to access the Swagger UI.
> fix(user-service): fix image build of the User API microservice

- .devcontainer/devcontainer.json
- .vscode/extensions.json
Fixes #726
- Add the VS Code extension [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) to quickly find TODO across the entire workspace.
In VS Code:
`Ctrl + Shift + P` > `Todo Tree: Export tree`:
Extension panel is accessible from VS Code vertical toolbar:
Support multiple tags (e.g. `TODO` and FIXME`) and allow to create/customize tags:
> feat(devcontainer): add VS Code extension Todo Tree

- .github/renovate.json
Motivations:
- Avoid wasting CPU time spent in running rebased PR branches
- Free resources for important CI workflow
- Avoid making noise in the contribution graphs
> chore(deps): disable renovate PR autorebase and enable gradle-wrapper manager

- apps/challenge-user-service/project.json
- Add the dependency `^install` to the user service task `serve`. This is required to install the local Java libraries that the user service depends on.
> fix(api): : add the dependency `^install` to the user service task `serve`

- .devcontainer/devcontainer.json
- tools/devcontainers/challenge/.devcontainer/Dockerfile
Fixes #856
The default value was around 8k.
```console
vscode@13deef517dad:/workspaces/challenge-registry$ cat /proc/sys/fs/inotify/max_user_watches
524288
```
> fix: Increase the max number of file watchers

- .github/workflows/build-devcontainer-image.yml
- .github/workflows/ci.yml
- tools/devcontainers/challenge/.devcontainer/README.md
- The CI workflow now uses the latest version of the dev container.
- The GH workflow only build a new dev container when its definition has changed (e.g. not when README.md has changed).
> chore: Update dev container used in CI workflow

- .vscode/settings.json
- apps/challenge-registry/project.json
- apps/challenge-registry/src/app/app.component.ts
- apps/challenge-registry/src/app/app.module.ts
- apps/challenge-registry/src/app/initialize-keycloak.factory.ts
- dev-env.sh
- docs/linters-and-formatters.md
- Fixes #880
- Fixes #888 
- Keycloak is no longer initialized when when page is rendered on the server side.
- First I tried providing a fake `window` to the server with the package [domino](https://www.npmjs.com/package/domino), but then the app wouldn't load.
- Tweaked the configuration of the VS Code extension ESLint related to formatting on save.
- Update the command `challenge-install` to install Gradle binary too.
- Bumped into #888
> fix: Fix Keycloak undefined `window` when using SSR

- libs/challenge-registry/home/src/lib/challenge-search/challenge-search.component.scss
Bug fix for #893.
**Screen width >481px**
**Screen width <481px**
> fix(ui): add responsiveness to top div

- libs/challenge-registry/challenge-search/src/_lib-theme.scss
- libs/challenge-registry/challenge-search/src/lib/_challenge-search-theme.scss
- libs/challenge-registry/challenge-search/src/lib/challenge-search.component.html
- libs/challenge-registry/challenge-search/src/lib/challenge-search.component.scss
- libs/challenge-registry/challenge-search/src/lib/challenge-search.component.ts
- libs/challenge-registry/challenge-search/src/lib/challenge-search.module.ts
- libs/challenge-registry/themes/src/_index.scss
Addresses #748:
Notes:
* Breadcrumbs still need some alignment adjustments but I figured we had enough to get the idea for now.
* The "Add Challenge" button is not added yet; will incorporate in 2023 Q1 when the service is ready.
* The "Sort by" is not added; I couldn't remember if this was an option with the pagination component already?
* For facets, I only listed 3 for now and get those working first.
* Not sure what's going on but the `mat-select-panel` is transparent and I wasn't able to adjust the background color:
I found a related [SO post here](https://stackoverflow.com/questions/52988519/mat-select-options-became-transparent-after-updating-to-angular-material-v7) -- maybe this is our issue too?
* Couldn't get the `mat-checkbox` to respond..... 
TODOs (will finish in this PR):
- …
> feat(ui): search page

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- .vscode/settings.json
Fixes #966
- Remove lombok VS Code extension, which is now part of Language Support for Java(TM) by Red Hat.
- Remove VS Code setting `java.jdt.ls.lombokSupport.enabled`, which is already true by default.
> fix: Remove lombok VS Code extension

- apps/challenge-api-gateway/src/main/java/org/sagebionetworks/challenge/configuration/SecurityConfiguration.java
- apps/challenge-organization-service/requests.http
- apps/challenge-organization-service/src/main/java/org/sagebionetworks/challenge/api/OrganizationApi.java
- apps/challenge-organization-service/src/main/java/org/sagebionetworks/challenge/api/OrganizationApiDelegate.java
- apps/challenge-organization-service/src/main/java/org/sagebionetworks/challenge/api/OrganizationApiDelegateImpl.java
- apps/challenge-organization-service/src/main/java/org/sagebionetworks/challenge/exception/GlobalErrorCode.java
- apps/challenge-organization-service/src/main/java/org/sagebionetworks/challenge/exception/GlobalExceptionHandler.java
- apps/challenge-organization-service/src/main/java/org/sagebionetworks/challenge/exception/InvalidEmailException.java
- apps/challenge-organization-service/src/main/java/org/sagebionetworks/challenge/exception/InvalidOrganizationException.java
- apps/challenge-organization-service/src/main/java/org/sagebionetworks/challenge/exception/OrganizationAlreadyExistsException.java
- apps/challenge-organization-service/src/main/java/org/sagebionetworks/challenge/service/OrganizationService.java
- apps/challenge-organization-service/src/main/resources/openapi.yaml
- libs/api-spec/build/openapi.yaml
- libs/api-spec/build/organization.openapi.yaml
- libs/api-spec/src/components/parameters/path/organizationId.yaml
- libs/api-spec/src/organization.openapi.yaml
- libs/api-spec/src/paths/organizations/@{organizationId}.yaml
Fixes #976 
- Added path to the Organization service to get an org by ID.
- Configured the API gateway security to allow public access to the new path.
- Added example requests to `requests.http`.
- The error returned by the paths of this service do not match the Error schema. I now have a better understanding of how to handle error in the context of microservices. This work will be implemented in a separate PR.
`requests.http`:
```console
GET {{organizationServiceHost}}/organizations/1
GET {{apiGatewayHost}}/api/v1/organizations/1
```
Output:
```console
HTTP/1.1 200 OK
transfer-encoding: chunked
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: …
```
> feat: Update the organization service to get org by ID

- apps/challenge-organization-service/src/main/resources/openapi.yaml
- apps/challenge-user-service/src/main/resources/openapi.yaml
- libs/api-client-angular/openapitools.json
- libs/api-client-angular/project.json
- libs/api-client-angular/src/lib/.openapi-generator/FILES
- libs/api-spec/build/base.openapi.yaml
- libs/api-spec/build/openapi.yaml
- libs/api-spec/build/organization.openapi.yaml
- libs/api-spec/build/user.openapi.yaml
- libs/api-spec/src/base.openapi.yaml
- libs/api-spec/src/organization.openapi.yaml
- libs/api-spec/src/user.openapi.yaml
Fixes #986
- Add the property `servers` to the OA definition
- Specify the Angular version that the OA generator must use to generate the client.
> feat: Add `servers` properties to OA description

- apps/challenge-registry/project.json
- apps/challenge-registry/src/app/app.component.ts
- apps/challenge-registry/src/app/app.module.ts
- apps/challenge-registry/src/proxy.conf.json
- libs/challenge-registry/org-profile/src/lib/org-profile.component.ts
Fixes #984 
- Get list of organizations from the backend on any org profile page (demo).
- Configure API client in `app.module.ts` of the challenge registry app.
- Add the project `challenge-organization-service` to the dependencies of the registry app.
- `nx serve challenge-registry`
- Check that the data can be retrieved:
- Directly from the microservice: http://localhost:8084/organizations
> **Note**
> This url will likely be changed in the future to include "/api" in the base url. This change will be transparent to everyone because the web app is sending requests to the API gateway (see below).
- From the API gateway:  http://localhost:8082/api/v1/organizations
- From any org profile page (displayed in browser console): http://localhost:4200/org/awesome-org
> feat: Populate the Organization page with data from the backend

- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/exception/ErrorConstants.java
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/exception/GlobalErrorCode.java
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/exception/GlobalExceptionHandler.java
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/exception/InvalidEmailException.java
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/exception/InvalidUserException.java
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/exception/SimpleChallengeGlobalException.java
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/exception/UserAlreadyRegisteredException.java
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/exception/UserNotFoundException.java
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/exception/UsernameAlreadyExistsException.java
- apps/challenge-user-service/src/main/java/org/sagebionetworks/challenge/service/UserService.java
Fixes #980
- The errors returned are now meeting the BasicError schema.
- Code reused from the Organization service.
- Fix issues with listing users and getting user by ID work.
> **Warning**
> This update requires the developer to re-import the Keycloak data. The container of Keycloak must be stopped before running the following command.
```console
rm -fr apps/challenge-keycloak/data/h2/*
nx import-dev-data challenge-keycloak
```
- Needed to update the `auth_id` value in the SQL seed data
> feat: Add error handling to the User service

- apps/challenge-service/.openapi-generator-ignore
- apps/challenge-service/.openapi-generator/FILES
- apps/challenge-service/build.gradle
- apps/challenge-service/gradle.properties
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/api/ChallengeApi.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/api/ChallengeApiDelegate.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/api/ChallengeApiDelegateImpl.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/configuration/EnumConverterConfiguration.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeCreateRequestDto.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeDto.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeStatusDto.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/ChallengeEntity.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/mapper/ChallengeMapper.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/ChallengeRepository.java
- apps/challenge-service/src/main/java/org/sagebionetworks/challenge/service/ChallengeService.java
- apps/challenge-service/src/main/resources/db/migration/V1.0.0__create_challenge_table.sql
- apps/challenge-service/src/main/resources/db/migration/V1.0.1__temp_data.sql
- apps/challenge-service/src/main/resources/openapi.yaml
- libs/api-spec/build/challenge.openapi.yaml
- libs/api-spec/build/openapi.yaml
- libs/api-spec/src/components/parameters/query/challenge/status.yaml
- libs/api-spec/src/components/schemas/ChallengeCreateRequest.yaml
- libs/api-spec/src/components/schemas/ChallengeCreateResponse.yaml
- libs/api-spec/src/components/schemas/ChallengeStatus.yaml
- libs/api-spec/src/paths/challenges.yaml
Fixes #1027
- Update the OA description
- Add the property `Challenge.status`
- Enable to filter list of challenge by their status
- Update the Challenge service
- List of challenges is filtered with querydsl.
- Getting the list of challenges will return an internal error if the query parameter `status` is missing from the `/challenges` query. This will be addressed in a following PR that adds more filters. I plan to adopt this [approach](https://samuel-mumo.medium.com/dynamic-queries-and-querydsl-jpa-support-in-spring-a1b4e233084b) which is suitable when we have many filters.
```
http://localhost:8085/v1/challenges?pageNumber=0&pageSize=100&status=upcoming&status=active
{
"number": 0,
"size": 100,
"totalElements": 2,
"challenges": …
```
> feat: Enable to filter list of challenges returned by the Challenge service by status

- tools/devcontainers/challenge/.devcontainer/Dockerfile
- Add `python3-dev` to the dev container, required to install uWSGI in Python projects.
> feat: Add python3-dev to dev container

- .devcontainer/devcontainer.json
- apps/challenge-registry/opensearch-dashboards/.env.example
- apps/challenge-registry/opensearch-dashboards/Dockerfile
- apps/challenge-registry/opensearch-dashboards/docker-compose.yml
- apps/challenge-registry/opensearch-dashboards/project.json
- apps/challenge-registry/opensearch/.env.example
- apps/challenge-registry/opensearch/Dockerfile
- apps/challenge-registry/opensearch/docker-compose.yml
- apps/challenge-registry/opensearch/project.json
- tools/configure-hostnames.sh
Fixes #1105 
- Add the project `challenge-registry-opensearch`
- Use version 1.x of OpenSearch because version 2.x is not documented as being [supported by Hibernate Search](https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#elasticsearch-integration)
- Add the project `challenge-registry-opensearch-dashboards`
- Reserve ports for OpenSearch and OpenSearch Dashboards
- They are a subset of the ports previously defined for ELK
Start OpenSearch:
```console
nx serve challenge-registry-opensearch
```
Run the test requests provided on Docker Hub:
```console
$ curl -XGET https://localhost:9200 -u admin:admin --insecure
{
"name" : "5d8f395238cd",
"cluster_name" : "docker-cluster",
"cluster_uuid" : "6KDbY2zaRsShlxZmvk-0Dw",
"version" : {
"distribution" : "opensearch", …
```
> feat: Add OpenSearch and OpenSearch Dashboards to the Challenge Registry

- apps/challenge-registry/app/project.json
It seems the initial budget size exceeds the limits of 1mb, which caused the CI failed [here](https://github.com/Sage-Bionetworks/challenge-registry/actions/runs/3833764119/jobs/6525526629#step:16:225).
Double the budget size to 2mb.
> feat: increase the budget limit

- .vscode/settings.json
Fixes #1052 
- Disable format on save for Java files because the current setup is too slow.
- It takes 1-5 seconds to format after saving the files.
- Files are already formatted by the pre-commit hook.
> feat: Disable format on save for Java files

- .husky/post-checkout
- .husky/post-merge
- .husky/post-rewrite
- tools/check-python-dependencies.js
Fixes #1125 
```console
vscode@8938397bfb17:/workspaces/sage-monorepo$ git checkout prepare-python-dependencies 
Switched to branch 'prepare-python-dependencies'
Your branch is up to date with 'origin/prepare-python-dependencies'.
✨ Preparing Node.js dependencies
✨ Preparing Java dependencies
✨ Preparing Python dependencies
vscode@8938397bfb17:/workspaces/sage-monorepo$
```
> feat: Prepare Python dependencies during git moves

- libs/challenge-registry/login/src/lib/login.component.html
- libs/challenge-registry/login/src/lib/login.component.scss
- libs/challenge-registry/login/src/lib/login.module.ts
- libs/challenge-registry/signup/src/lib/signup.component.html
- libs/challenge-registry/signup/src/lib/signup.component.scss
- libs/challenge-registry/signup/src/lib/signup.module.ts
- libs/challenge-registry/ui/src/lib/navbar/navbar.component.html
Addresses #1151 :
I think some fine-tuning details are still needed, but this should be enough for our closed launch.
> style(ui): fix login and register pages

- apps/challenge-registry/challenge-service/requests.http
- apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/ChallengeEntity.java
- apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/SimpleChallengeInputDataTypeEntity.java
- apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/SimpleChallengePlatformEntity.java
- apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/CustomChallengeRepositoryImpl.java
- apps/challenge-registry/challenge-service/src/main/java/org/sagebionetworks/challenge/service/ChallengeService.java
Fixes #1178 
- Filter challenges with the query parameter `inputDataTypes`.
- Enable full-text search to search using a challenge input data types.
- Update API client for Angular.
List the challenges that include the input data type `genomic`:
```console
GET {{basePath}}/challenges?inputDataTypes=genomic
HTTP/1.1 200 
{
"number": 0,
"size": 100,
"totalElements": 2,
{
"id": 1,
"name": "The Digital Mammography DREAM Challenge",
"headline": "Example headline",
"description": "Example description",
"status": "upcoming",
"difficulty": "good_for_beginners",
"platform": {
"id": 1,
"slug": "synapse",
"name": "Synapse"
},
"incentives": [
"monetary",
"publication"
],
"submissionTypes": [
"container_image"
],
"inputDataTypes": …
```
> feat: Filter the challenges by input data types (backend)

- .devcontainer/devcontainer.json
- apps/openchallenges/zipkin/Dockerfile
- apps/openchallenges/zipkin/docker-compose.yml
- apps/openchallenges/zipkin/project.json
- tools/configure-hostnames.sh
Fixes #1200 
- Add the project `openchallenges-zipkin` (Docker service)
- Reserve the port 9411 for Zipkin
Start the Zipkin server:
```console
nx serve openchallenges-zipkin
```
Access Zipkin UI on `http://localhost:9411`:
> feat: Add zipkin server

- apps/openchallenges/challenge-service/build.gradle
- apps/openchallenges/challenge-service/project.json
- apps/openchallenges/challenge-service/src/main/resources/application.yml
Fixes #1202 
- Add Sleuth to the challenge service
- Push logs traces to Zipkin server
- Add Zipkin project as a dependency of the challenge service
- Zipkin stores the traces in memory by default. E.g., stopping and restarting its container will delete the existing traces.
- [Zipkin supports different types of storage](https://hub.docker.com/r/openzipkin/zipkin/), including Elasticsearch.
- If Zipkin is not running when the challenge service starts, a Connection Refused is thrown (once?). This does not prevent the service to work and respond to the request.
Analyze the traces of the requests sent to the challenge service with Zipkin:
> feat: Push traces from the challenge service to Zipkin

- apps/openchallenges/challenge-service/project.json
- apps/openchallenges/challenge-service/requests.http
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeDirectionDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeSearchQueryDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/challenge/model/dto/ChallengeSortDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/challenge/model/entity/ChallengeEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/challenge/model/repository/CustomChallengeRepositoryImpl.java
- apps/openchallenges/challenge-service/src/main/resources/db/migration/V1.1.0__insert_data.sql
- apps/openchallenges/challenge-service/src/main/resources/openapi.yaml
- libs/openchallenges/api-description/build/challenge.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeDirection.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeSort.yaml
Fixes #1157 
- Add two example challenges: one organized in 2024 and one in 2025.
- Add the option to sort challenges by `starting_soon` and `ending_soon`.
- Accept `null` direction so that the backend can decide on the default to choose (`desc` or `asc`).
- Example 1: `/challenges?sort=starred` should use the default direction `desc`
- Example 2: `/challenges?sort=starting_soon` should use the default direction `asc` to show first the challenges that start the closest to now.
- Changing the OA description to accept `null` direction has one minor negative side effect: The OA generator for Java will handles the creation of enums as follows: "if the specified value does not exist, return `null`". It would have been preferable to check if the value specified is in (`asc`, `desc`, `null`), …
> feat: Sort challenges by Closing soon, starting soon (backend)

- dev-env.sh
Fixes #1192
- Add a workspace command to quickly kill the process(es) listening to the port specified.
```console
workspace-kill-port
```
When a process is listening to the port specified:
```console
$ workspace-kill-port 12345
Killing the processes listening to the port 12345.
```
When a process is NOT listening to the port specified:
```console
$ workspace-kill-port 12345
There are no processes listening to the port 12345.
```
> feat: Add a workspace command to kill the process that listens to a port

- .devcontainer/devcontainer.json
- .vscode/extensions.json
> fix: Rename VS Code extension `vscode-boot-dev-pack`

- tools/devcontainers/sage/.devcontainer/Dockerfile
Fixes  #1283
- Add `vault` command to the dev container.
Print Vault version:
```console
$ vault --version
Vault v1.12.2 (415e1fe3118eebd5df6cb60d13defdc01aa17b03), built 2022-11-23T12:53:46Z
```
Set the following environment variables to interact with the OC vault server:
```console
export VAULT_ADDR='http://127.0.0.1:8200'
export VAULT_TOKEN=changeme
```
Add and read secrets:
```console
$ vault kv put secret/config-server plop.hello=world
====== Secret Path ======
secret/data/config-server
======= Metadata =======
Key                Value
---                -----
created_time       2023-02-05T01:27:10.263055161Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1
vscode@131d17258f7f:/workspaces/sage-monorepo$ vault kv get secret/config-server …
```
> feat: Add Vault CLI to the dev container

- .devcontainer/devcontainer.json
- Update the dev container image to benefit from the following updates:
- #1280
- #1284
> chore: Update dev container image to get access to `jq` and Vault CLI

- apps/openchallenges/config-server/build.gradle
- apps/openchallenges/config-server/src/main/resources/application.yml
- apps/openchallenges/organization-service/project.json
- apps/openchallenges/organization-service/src/main/resources/application.yml
Fixes #1278 
- Add basic authentication to the config server.
- Configure the org service to authenticate with the config server.
> feat: Add basic authentication to the config server

- libs/openchallenges/api-client-angular/src/lib/model/challengeSubmissionType.ts
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeSubmissionType.yaml
Follow up to #1298
- Add the value `notebook` to the API description source file.
- `nx build openchallenges-api-description`
- `nx openapi-generate openchallenges-challenge-service`
- `nx openapi-generate openchallenges-api-client-angular`
> fix: Add `notebook` enum value to api description source file

- apps/openchallenges/app/project.json
@vpchung There is actually no need for the app to build the image of its dependencies: running their task `serve-detach` is already taking care of building their image. So today's score is 1-0... 😊
> fix: App serve does not need to build images of dependencies

- .github/renovate.json
Renovate is rebasing PR that it has opens every time we push to `main`, which triggers notifications in my GH feed (= noise).
I plan to reactivate renovate once per quarter to update dependencies.
> chore: Disable renovate to remove deps update noise

- docker/openchallenges/services/api-gateway.yml
- docker/openchallenges/services/challenge-service.yml
- docker/openchallenges/services/config-server.yml
- docker/openchallenges/services/organization-service.yml
- docker/openchallenges/services/service-registry.yml
Fixes #1345 
- Remove the `command` property from the microservice Docker compose services.
> feat: Remove the docker compose command for microservice

- apps/openchallenges/image-service/.openapi-generator/FILES
- apps/openchallenges/image-service/requests.http
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/api/ImageApiDelegateImpl.java
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/model/dto/ImageDto.java
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/service/ImageService.java
- apps/openchallenges/image-service/src/main/resources/openapi.yaml
- docker/openchallenges/services/image-service.yml
- libs/openchallenges/api-description/build/image.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/Image.yaml
Closes #1414
- Implement the get image endpoint of the image service
Get the image with the key `triforce.png` (stored in the AWS S3 bucket):
```
GET {{basePath}}/images/triforce.png
HTTP/1.1 200 
{
"url": "http://localhost:8889/unsafe/triforce.png"
}
```
> feat: Implement method to get (unsafe) image url

- apps/openchallenges/image-service/build.gradle
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/service/ImageService.java
- libs/openchallenges/app-config-data/src/main/java/org/sagebionetworks/openchallenges/app/config/data/ImageServiceConfigData.java
Closes #1416 
- Add a Thumbor client to the image service project.
- Sign the URLs to images served by Thumbor.
- The Thumbor config parameter `SECURITY_KEY` must be set (here to `changeme`).
Get the image with the key `triforce.png`:
```
GET {{basePath}}/images/triforce.png
HTTP/1.1 200 
{
"url": "http://localhost:8889/ucBCtKeFXF3rPUsmUGmxcTRnoj0=/300x300/triforce.png"
}
```
Tampering with the URL will return a 400 error.
> feat: Sign the URL returned by the image service

- apps/openchallenges/challenge-service/config/application-local.yml
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/ChallengeServiceApplication.java
- apps/openchallenges/image-service/config/application-local.yml
- apps/openchallenges/organization-service/config/application-local.yml
- libs/openchallenges/app-config-data/src/main/java/org/sagebionetworks/openchallenges/app/config/data/ChallengeServiceConfigData.java
Closes #1383 
- Add the config data class and use it in the challenge service.
- The config of the challenge service is already living in the GH repo.
> feat:  Externalize the config of the challenge service

- apps/schematic/app/src/_app-theme.scss
I just noticed with the latest PR (#1428) that a test in the `schematic` app was failing due to a missing typography (which was removed with #1388).
This PR will fix that failed test.
> fix: remove undefined typography

- apps/openchallenges/challenge-service/build.gradle
- apps/openchallenges/grafana/.gitignore
- apps/openchallenges/grafana/README.md
- apps/openchallenges/grafana/docs/create-aws-resources.md
- apps/openchallenges/grafana/project.json
- apps/openchallenges/grafana/tools/backup-to-s3.sh
- apps/openchallenges/grafana/tools/create-api-key.sh
- apps/openchallenges/grafana/tools/grafana-backup-tool/.env.example
- apps/openchallenges/grafana/tools/restore-from-s3.sh
- apps/openchallenges/prometheus/config/prometheus.yml
- docker/openchallenges/services/prometheus.yml
Fixes #1344 
- Enable to save the Grafana data (organizations, users, dashboards) to AWS S3.
- Restore Grafana data from AWS S3.
- Add README to the openchallenges-grafana project.
- Enable Prometheus to collect data from the challenge service.
- Add micrometer dashboard (community dashboard)
- One limitation is that restoring data does not overwrite existing data. The solution is described in the README. It involves wiping the Grafana data clean and then restart Grafana container. An API key must then be regenerated and specified in the file `tools/grafana-backup-tool/.env` before being able to restore the data to get access to the latest version of the dashboard. This behavior is a bit cumbersome and I'm hoping that we can improve it in the future, e.g. by deleting specific resources …
> feat: Backup and restore Grafana data from/to S3

- docker/openchallenges/services/grafana.yml
- docker/openchallenges/services/vault.yml
Fixes #1429
@mdsage1 Here are tips to test this PR:
- Checkout the branch behind this PR. You can do that easily in VS Code from the GitHub extension, under the section "Waiting For My Review", then right-click on this PR and select the option to check it out.
- Remove all docker artifact with `workspace-docker-stop` and `docker system prune --volumes`.
- Starting Vault should be enough but I remember that you had this issue when starting the entire stack, so try again with `nx serve-detach openchallenges-app`.
If Vault container starts successfully, then this PR should have fixed the issue.
> fix: Increase Vault memory to 500M

- apps/openchallenges/image-service/README.md
- apps/openchallenges/thumbor/README.md
- docker/openchallenges/services/app.yml
- libs/openchallenges/about/src/lib/about.component.html
- libs/openchallenges/about/src/lib/about.component.ts
Fixes #1443
- Start the image service and Thumbor when the app is started with Docker Compose.
- Demonstrate how to consume an image from the image service in the OC app.
- Document how to configure and use the image service and its dependencies (Thumbor).
- We will continue to store asset images in SVG format on the GitHub repo for 1) the sake of version controlling them and 2) so that the asset images are displayed quickly when the app first load. But GH is not made to store bitmap files such as the logo of organization and banner of challenges. These images are also too large to be included in the app bundle. That's where the image service becomes handy.
- Maybe I shouldn't have "replaced" the app logo in the about page. The line for the original image is still in the code, I just …
> feat: Add image from the image service to the About page

- apps/openchallenges/challenge-service/.openapi-generator/FILES
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/api/ChallengeInputDataTypeApi.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/api/ChallengeInputDataTypeApiDelegate.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/api/ChallengeInputDataTypeApiDelegateImpl.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/configuration/EnumConverterConfiguration.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengeInputDataTypeDirectionDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengeInputDataTypeSearchQueryDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengeInputDataTypeSortDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengeInputDataTypeEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/service/ChallengeInputDataTypeService.java
- apps/openchallenges/challenge-service/src/main/resources/openapi.yaml
- libs/openchallenges/api-description/build/challenge.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/parameters/query/challengeInputDataTypeSearchQuery.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeInputDataTypeDirection.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeInputDataTypeSearchQuery.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeInputDataTypeSort.yaml
- libs/openchallenges/api-description/src/paths/challengeInputDataTypes.yaml
Fixes #1447
- Implement same search query API for challenge input data types as for challenges and organization.
- This PR updates the API description and the challenge service.
- This PR does not update any OC API client libraries.
List the challenge input data types:
```
GET {{basePath}}/challengeInputDataTypes
GET {{basePath}}/challengeInputDataTypes?sort=name # more specific
HTTP/1.1 200 
{
"number": 0,
"size": 100,
"totalElements": 4,
"challengeInputDataTypes": [
{
"id": 3,
"slug": "gene-expression",
"name": "gene expression",
"createdAt": "2023-04-03T23:44:58Z",
"updatedAt": "2023-04-03T23:44:58Z"
},
{
"id": 1,
"slug": "genomic",
"name": "genomic",
"createdAt": "2023-04-03T23:44:58Z",
"updatedAt": "2023-04-03T23:44:58Z"
},
{ …
```
> feat: Implement new search query API for challenge input data types 

- apps/openchallenges/challenge-service/.openapi-generator/FILES
- apps/openchallenges/challenge-service/requests.http
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/api/ChallengePlatformApi.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/api/ChallengePlatformApiDelegate.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/api/ChallengePlatformApiDelegateImpl.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/configuration/EnumConverterConfiguration.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengePlatformDirectionDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengePlatformSearchQueryDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengePlatformSortDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengePlatformEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/ChallengePlatformRepository.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/CustomChallengePlatformRepository.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/CustomChallengePlatformRepositoryImpl.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/service/ChallengePlatformService.java
- apps/openchallenges/challenge-service/src/main/resources/openapi.yaml
- libs/openchallenges/api-description/build/challenge.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/parameters/query/challengePlatformSearchQuery.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengePlatformDirection.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengePlatformSearchQuery.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengePlatformSort.yaml
- libs/openchallenges/api-description/src/paths/challengePlatforms.yaml
- libs/openchallenges/api-description/src/paths/challenges.yaml
Fixes #1445
- Add full-text search to challenge platforms
- This PR is expected to break UI features that relies on searching challenge platforms. This issue will be fixed when the new UI widget to search challenge platforms, challenge input data types, etc. will be merged to `main`.
List the challenges platforms for the search terms 'synapse'.
```
GET {{basePath}}/challengePlatforms?searchTerms=synapse
HTTP/1.1 200
{
"number": 0,
"size": 100,
"totalElements": 1,
"challengePlatforms": [
{
"id": 1,
"slug": "synapse",
"name": "Synapse",
"avatarUrl": "https://via.placeholder.com/300.png",
"websiteUrl": "https://synapse.org/",
"createdAt": "2023-04-25T22:38:29Z",
"updatedAt": "2023-04-25T22:38:29Z"
}
]
}
```
> feat: Implement new search query API for challenge platforms

- apps/openchallenges/challenge-service/requests.http
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengeInputDataTypeEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/ChallengeInputDataTypeRepository.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/CustomChallengeInputDataTypeRepository.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/CustomChallengeInputDataTypeRepositoryImpl.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/search/ChallengeInputDataTypeNameValueBridge.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/service/ChallengeInputDataTypeService.java
Fixes #1463
The content of this PR should have been included with #1451. I may have forgotten to push my last changes.
List the challenge input data types sorted by name.
```
GET {{basePath}}/challengeInputDataTypes?sort=name
HTTP/1.1 200
{
"number": 0,
"size": 100,
"totalElements": 4,
"challengeInputDataTypes": [
{
"id": 3,
"slug": "gene-expression",
"name": "gene expression",
"createdAt": "2023-04-29T15:43:21Z",
"updatedAt": "2023-04-29T15:43:21Z"
},
{
"id": 1,
"slug": "genomic",
"name": "genomic",
"createdAt": "2023-04-29T15:43:21Z",
"updatedAt": "2023-04-29T15:43:21Z"
},
{
"id": 4,
"slug": "metabolomic",
"name": "metabolomic",
"createdAt": "2023-04-29T15:43:21Z",
"updatedAt": "2023-04-29T15:43:21Z"
},
{
"id": 2,
"slug": …
```
> fix: Fix challenge input data type full-text search and sorters

- apps/openchallenges/challenge-service/requests.http
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengePlatformSortDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengePlatformEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/CustomChallengePlatformRepositoryImpl.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/search/ChallengePlatformNameValueBridge.java
- apps/openchallenges/challenge-service/src/main/resources/openapi.yaml
- libs/openchallenges/api-description/build/challenge.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengePlatformSort.yaml
Closes #1476 
- Sort challenge platforms by name (default when no search terms are provided)
- Sort challenge platforms by relevance (default when search terms are provided)
List the challenge platforms sorted by name.
```
GET {{basePath}}/challengePlatforms?sort=name
HTTP/1.1 200
{
"number": 0,
"size": 100,
"totalElements": 12,
"challengePlatforms": [
{
"id": 2,
"slug": "cagi",
"name": "CAGI",
"avatarUrl": "https://via.placeholder.com/300.png",
"websiteUrl": "https://genomeinterpretation.org/challenges.html",
"createdAt": "2023-04-29T21:43:23Z",
"updatedAt": "2023-04-29T21:43:23Z"
},
{
"id": 3,
"slug": "cami",
"name": "CAMI",
"avatarUrl": "https://via.placeholder.com/300.png",
"websiteUrl": "https://data.cami-challenge.org/", …
```
> feat: Add sorters by relevance and name for challenge platforms 

- .devcontainer/devcontainer.json
- package.json
- yarn.lock
Closes #1479 
- Update the devcontainer used by the monorepo (now includes Terraform CLI)
- Add Terraform CDK CLI (Node.js package)
```console
vscode@0fb43fed7afd:/workspaces/sage-monorepo$ terraform --help
Usage: terraform [global options] <subcommand> [args]
The available commands for execution are listed below.
The primary workflow commands are given first, followed by
less common or more advanced commands.
Main commands:
init          Prepare your working directory for other commands
validate      Check whether the configuration is valid
plan          Show changes required by the current configuration
apply         Create or update infrastructure
destroy       Destroy previously-created infrastructure
All other commands:
console       Try Terraform expressions at an interactive …
```
> feat: Update devcontainer with terraform and add Terraform CDK CLI

- .husky/pre-commit
- .vscode/settings.json
- apps/openchallenges/image-service/project.json
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/ImageServiceApplication.java
Closes #1488
- Update the task `serve` of the image service to disable formatting check.
- The motivation is to streamline development by removing the need to run manually the task `format`.
- Update the pre-commit hook to automatically format the files AND re-index the staged files after they have been formatted.
- Enable Format on Save for Java files.
- One limitation is that the environment is now using two different tools to format Java files:
- Spotless that powers the task `format`
- The VS Code extension "Language Support for Java" that is run when saving Java files.
- While Spotless is the tool used to valid the formatting of the Java files, the motivation for formatting files on save with Language Support for Java is to make the writing of Java code smoother. In the case where …
> feat: Format Java files on Save

- apps/openchallenges/organization-service/project.json
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/service/OrganizationService.java
Fixes #1501
- Build org avatar URL when getting a single org from the organization service 
- The org service can now be served with formatting errors in the code (development mode)
The org logo now appears on the org profile page.
> fix: Avatar is not displayed on organization profile

- apps/openchallenges/infra/README.md
- apps/openchallenges/infra/src/main.ts
Closes #1497 
- Create the TF Cloud organization `sagebionetworks`
- Configure the project `openchallenges-infra` to store the stack state to Terraform Cloud
- Document how to deploy the stack (see README)
> feat: Save Terraform stack state to Terraform Cloud

- libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.html
- libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.ts
Closes #1468
- Home page: fetch challenge and org counts from the backend
- Download the images that illustrate the counts at the size they are used
- The user count remains hardcoded as the user service will not be available for the preview.
> feat: Get challenge and org counts from the backend

- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/exception/BadRequestException.java
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/exception/ControllerAdvisor.java
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/exception/ErrorConstants.java
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/model/dto/ImageQueryDto.java
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/service/ImageService.java
- apps/openchallenges/image-service/src/main/resources/openapi.yaml
- libs/openchallenges/api-description/build/image.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/ImageKey.yaml
- libs/openchallenges/api-description/src/components/schemas/ImageQuery.yaml
Fixes #1552
- Validate the API property `ImageQuery.objectKey`
- We should validate the data at multiple level. One of them should be before and/or when we dump the data to the DB.
The image service now shows an error (actually a warning?) in the logs when an invalid object key is specified (validation code automatically generated).
```console
2023-05-16 02:44:50.747  WARN [openchallenges-image-service,fb5b88b51f1090a1,fb5b88b51f1090a1] 18985 --- [nio-8086-exec-8] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors<EOL>Field error in object 'imageQueryDto' on field 'objectKey': rejected value [logo/texas_biomed_2.png, tx_biomed1.png]; codes …
```
> fix: Validate image object key values

- apps/openchallenges/infra/src/ecs/ecs-service-client.ts
- apps/openchallenges/infra/src/ecs/ecs-service-upstream.ts
- apps/openchallenges/infra/src/ecs/ecs-task-definition-client.ts
- apps/openchallenges/infra/src/ecs/ecs-task-definition-gold.ts
- apps/openchallenges/infra/src/ecs/ecs-task-definition-silver.ts
- apps/openchallenges/infra/src/main.ts
Closes #1565 
- Deploy an ECS task for the client
- Deploy two ECS tasks for the gold and silver mock microservices
```console
vscode@2d058f0500d9:/workspaces/sage-monorepo/apps/openchallenges/infra$ cdktf deploy
...
openchallenges-stack  aws_instance.database_7CF902CB (database/database): Still creating... [2m0s elapsed]
openchallenges-stack  aws_instance.database_7CF902CB (database/database): Still creating... [2m10s elapsed]
openchallenges-stack  aws_instance.database_7CF902CB (database/database): Still creating... [2m20s elapsed]
openchallenges-stack  aws_instance.database_7CF902CB (database/database): Creation complete after 2m22s [id=i-0357ca67cfd1653a2]
openchallenges-stack  Apply complete! Resources: 52 added, 0 changed, 0 destroyed.
Outputs:
client_service_endpoint = …
```
> feat:  Deploy mock microservices with CDKTF and AWS Fargate

- apps/openchallenges/infra/src/ec2/single-stack-instance.ts
- apps/openchallenges/infra/src/main.ts
- apps/openchallenges/infra/src/resources/scripts/single-stack-instance.sh
- apps/openchallenges/infra/src/stack/openchallenges-preview-stack.ts
Closes #1578
- Add a second CDKTF stack to separate the long-term stack from the preview stack
Build the Terraform configuration files for all stacks:
```console
cdktf synth
```
Deploy the new stack:
```console
cdktf deploy openchallenges-preview
```
> feat: Create a second deployment stack withing openchallenges-infra

- tools/devcontainers/sage/.devcontainer/Dockerfile
Installing a Python environment may take more than 1 min (depends on compute resources and internet bandwidth). The time required to perform this action is larger than the time required to download a slightly larger devcontainer image that is preloaded with the environment. For this reason, the Sage devcontainer now accepts multiple Python environment to be included in its image (up to a limit). 
```console
$ time pyenv install 3.11.0
...
real    1m31.234s
```
> feat: Preload devcontainer with Python 3.11.0

- tools/devcontainers/sage/.devcontainer/Dockerfile
Installing a Python environment may take more than 1 min (depends on compute resources and internet bandwidth). The time required to perform this action is larger than the time required to download a slightly larger devcontainer image that is preloaded with the environment. For this reason, the Sage devcontainer now accepts multiple Python environment to be included in its image (up to a limit). 
```console
$ time pyenv install 3.11.0
...
real    1m31.234s
```
> feat: Add Python 3.11.0 to the devcontainer (take 2)

- apps/openchallenges/infra/src/ec2/database.ts
- apps/openchallenges/infra/src/ecs/ecs-task-definition-gold.ts
- apps/openchallenges/infra/src/ecs/ecs-task-definition-silver.ts
- apps/openchallenges/infra/src/openchallenges-preview-stack.ts
- apps/openchallenges/infra/src/openchallenges-stack.ts
- apps/openchallenges/infra/src/security-group/security-groups.ts
Closes #1586
- Set the VPC CIDR of the OC Preview stack to `10.70.0.0/32` as suggested by @jesusaurus 
- The project `openchallenges-infra` modified here is still a very early prototype. DRY TODOs will be addressed in future PRs.
```console
$ cdktf deploy openchallenges-preview
...
Changes to Outputs:
+ bastion_private_ip          = "10.70.2.172"
+ bastion_public_ip           = (known after apply)
+ preview_instance_private_ip = (known after apply)
+ preview_instance_public_ip  = (known after apply)
+ private_subnet_0_cidr_block = "10.70.32.0/20"
+ private_subnet_1_cidr_block = "10.70.48.0/20"
+ public_subnet_0_cidr_block  = "10.70.0.0/20"
+ public_subnet_1_cidr_block  = "10.70.16.0/20"
...
```
> chore: Set OpenChallenges VPC CIDR to 10.70.0.0/16

- apps/openchallenges/infra/README.md
- apps/openchallenges/infra/src/resources/scripts/bastion.sh
- apps/openchallenges/infra/src/resources/scripts/preview-instance.sh
Closes #1567
- Install the Docker engine on the preview instance
Docker is now available on the preview instance.
```console
ubuntu@openchallenges-preview-instance:~$ docker --version
Docker version 24.0.1, build 6802122
$ docker compose
Usage:  docker compose [OPTIONS] COMMAND
Define and run multi-container applications with Docker.
Options:
--ansi string                Control when to print ANSI control characters ("never"|"always"|"auto") (default
"auto")
--compatibility              Run compose in backward compatibility mode
--dry-run                    Execute command in dry run mode
--env-file stringArray       Specify an alternate environment file.
-f, --file stringArray           Compose configuration files
--parallel int               Control max parallelism, -1 for unlimited …
```
> feat: Deploy an EC2 instance with CDKTF that has Docker installed

- apps/openchallenges/infra/README.md
- apps/openchallenges/infra/src/bastion/bastion-instance-profile.ts
- apps/openchallenges/infra/src/bastion/bastion.ts
- apps/openchallenges/infra/src/openchallenges-preview-stack.ts
- tools/devcontainers/sage/.devcontainer/Dockerfile
Closes #1591
- Add an IAM instance profile to the Bastion
- Document how to connect to the Bastion with SSM
- Add the AWS Session Manager plugin to the devcontainer
The ID of the bastion is now shown after its deployment. This ID will be used to access the bastion with SSM.
```console
openchallenges-preview
bastion_id = i-05b07d2ace58137e8
```
Connect to the bastion with SSM:
```console
vscode@eee29c9f9d7c:/workspaces/sage-monorepo$ ssh oc-bastion
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.19.0-1024-aws x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
System information as of Sat May 27 00:08:00 UTC 2023
System load:           0.060546875
Usage of /:            23.1% of 7.57GB
Memory usage: …
```
> feat: Connect to the bastion with AWS SSM

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- apps/openchallenges/infra/README.md
- apps/openchallenges/infra/src/bastion/bastion-config-data.ts
- apps/openchallenges/infra/src/bastion/bastion-config.ts
- apps/openchallenges/infra/src/bastion/bastion.ts
- apps/openchallenges/infra/src/openchallenges-preview-stack.ts
- apps/openchallenges/infra/src/resources/scripts/bastion.sh
Closes #1566
- Update the devcontainer to [b5ec4f9](https://hub.docker.com/layers/sagebionetworks/sage-devcontainer/b5ec4f9/images/sha256-33c388fdd169c4db1cbe9985e0e080b59a4bdf06bafb2db82238ff9559517e1c?context=repo)
Use the variable in the user data script:
```console
echo export HELLO=${var.hello} >> /etc/environment
```
Deploy the plan with:
```console
TF_VAR_hello='Hello' cdktf deploy openchallenges-preview
```
- The variable value does not appear in the plan (safer)
- A drawback of using `${var.my_variable}` in a user data script is that it's not clear that this script requires this variable.
The script must be defined as a TerraformAsset, otherwise `Fn.templatefile` won't find the file at the path specified.
```typescript
const instanceScript = new TerraformAsset(this, …
```
> feat: Set environment variables to an EC2 deployed with CDKTF

- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/model/dto/ImageHeightDto.java
- apps/openchallenges/image-service/src/main/java/org/sagebionetworks/openchallenges/image/service/service/ImageService.java
- apps/openchallenges/image-service/src/main/resources/openapi.yaml
- libs/openchallenges/api-client-angular/src/lib/model/imageHeight.ts
- libs/openchallenges/api-description/build/image.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/ImageHeight.yaml
Closes #1636
- Update the image service to offer images with their height set to 32 px
> **Note** This development recipe was applied to create this PR. Time: 15 min.
1. Update the API description
- Update the model in `libs/openchallenges/api-description/src`
- Build the API description: `nx build openchallenges-api-description`
2. Update the service (here the image service)
- Run OpenAPI Generator: `nx openapi-generate openchallenges-image-service`
- Update the business logic (if needed)
3. Update the API clients
- For Angular: `nx openapi-generate openchallenges-api-client-angular`
4. Update the web app
Build the images and start the image service and its dependencies, which include Thumbor:
``` console
nx serve-detach openchallenges-image-service
``` …
> feat: Enable the image service to return images with height 32 px

- apps/openchallenges/api-gateway/config/application-local.yml
- apps/openchallenges/thumbor/.env.example
- apps/openchallenges/thumbor/.env.example.aws
- apps/openchallenges/thumbor/README.md
- docker/openchallenges/services/thumbor.yml
Closes #1632
- Set Thumbor to listen to port 8889 inside its container (previously 8888).
- Overwrites the API gateway config so that it sends requests to Thumbor on port 8889 (dev server only).
- 📣 This PR requires developer to add manually the variable `PORT=8889` to the `.env` file of the Thumbor project.
- 📣 This PR requires a change to the remote config of the API gateway stored in another GH repo. This change will break the API gateway container of other feature branches. These feature branches will need to be updated from `main` after this PR has been merged.
Thumbor can be reached when deployed with its container and after changing the port mapping.
> feat: Thumbor dev server and container should listen to the same port

- libs/openchallenges/styles/src/lib/_constants.scss
- libs/openchallenges/styles/src/lib/_general.scss
- libs/openchallenges/ui/src/lib/navbar/navbar.component.scss
Fixes #1652 
* keep navbar on top of viewport.  This will allow users to easily go to a different search page after they've done some scrolling
**No scrolling done yet**
**After some scrolling**
> feat(ui): sticky navbar

- docker/openchallenges/services/thumbor.yml
Closes  #1655
- We observed that Thumbor gets close to 90% of its current max memory, which is why this PR increases this amount.
> feat: Increase Thumbor container memory to 500M

- libs/openchallenges/styles/src/lib/_general.scss
* specify `body` height to be _at most_ 100vh
**Before** - Gap seen at the bottom:
**After** - No gap:
> fix(ui): small UI fix

- libs/openchallenges/api-description/build/challenge.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/build/organization.openapi.yaml
- libs/openchallenges/api-description/src/challenge.openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeContribution.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeContributionRole.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeContributionsPage.yaml
- libs/openchallenges/api-description/src/components/schemas/OrganizationSearchQuery.yaml
- libs/openchallenges/api-description/src/paths/challenges/@{challengeId}/contributions.yaml
Related to #1537
This PR updates the OC API description to enable users to access contributions made to a challenge. The implementation of this change to the API description will be made in other PRs that target the upstream branch `challenge-contributions`.
- Add the path `/challenges/{challengeId}/contributions`
- Rename the org search query param `ChallengeContributorRole` to `ChallengeContributionRole`
- I've been thinking about whether we should name the object `contribution` or `contributor`. The reason I prefer the former is that we could add more information about the contribution that are not directly about the contributor such as a start and end date for the contribution.
- A source of inspiration could be [CD2H contribution data …
> feat: Add path to get the contributions to a challenge

- tools/switch-devcontainer-to-docker-outside-of-docker.sh
Closes #1675
The OpenChallenges team has always been using the Sage Monorepo dev container with VS Code (GUI). This PR illustrates how a dev container can be managed with a CLI and used to run a process *inside* the dev container from the host (i.e. outside of the dev container).
This PR demonstrates how to use this approach to build the Docker images for all the components of the OC stack so that these images are then available on the host. The dev container feature "docker-outside-of-docker" is used to share the Docker engine of the host with the dev container (while the feature "docker-in-docker" isolates the host and dev container Docker engines), so that the images build image the dev container are available to the host too. In an upcoming PR, the OC stack will be started on the host …
> feat: Build OC images from outside the dev container

- tools/switch-devcontainer-to-docker-outside-of-docker.sh
The script added in #1676 is meant to be run outside of the dev container and where the variable `$WORKSPACE_DIR` is not defined.
> fix: Update docker-outside-of-docker script

- apps/openchallenges/infra/README.md
- apps/openchallenges/infra/src/preview-instance-alb/preview-instance-alb.ts
- apps/openchallenges/infra/src/security-group/security-groups.ts
Closes #1678
- Configure the preview instance to listen to the port 8000
- Configure the ALB to forward traffic to the port 8000 of the preview instance
- Document in the `openchallenges-infra` README how to configure and start the stack
> feat: Configure the OC stack during deployment

- tools/devcontainers/sage/.devcontainer/Dockerfile
- tools/devcontainers/sage/.devcontainer/devcontainer.json
Closes #1620
This PR adds R with a pinned version to the monorepo dev container image. R will then be available to all the developers of the monorepo once it's part of the official dev container, which will be built and published to Docker Hub by a CI/CD workflow when this PR is merged.
- Add R version 4.2.3 to the dev container image
- Remove comments and unused properties from `tools/devcontainers/sage/.devcontainer/devcontainer.json`
> **Note** I used the steps below to build the dev container image locally and check that R is properly added to the dev container image. As any contribution made to this monorepo, this work was done inside the monorepo dev container (#inception). :-)
Build the test dev container image (`sagebionetworks/sage-devcontainer:test`):
```console
cd …
```
> feat: Add R to the monorepo devcontainer

- libs/openchallenges/ui/src/lib/paginator/paginator.component.html
- libs/openchallenges/ui/src/lib/paginator/paginator.component.ts
- fixes #1702 
The issue was the `[first]` input of `p-paginator` should use "first" (index of the first item in the new page), instead of "pageNumber" (index of the new page). To fix the bug, manually calculating the "first" using  "pageNumber" and "pageSize".
As a reminder for future, the proporties of paginator states from `onPageChange` are listed below:
```ts
paginate(event) {
event.first = Index of the first record -> itemIndex
event.rows = Number of rows to display in new page -> pageSize
event.page = Index of the new page -> pageNumber
event.pageCount = Total number of pages
}
```
---
https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/f17f38ad-7f7a-49c7-a382-01ef469e3e9e
> feat(fix): Make paginator highlight the correct selection

- libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
- libs/openchallenges/org-search/src/lib/org-search-filters-values.ts
- libs/openchallenges/org-search/src/lib/org-search-filters.ts
- libs/openchallenges/org-search/src/lib/org-search.component.html
- libs/openchallenges/org-search/src/lib/org-search.component.ts
- resolves #1705 
---
https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/cd669d55-1236-4b7c-8913-f19e6a5dc125
- The pagination and sort filters are also captured (not showing in the recording above)
https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/3ca20289-ebe8-43ea-a84f-9895d844b92b
> feat(angular):  Capture the active search parameters for Organization Search page

- apps/openchallenges/infra/README.md
- apps/openchallenges/infra/src/resources/scripts/preview-instance.sh
The OC images are first built when the EC2 instance is deployed. This PR describes how to manually rebuild the images after checking out a new version of the code base.
> docs: Document how to build OC images manually on Preview Instance EC2

- libs/openchallenges/challenge/src/lib/challenge.component.html
- libs/openchallenges/org-profile/src/lib/org-profile.component.html
- fixes #1687 
Move `ngIf="organization$` to an extra inner `ng-container` to preserve the content space. The footer will always be at the bottom, even if the data is empty initially (due to delays).
>**Note**: 
> If the data is undefined after the requests are complete, the page will still be redirected to "Not Found" page. Although I haven't tested since I still have troubles loading images, I expect no flashes of height difference.
```html
<main class="base mat-typography" *ngIf="organization$ | async as org">
...
<main>
<main class="base mat-typography">
<ng-container *ngIf="organization$ | async as org">
...
</ng-container>
<main>
```
The changes above are only applied to Challenge Profile and Org Profile pages.
> feat(ui): Preserve the content space to make footer sticky at the bottom

- .devcontainer/devcontainer.json
Closes #1700
- It looks like only GitHub Codespace offers this feature. I tried VS Code settings `"workbench.startupEditor": "readme"` but couldn't manage to get it to display the README when opening the folder. I'm also worried that using this option would open the README instead of the last files opened. I also have this concern for GH Codespace, but that's less critical since I don't see us developing on Codespace actively, but instead showing the README would be a plus in Codespace for demo. 
- The change made by this PR can be revert anytime if needed.
- VS Code: https://code.visualstudio.com/docs/getstarted/settings#_settingsjson
- Codespace: [Automatically opening files in the codespaces for a repository](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/c …
> docs: Show Sage Monorepo README when new dev container starts

- .devcontainer/devcontainer.json
Closes #1727
- Update `docker-in-docker` to v2.2.0
- Update Docker to v20.10.24
- It looks like the latest version of `docker-in-docker` (v2.2.0) can not install versions of Docker above 20.10.x.
- I opened a ticket in the feature repo: https://github.com/devcontainers/features/issues/607
> chore: Update `docker-in-docker`

- tools/devcontainers/sage/.devcontainer/Dockerfile
Closes #1732
```console
vscode@c479c8cffdf7:/$ trivy --version
Version: 0.43.1
vscode@c479c8cffdf7:/$ trivy --help
Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues and hard-coded secrets
Usage:
trivy [global flags] command [flags] target
trivy [command]
Examples:
$ trivy image python:3.4-alpine
$ trivy image --input ruby-3.1.tar
$ trivy fs .
$ trivy server
Scanning Commands
aws         [EXPERIMENTAL] Scan AWS account
config      Scan config files for misconfigurations
filesystem  Scan local filesystem
image       Scan a container image
kubernetes  [EXPERIMENTAL] Scan kubernetes cluster
repository  Scan a remote repository
rootfs      Scan rootfs
sbom        Scan SBOM for vulnerabilities
vm          [EXPERIMENTAL] Scan …
```
> chore: Add Trivy to the dev container image

- apps/openchallenges/zipkin/project.json
Closes #1730
Scan the Docker image of a project with Trivy:
```console
nx build-image <project>
nx scan-image <project>
```
- https://github.com/nrwl/nx/issues/8051
- Updating Nx may help (future ticket)
- Add the task `scan-image` to the project `openchallenges-zipkin`
```console
vscode@3d8deaace953:/workspaces/sage-monorepo$ nx scan-image openchallenges-zipkin
> nx run openchallenges-zipkin:scan-image
sagebionetworks/openchallenges-zipkin:latest (alpine 3.16.3)
============================================================
Total: 26 (UNKNOWN: 0, LOW: 0, MEDIUM: 8, HIGH: 18, CRITICAL: 0)
┌────────────┬───────────────┬──────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability │ Severity │ Installed Version │ …
```
> feat: Explore Trivy to scan docker images

- .github/workflows/ci.yml
- apps/openchallenges/apex/project.json
- apps/openchallenges/api-gateway/project.json
- apps/openchallenges/app/project.json
- apps/openchallenges/challenge-service/project.json
- apps/openchallenges/config-server/project.json
- apps/openchallenges/elasticsearch/project.json
- apps/openchallenges/grafana/project.json
- apps/openchallenges/image-service/project.json
- apps/openchallenges/mariadb/project.json
- apps/openchallenges/mysqld-exporter/project.json
- apps/openchallenges/organization-service/project.json
- apps/openchallenges/prometheus/project.json
- apps/openchallenges/rstudio/project.json
- apps/openchallenges/service-registry/project.json
- apps/openchallenges/thumbor/project.json
- apps/openchallenges/vault/project.json
- apps/openchallenges/zipkin/project.json
Closes #1708
- Update all the OpenChallenges projects that can be deployed with `docker/openchallenges/serve-detach.sh` to build, scan and publish their images to GHCR, except a few images (see Nx option `--exclude`).
- Temporarily build, scan and publish all OC images, which will be reverted to `affected` once all the images have been published once.
- The GH runner has 84 GB of storage, which is not enough to build all the OC images. I bumped into this issue here because I use `run-many` but ultimately building the images only for the `affected` projects will make things work. For now I work around this issue with `run-many` using the option `--exclude=A,B`.
> chore: Push OpenChallenges images to GHCR

- .github/workflows/ci.yml
Disable image scans because this step fails due to `no space left` error on the GH runner.
> chore: Disable image scans

- .github/workflows/ci.yml
- apps/schematic/api-docs/project.json
- apps/schematic/api/project.json
- apps/synapse/rstudio/project.json
- dev-env.sh
- docker/openchallenges/services/apex.yml
- docker/openchallenges/services/api-gateway.yml
- docker/openchallenges/services/app.yml
- docker/openchallenges/services/challenge-service.yml
- docker/openchallenges/services/config-server.yml
- docker/openchallenges/services/elasticsearch.yml
- docker/openchallenges/services/grafana.yml
- docker/openchallenges/services/image-service.yml
- docker/openchallenges/services/mariadb.yml
- docker/openchallenges/services/minio.yml
- docker/openchallenges/services/mysqld-exporter.yml
- docker/openchallenges/services/organization-service.yml
- docker/openchallenges/services/prometheus.yml
- docker/openchallenges/services/rstudio.yml
- docker/openchallenges/services/service-registry.yml
- docker/openchallenges/services/thumbor.yml
- docker/openchallenges/services/vault.yml
- docker/openchallenges/services/zipkin.yml
- docker/schematic/services/api.yml
- docker/synapse/services/rstudio.yml
Closes #1745
- Rename all the images generated by this monorepo so that they use the GHCR names
- Add the command `synapse-build-images`
- Disable image push, scan and publish in the CI workflow (to be fixed in another PR)
```console
```
```console
schematic-build-images
nx serve-detach schematic-api
```
```console
synapse-build-images
nx serve-detach synapse-rstudio
```
> fix: Restore nx serve-detach

- .github/workflows/ci.yml
- apps/openchallenges/apex/project.json
- apps/openchallenges/api-gateway/project.json
- apps/openchallenges/app/project.json
- apps/openchallenges/challenge-service/project.json
- apps/openchallenges/config-server/project.json
- apps/openchallenges/elasticsearch/project.json
- apps/openchallenges/grafana/project.json
- apps/openchallenges/image-service/project.json
- apps/openchallenges/mariadb/project.json
- apps/openchallenges/mysqld-exporter/project.json
- apps/openchallenges/organization-service/project.json
- apps/openchallenges/prometheus/project.json
- apps/openchallenges/rstudio/project.json
- apps/openchallenges/service-registry/project.json
- apps/openchallenges/thumbor/project.json
- apps/openchallenges/vault/project.json
- apps/openchallenges/zipkin/project.json
- apps/schematic/api/project.json
- apps/synapse/rstudio/project.json
Closes #1744
- Create the task `publish-and-remove-image`
- Update CI to run the task `publish-and-remove-image` for all project one at a time
- The step `publish-and-remove-image` is applied to one project at a time so that the removal of images does not affect concurrent tasks.
- Ultimately the CI step `publish-and-remove-image` will be performed only for affected projects.
> chore: Publish images without rebuilding them in the CI workflow

- .github/workflows/ci.yml
Closes #1748
- Remove QEMU as we don't need to build image for multiple plaftorms
- Use GH Action from the marketplace to setup buildx
- Configure buildx to use the driver `docker` instead of `docker-container` (default)
- Using the driver `docker` enables to build images that depends on local images (e.g. the `-base:local` images). However, we loose the ability to cache Docker layers in the CI workflow, which makes the workflow slower.
- If we want to continue to benefit from caching layers, two solutions would be to:
- Push the base images to the GHCR registry
- Use a local registry to store the `-base` images (see comment in #1748)
- https://github.com/docker/setup-buildx-action#inputs
- https://docs.docker.com/engine/reference/commandline/buildx_create/#driver
> fix: Remove QEMU and setup buildx to use the docker driver

- .github/workflows/ci.yml
- apps/openchallenges/apex/project.json
- apps/openchallenges/api-gateway/project.json
- apps/openchallenges/app/project.json
- apps/openchallenges/challenge-service/project.json
- apps/openchallenges/config-server/project.json
- apps/openchallenges/elasticsearch/project.json
- apps/openchallenges/grafana/project.json
- apps/openchallenges/image-service/project.json
- apps/openchallenges/mariadb/project.json
- apps/openchallenges/mysqld-exporter/project.json
- apps/openchallenges/organization-service/project.json
- apps/openchallenges/prometheus/project.json
- apps/openchallenges/rstudio/project.json
- apps/openchallenges/service-registry/project.json
- apps/openchallenges/thumbor/project.json
- apps/openchallenges/vault/project.json
- apps/openchallenges/zipkin/project.json
- apps/schematic/api/project.json
- apps/synapse/rstudio/project.json
Closes #1748
- Make the task `publish-image` depend on `build-image`.
- Another solution would have to make the `publish-image` task depends on `build-image-base` only for projects that have a base image (e.g. `openchallenges-api-gateway`). Instead, I prefer to make all the task `publish-image` depend on `build-image` to have a more general solution. Thanks to image caching, the task `publish-image` is fast because the image has already been built by the task `build-image`.
Save your personal access token (classic). We recommend saving your token as an environment variable.
```console
export CR_PAT=YOUR_TOKEN
```
Using the CLI for your container type, sign in to the Container registry service at `ghcr.io`.
```console
$ echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
> …
```
> fix: Fix images that depend on a base image

- docker/openchallenges/services/apex.yml
- docker/openchallenges/services/api-gateway.yml
- docker/openchallenges/services/app.yml
- docker/openchallenges/services/challenge-service.yml
- docker/openchallenges/services/config-server.yml
- docker/openchallenges/services/elasticsearch.yml
- docker/openchallenges/services/grafana.yml
- docker/openchallenges/services/image-service.yml
- docker/openchallenges/services/mariadb.yml
- docker/openchallenges/services/minio.yml
- docker/openchallenges/services/mysqld-exporter.yml
- docker/openchallenges/services/organization-service.yml
- docker/openchallenges/services/prometheus.yml
- docker/openchallenges/services/rstudio.yml
- docker/openchallenges/services/service-registry.yml
- docker/openchallenges/services/thumbor.yml
- docker/openchallenges/services/vault.yml
- docker/openchallenges/services/zipkin.yml
- docker/schematic/services/api.yml
- docker/synapse/services/rstudio.yml
Closes #1756
See #1756 for a description of this feature.
- Enable to specify the version of the stack to deploy
This step is required to pull and deploy the images with the tag `edge` (see below).
See [instructions](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).
> **Note**: The visibility of the images may be set to public in the future to enable anonymous download.
Build and deploy the `local` version:
> **Note** This is the same command that we have used until now (improved DX).
```console
```
Deploy the `edge` version:
```console
OPENCHALLENGES_VERSION=edge nx serve-detach openchallenges-apex
```
Deploy the `local` version:
```console …
```
> feat: Enable to specify the version of a stack to deploy

- apps/openchallenges/api-gateway/src/main/resources/application.yml
- apps/openchallenges/challenge-service/src/main/resources/application.yml
- apps/openchallenges/challenge-to-elasticsearch-service/src/main/resources/application.yml
- apps/openchallenges/config-server/.env.example
- apps/openchallenges/config-server/README.md
- apps/openchallenges/config-server/src/main/resources/application.yml
- apps/openchallenges/image-service/src/main/resources/application.yml
- apps/openchallenges/kaggle-to-kafka-service/src/main/resources/application.yml
- apps/openchallenges/organization-service/src/main/resources/application.yml
- apps/openchallenges/service-registry/src/main/resources/application.yml
Closes #1760
- Configure the config server to access the private git repository with an SSH key instead of user credentials
- Rename the service profile name `development` to `dev`
Click on the image to learn everything there is to know about this PR (XP Sharing video series).
[![IMAGE ALT TEXT](http://img.youtube.com/vi/cHPcwdAdDzc/0.jpg)](http://www.youtube.com/watch?v=cHPcwdAdDzc "Video Title")
> **Note** Please share your feedback about this video in this thread or in DM (video content, format, etc.).
This is what the `.env` of the OpenChallenges config server looks like (see `.env.example`):
```
GIT_DEFAULT_LABEL=test-2
GIT_HOST_KEY_ALGORITHM=ssh-ed25519
GIT_HOST_KEY=AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
GIT_PRIVATE_KEY="-----BEGIN OPENSSH PRIVATE …
```
> feat: Configure the OC config server to access the git repo with SSH

- .github/workflows/scan-images.yml
Closes #1759
- Add GitHub workflow that scan the edge images published by Sage Monorepo with Trivy
- https://github.com/fluent/fluent-bit/blob/master/.github/workflows/cron-trivy.yaml
> feat: Scan edge images with Trivy

- apps/openchallenges/apex/.env.example
- apps/openchallenges/apex/templates/http.conf.template
- apps/openchallenges/api-docs/Dockerfile
- docker/openchallenges/services/apex.yml
Closes #1780
- Add `HEALTHCHECK` to the image of `openchallenges-api-docs`
- Start the API docs container when starting the OC apex container
- Configure the OC apex to redirect traffic to `/api-docs` to the API docs container
Starting the OC stack now serves the API docs on `localhost:8000/api-docs`.
```console
workspace-docker-stop
docker system prune --force
```
> feat: Configure the OC Apex to target the API docs

- apps/openchallenges/apex/Dockerfile
Closes #1822
- Update `openchallenges-apex` base image
> fix: Fix `CVE-2023-35945` in OC apex

- .devcontainer/devcontainer.json
Closes #1806
- Update the active devcontainer
- This is the first time the image of the active devcontainer comes from GHCR
> chore: Update the active devcontainer to `1859079`

- apps/openchallenges/organization-service/requests.http
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/api/OrganizationApi.java
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/api/OrganizationApiDelegate.java
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/api/OrganizationApiDelegateImpl.java
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/configuration/SpringDocConfiguration.java
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/model/repository/OrganizationRepository.java
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/service/OrganizationService.java
- apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
- apps/openchallenges/organization-service/src/main/resources/openapi.yaml
- libs/openchallenges/api-client-angular/src/lib/api/organization.service.ts
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/build/organization.openapi.yaml
- libs/openchallenges/api-description/openapi-merge.yaml
- libs/openchallenges/api-description/src/components/parameters/path/org.yaml
- libs/openchallenges/api-description/src/components/schemas/OrgId.yaml
Closes #1722
- Update endpoint to access `id` value in addition to `login` values
- Requires org logins to start with a-z
- Update the OC API client for Angular
- The motivation for requiring org logins to start with a-z is so that there is never an org login that may be an org ID too, which would otherwise lead to ambiguity when retrieving the organization.
```
GET {{basePath}}/organizations/dream
HTTP/1.1 200
{
"id": 1,
"name": "DREAM",
"email": "dream@sagebionetworks.org",
"login": "dream",
"description": "Together, we share a vision to enable individuals and groups to collaborate openly so that the “wisdom of the crowd” provides the greatest impact on science and human health.",
"avatarKey": "logo/dream.png",
"websiteUrl": "https://dreamchallenges.org/",
"challengeCount": 47, …
```
> feat: Get org by `id` or `login`

- .devcontainer/devcontainer.json
- apps/schematic/api/prepare-python.sh
- dev-env.sh
- Update the devcontainer to version `55645b0`
- Update the `prepare-python.sh` of the project `schematic-api` to re-initialize `pyenv` after installing new Python env
- The new devcontainer image was built by #1844
- This PR fixes an issue encountered when running the task `prepare-python` for the project `schematic-api` in a GitHub workflow. This error could not be reproduced locally. The difference between the task `prepare-python` of `schematic-api` compared to the other Python projects is that `schematic-api` is using a version of Python not pre-installed by the devcontainer. This is actually a feature of Sage Monorepo to give developers the flexibility to use any Python version for their project. Yet, making projects use pre-installed Python versions contributes to speed up the …
> chore: Update devcontainer to `55645b0` (now Ubuntu 22.04)

- libs/openchallenges/challenge/src/lib/challenge-overview/challenge-overview.component.html
- libs/openchallenges/home/src/lib/challenge-registration/challenge-registration.component.html
- libs/openchallenges/org-profile/src/lib/org-profile-overview/org-profile-overview.component.html
Fixes #1855 
* replace link on home page to the "Add New Challenge" google form
* add pre-filled link to the profile page footer for challenges and organizations
Profile page update:
> fix(ui): add links to Google Forms

- dev-env.sh
Closes #1899
This solution seamlessly solves the issue described in #1899 for developers.
- The code added via this PR had been previously removed during the upgrade of the dev container to Ubuntu. At the time the command was throwing an error for me. I'm now in the Ubuntu dev container and I can run this command fine.
> fix: Set `vm.max_map_count` when starting a new terminal

- .github/workflows/ci.yml
Temporary fix to the out of storage space issue encountered by the CI workflow when building the Docker images of the affected projects.
> fix: Build selected image instead of all affected projects

- libs/openchallenges/about/src/lib/about.component.scss
- libs/openchallenges/ui/src/lib/organization-card/_organization-card-theme.scss
Fixes #1830 
* remove drop shadow surrounding avatar on organization card
* remove drop shadow from goal card
> **Note**: the drop shadows will remain on the profile pages, e.g.
> ![Screenshot 2023-08-02 at 1 55 37 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/5f060d36-0ac0-47f5-b12e-d658b9f66a3c)
**Organization cards**
**Goal cards**
**Organization cards (blue border)**
**Organization cards (black border)**
**Goal cards (border)**
> fix(ui): remove drop shadows from select cards

- apps/openchallenges/app/src/app/app-sections.ts
Closes #1864
Remove the About button from the navbar to simplify the flow. Visitor will now land on the page and not hesitate between reading the home page and clicking on About (another "issue" was that About was listed first in the navbar).
The About page is still accessible from a link in the footer.
> fix: Remove the About button from the navbar

- apps/openchallenges/app/.env.example
- apps/openchallenges/app/src/config/config.json
- apps/openchallenges/app/src/config/config.json.template
- libs/openchallenges/about/src/lib/about.component.html
- libs/openchallenges/about/src/lib/about.component.ts
- libs/openchallenges/challenge-search/src/lib/challenge-search.component.html
- libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
- libs/openchallenges/challenge/src/lib/challenge.component.html
- libs/openchallenges/challenge/src/lib/challenge.component.ts
- libs/openchallenges/config/src/lib/app.config.ts
- libs/openchallenges/config/src/lib/mock-app.config.ts
- libs/openchallenges/home/src/lib/home.component.html
- libs/openchallenges/home/src/lib/home.component.ts
- libs/openchallenges/login/src/lib/login.component.ts
- libs/openchallenges/not-found/src/lib/not-found.component.html
- libs/openchallenges/not-found/src/lib/not-found.component.ts
- libs/openchallenges/org-profile/src/lib/org-profile.component.html
- libs/openchallenges/org-profile/src/lib/org-profile.component.ts
- libs/openchallenges/org-search/src/lib/org-search.component.html
- libs/openchallenges/org-search/src/lib/org-search.component.ts
- libs/openchallenges/signup/src/lib/signup.component.ts
- libs/openchallenges/team/src/lib/team.component.html
- libs/openchallenges/team/src/lib/team.component.ts
- libs/openchallenges/ui/src/lib/footer/footer.component.html
- libs/openchallenges/ui/src/lib/footer/footer.component.ts
- libs/openchallenges/user-profile/src/lib/user-profile.component.html
- libs/openchallenges/user-profile/src/lib/user-profile.component.ts
Closes #1794
Add the property `Data updated on` to the OC footer.
- This PR adds the property `DATA_UPDATED_ON` to the `.env` of the project `openchallenges-app` (see `.env.example` updated by this PR)
> feat: Specify the data version in the OC footer

- libs/openchallenges/org-profile/src/lib/org-profile-challenges/org-profile-challenges.component.html
- libs/openchallenges/styles/src/lib/_general.scss
- libs/openchallenges/ui/src/lib/organization-card/organization-card.component.scss
- libs/openchallenges/ui/src/lib/organization-card/organization-card.component.spec.ts
- libs/openchallenges/ui/src/lib/organization-card/organization-card.component.ts
- libs/openchallenges/user-profile/src/lib/user-profile-challenges/user-profile-challenges.component.html
- closes #1917 
- Scale up org card a bit to make its width consistent with challenge card's
- search bar is not removed - here just for demoing the width between two types of cards
- star button is removed from the latest version in `main`
> feat(ui): Make width of challenge and org cards consistent

- libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
- libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.ts
- libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.ts
- libs/openchallenges/org-profile/src/lib/org-profile.component.ts
- libs/openchallenges/org-search/src/lib/org-search.component.ts
- fixes #1659 
When the image url is not successfully retrieved from image service, the organization card is not loaded at all. To avoid this behavior, this pr is to return default empty string as avatarUrl if the image service is failed.
> fix: Use default avatar if image service is down

- libs/openchallenges/challenge/src/lib/_challenge-theme.scss
- libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.html
- libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.ts
- libs/openchallenges/challenge/src/lib/challenge-organizers/challenge-organizers.component.html
- Add default 'Not available' when there are no content in profile tabs
> feat(ui): Add default text when array is empty in profile tabs

- apps/openchallenges/infra/src/cnb-dev-stack.ts
- apps/openchallenges/infra/src/dns/cnb-dev-dns.ts
Contributes to #1898
- Add a ACM certificate to the stack `cnb-dev` for all OC DNS names
- Once applied (`cdktf deploy cnb-dev`), the existing certificate for `dev.openchallenges.io` will be removed according to the diff output shown below.
Output of `cdktf diff cnb-dev`
```console
cnb-dev  Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+/- create replacement and then destroy
Terraform will perform the following actions:
cnb-dev    # aws_acm_certificate.dns_openchallenges_cert_42540034 (dns/openchallenges_cert) must be replaced
+/- resource "aws_acm_certificate" "dns_openchallenges_cert_42540034" {
~ arn                       = "arn:aws:acm:us-east-1:384625883722:certificate/b1c70716-8f19-4d06-9737- …
```
> feat: Add ACM certificate for OC prod DNS

- .github/CODEOWNERS
Requested by @andrewelamb 
- Add code owners for Schematic
- List code owners in alphanumeric order
> chore: Add code owners for Schematic

- apps/openchallenges/infra/src/dns/openchallenges-dev-dns.ts
- apps/openchallenges/infra/src/preview-instance-alb/preview-instance-alb.ts
Closes #1898
- Update the preview instance ALB to use the certificate created in #1925
- Add Route53 record for `openchallenges.io`
- I'm keeping the record for `dev.openchallenges.io` so that the stack continues to work before Sage Week without changing host names in the configuration of the stack (requests are sent under the hood to `dev.openchallenges.io`)
> chore: Point `openchallenges.io` to the OC preview EC2 instance

- libs/openchallenges/challenge/src/lib/challenge-organizers/challenge-organizers.component.scss
- libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.scss
- libs/openchallenges/home/src/lib/featured-challenge-list/featured-challenge-list.component.scss
- libs/openchallenges/org-profile/src/lib/org-profile-members/org-profile-members.component.scss
- libs/openchallenges/styles/src/lib/_general.scss
- libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.scss
- libs/openchallenges/ui/src/lib/organization-card/organization-card.component.scss
- fixes #1928 
- Replace `auto-fit` by `auto-fill` in grid layout. `Auto-fill` will actually remain the layout and not fill the empty grid (which confused me by its name)
- ~~Make cards stretchable a bit to better fit in the container~~
>**Note**
>The cards have remained to use fixed width as @tschaffter suggests.
> feat(ui): Adjust layout of cards

- libs/openchallenges/challenge/src/lib/challenge-stats/challenge-stats.component.html
- libs/openchallenges/challenge/src/lib/challenge.component.html
- libs/openchallenges/org-profile/src/lib/org-profile.component.html
* hide stargazers metric from challenge profile
* display "N views" on challenge profile (instead of a distinct value)
* hide verification badge until we can add a tooltip and/or explanation what it means to be verified on OC
> fix(ui): Hide in-progess items for soft launch

- .github/workflows/ci.yml
Contributes to #1975
Enable the caching of Node.js packages when running the CI workflow. This PR makes the CI workflow runs 3 minutes faster as Node.js packages are cached and no longer need to be downloaded for each run of the workflow.
See this [comment](https://github.com/Sage-Bionetworks/sage-monorepo/issues/1975#issuecomment-1682529163) for more details.
UPDATE: The caching of Node.js packages was already active before this PR. The scope of this PR is limited to providing a more clean implementation of the Node.js packages caching.
Details of `yarn install --immutable`, which is executed by `workspace-install`:
```console
yarn install --immutable
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @cdktf/cli-core@npm:0.16.1 doesn't provide ink (pa54fc), requested by ink-select-input
➤ YN0002: │ …
```
> feat: Investigate yarn cache folder

- .github/workflows/ci.yml
Contributes to #1975
Enable the caching of R packages when running the CI workflow. This PR makes the CI workflow runs 3 minutes faster as R packages are cached and no longer need to be downloaded for each run of the workflow.
- Cache R packages
- Remove `--mount type="bind,source=$HOME/.docker,target=/home/vscode/.docker"` from the workflow when pushing to `main`. It was not set for the workflow triggered by push to a PR so it should not be needed.
- This PR is similar to #1979 but the tricky part (permissions) here is that the renv cache is outside of the repo folder cloned by the CI workflow (`~/.cache/R/renv/cache`).
> feat: Cache R packages in CI workflow

- .github/workflows/ci.yml
Contributes to #1975 
TODO
Time to run `nx run-many --target=prepare-python`:
- Without any caching: 
- 4m18s (1 run)
- When caching Poetry cache folder: 
- 2m45s (1 run)
- When caching venvs:
- 3m (1 run)
- For projects that have their `.venv` folder in the project folder,  the logs show that there are no packages to install when using the venv cache. Yet the "gain" of time is not strikingly apparent.
- It could be that the packages are cached with poetry and that installing them is relatively fast.
- It takes 12s to run `prepare-python` for `schematic-api` when caching Poetry and venv.
- It takes 30s to run `prepare-python` for `schematic-api` when caching only Poetry.
- For now I will continue to cache venv though it seems that its content may overlap with the content cached with …
> feat: Cache Poetry and venv in CI workflow

- .github/workflows/ci.yml
Contributes to #1975 
Cache the Gradle cache.
It is difficult to evaluate how much time is saved with this feature because the task `prepare-java` only install the Gradle wrapper. This task does not download and install the dependencies as the tasks `prepare-python` and `prepare-r` do. Here the approach implemented for Java project is more efficient as packages are downloaded only when needed.
The content of the Gradle cache folder in my dev container is about 400MB. These is at least as much data that will not need to be downloaded again and again.
```console
$ du -h --max-depth=0 ~/.gradle/caches
391M    /home/vscode/.gradle/caches
```
This is also visible when looking at the content of the cache (post cache):
```console
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude …
```
> feat: Cache Gradle in CI workflow

- .devcontainer/devcontainer.json
- apps/schematic/api/.gitignore
Closes #1998
- Update the devcontainer to get access to the SonarScanner CLI
- The scans shown below are run manually.
- Project folders would be scanned by a GH workflow if we decide to adopt Sonar tools.
```console
$ sonar-scanner --version
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarScanner 5.0.1.3006
INFO: Java 17.0.8 Private Build (64-bit)
INFO: Linux 4.14.320-243.544.amzn2.x86_64 amd64
```
Create a project on SonarCloud and follow the instructions. For a project of type "Other", which include Python projects, the SonarScanner CLI must be used. E.g.
```console
sonar-scanner \
-Dsonar.organization=tschaffter \
-Dsonar.projectKey=schematic-api \
-Dsonar.sources=. \ …
```
> feat: Update the devcontainer to access SonarScanner CLI

- .github/workflows/ci.yml
Disable the push of images to GHCR in CI workflow. This is a temporary measure to enable other contributors to merge to `main`. This quick fix will be permanently solved in #2013.
> fix: Disable docker push in CI workflow on main

- .devcontainer/devcontainer.json
- Update from Docker `20.10.24` to `24.0.5`
- Update the docker-in-docker feature
- Docker now uses SemVer instead of CalVer
- Since Docker `23.0`, Buildx must be installed separately as a plugin. Thankfully, the feature docker-in-docker takes care of that for us (see option [`installDockerBuildx`](https://github.com/devcontainers/features/tree/main/src/docker-in-docker) set to true by default)
1. Rebuild the dev container to get access to the new version of Docker
2. Set up the workspace: `workspace-install`
3. Build all the OC images: `openchallenges-build-images`
4. Start the OC stack: `nx serve-detach openchallenges-apex`
5. Test the web app in the browser
```console
$ docker --version
Docker version 24.0.5, build ced0996
```
> chore: Update Docker-in-Docker

- apps/schematic/api/prepare-python.sh
Contributes to #2036 
- Remove the Cython patch required for `schematic-api` to work with an earlier version of Python.
- The project `schematic-api` works now fine with Python 3.10.12 without the Cython patch.
> chore: Remove Cython patch from `schematic-api`

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- apps/openchallenges/image-service/build.gradle
Closes #2042 
Start pushing the results of Sonar scan for projects that implement the task `sonar` to SonarCloud.
New OC image service SonarCloud project: https://sonarcloud.io/project/overview?id=openchallenges-image-service
- Update the Sonar config of OC image service to push to its new project
- Add step to the CI workflow to generate and push the results of Sonar scans
- Pass the environment variables `SONAR_TOKEN` to the dev container
> **note**
> This PR modifies `devcontainer.json`, which will prompt users to rebuild their dev container.
- Ask @tschaffter to create a corresponding projects on SonarCloud.io
- Search Sage Monorepo for a project that already implement the task `sonar` and that use the same programming language as your project.
- If you found at least one project, use …
> ci: Push Sonar scan results when pushing to `main`

- .github/workflows/ci.yml
> fix: Define `SONAR_TOKEN` in CI workflow

- apps/openchallenges/app/project.json
- apps/schematic/api/project.json
- tools/sonar-scanner.sh
Closes #2053
Scan the project `schematic-api` and push the report to SonarCloud when pushing to the branch `main`.
- Add the task `sonar` to the project `schematic-api`
- Simplify the syntax of the task `sonar`
- Update the task `sonar` for the project `openchallenges-app`
See the [scan report](https://sonarcloud.io/summary/overall?id=schematic-api) for `schematic-api` on SonarCloud.
> ci: Scan Schematic API with Sonar

- apps/openchallenges/challenge-service/build.gradle
- apps/openchallenges/challenge-service/gradle.properties
- apps/openchallenges/challenge-service/project.json
Closes #2069
- Add the task `sonar` to the project `openchallenges-challenge-service`
- Use Nx variables `{projectName}` and `{projectRoot}` whenever possible in `project.json`
> ci: Configure Sonar for the challenge service

- apps/openchallenges/api-gateway/project.json
- apps/openchallenges/auth-service/project.json
- apps/openchallenges/challenge-service/project.json
- apps/openchallenges/challenge-to-elasticsearch-service/project.json
- apps/openchallenges/config-server/project.json
- apps/openchallenges/core-service/project.json
- apps/openchallenges/image-service/project.json
- apps/openchallenges/kaggle-to-kafka-service/project.json
- apps/openchallenges/notebook/project.json
- apps/openchallenges/organization-service/project.json
- apps/openchallenges/service-registry/project.json
- apps/openchallenges/user-service/project.json
- apps/schematic/api/project.json
- apps/schematic/notebook/project.json
- dev-env.sh
- libs/openchallenges/api-client-r/project.json
- libs/openchallenges/app-config-data/project.json
- libs/openchallenges/kafka-admin/project.json
- libs/openchallenges/kafka-consumer/project.json
- libs/openchallenges/kafka-model/project.json
- libs/openchallenges/kafka-producer/project.json
- libs/schematic/api-client-python/project.json
- libs/shared/java/util/project.json
- tools/prepare-java-envs.js
- tools/prepare-python-envs.js
- tools/prepare-r-envs.js
Closes #2075 
Adopt the same task name to prepare projects - mainly install dependencies - independently of the programming language and package manager used. The task `prepare-python`, `prepare-java` and `prepare-r` are renamed to `prepare`.
When preparing projects for specific languages (e.g. Java projects needs to be prepare one at a time to avoid a race condition), filtering is performed based on project tags.
The new command `workspace-install`:
```bash
function workspace-install {
yarn install --immutable
nx run-many --target=create-config
nx run-many --target=prepare --projects=tag:language:java --parallel=1
nx run-many --target=prepare --projects=tag:language:python --projects=tag:language:r
}
```
> **Warning**
> After checking out the update, running the command …
> refactor: Deprecate tasks `prepare-<languages>`

- dev-env.sh
> fix: `workspace-docker-stop` now checks if there are containers to stop 

- .github/workflows/ci.yml
- dev-env.sh
Closes #2087 
I asked this question in the main ticket. This PR makes the cache less relevant because they may include less packages now that we are only installing the packages for affected projects. Using only the affected projects to generate the cache key would over complicate the system and saturate the storage space available.
By default, caches are replaced when their key changes instead of updating the existing cache. Updating existing cache would be more storage space efficient but would increase the risks of cache poisoning. This is something that we could explore in the future for each type of cache (Yarn, Gradle, etc.).
This PR does not affect any projects, yet all the projects are prepared, which takes between 2-4 minutes depending on the status of the cache.
This PR does not …
> ci: Add the command `workspace-install-affected`

- apps/schematic/api/tox.ini
- tools/sonar-scanner.sh
Closes #2061
- Configure Schematic API to generate the coverage report in XML format
- Tells Sonar where to find coverage reports in XML format generate by Python projects
The coverage percentage of Schematic API is now published on the [Code Quality Dashboard](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/CODE_QUALITY.md).
@MiekoHash
> test: Push Schematic API coverage report to SonarCloud

- apps/openchallenges/app/src/app/app-routing.module.ts
- fixes #1972 
Now the scroll position is always reset to top by switching the pages/components
> feat(fix): Reset scroll position to top

- apps/openchallenges/app/src/app/app.config.ts
- apps/openchallenges/app/src/app/app.routes.ts
- apps/openchallenges/app/src/main.ts
Closes #2096
- Migrate the content of `app-routing.module.ts` to `app.routes.ts`
- Create the file `app.config.ts` introduced with Angular v16 which includes code for routes.
> **Note**
> The PR opened by @sagely1 adds a fresh new Angular project generated with the Angular generator. I used it as a reference for the implementation of `app.config.ts`.
@sagely1 This PR may interest you since it is related to a new concept/design introduced in Angular v16.
> refactor: Remove last module from OC app

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
Closes #2105
Enable the dev container used in the CI workflow to authenticate to GHCR and push images.
Until now the dev container in the CI workflow didn't have access to docker auth credentials to push to GHCR. This is because the login happens outside of the dev container and the container does not have access to the credentials.
Trying to push an image to GHCR inside the dev container results in this error:
```console
NX   buildx failed with: ERROR: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
```
After mounting the `$HOME/.docker` folder from the home to the dev container, a new error appears:
```console
Docker buildx is required. See https://github.com/gperdomor/nx-tools to set up nx-container executor with buildx.
```
The reason is that …
> ci: Enable Dev Container in CI workflow to push to GHCR

- apps/openchallenges/challenge-service/project.json
- apps/openchallenges/challenge-to-elasticsearch-service/project.json
- apps/openchallenges/image-service/project.json
- apps/openchallenges/kaggle-to-kafka-service/project.json
- apps/openchallenges/organization-service/project.json
- apps/openchallenges/user-service/project.json
- apps/schematic/api/project.json
- libs/openchallenges/api-client-angular/project.json
- libs/openchallenges/api-client-r/project.json
- libs/openchallenges/api-description/project.json
- libs/schematic/api-client-angular/project.json
- libs/schematic/api-client-python/project.json
- libs/schematic/api-description/project.json
- libs/synapse/api-description/project.json
Generating a REST API server stub and client is currently perform with this workflow:
1. Build the API description: E.g. `nx build <product>-api-description`
2. Generate the code: E.g. `nx openapi-generate <product>-api-client-python`
This PR proposes to chain these two commands so that running `nx openapi-generate <project>` will automatically build the API description the API server stub/client depends on.
UPDATE: Similarly, the task `lint` of API description projects also run their `build` task first.
> feat: Task `openapi-generate` now builds the API description

- libs/openchallenges/about/src/lib/about.component.html
- libs/openchallenges/about/src/lib/about.component.ts
- libs/openchallenges/challenge-search/src/lib/challenge-search.component.html
- libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
- libs/openchallenges/challenge/src/lib/challenge.component.html
- libs/openchallenges/challenge/src/lib/challenge.component.ts
- libs/openchallenges/config/src/lib/config.service.ts
- libs/openchallenges/home/src/lib/home.component.html
- libs/openchallenges/home/src/lib/home.component.ts
- libs/openchallenges/not-found/src/lib/not-found.component.html
- libs/openchallenges/not-found/src/lib/not-found.component.ts
- libs/openchallenges/org-profile/src/lib/org-profile.component.html
- libs/openchallenges/org-profile/src/lib/org-profile.component.ts
- libs/openchallenges/org-search/src/lib/org-search.component.html
- libs/openchallenges/org-search/src/lib/org-search.component.ts
- libs/openchallenges/team/src/lib/team.component.html
- libs/openchallenges/team/src/lib/team.component.ts
- libs/openchallenges/ui/src/lib/footer/footer.component.ts
- Closes #2027
- Contributes to #1966
- Pass all required input to the footer instances
- Start using `@Input({ required: true })`
The footer is defined as a UI component in the project `openchallenges-ui`. Following a best practice from Nx and to make the components reusable, the components defined in this project should not rely on app-specific services. This is the reason why the value of the footer inputs are no longer defined in the footer component itself. Rather, the input values are specified where the footer instances are created.
Unfortunately, the current design is that each page content has its own instance of the footer instead of defining a single instance - e.g. in the `app.component.ts`. I believe that the reason is to provide pages with more flexibility, but as far as I …
> fix: Specify the missing inputs of the footer

- libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.ts
- fixes #1947 
- filter unique challenge contributions regardless of roles on Challenge profile page  (this will be updated to categorize contributions into different tabs by roles in the future)
> feat(fix): Display unique challenge contributions

- .github/workflows/ci.yml
Contributes to #2128
Publish again the image of the API gateway. The last edge version was published 6 weeks ago, before I modified it to allow `/api/v1/challengeAnalytics`.
> fix: Publish again the `openchallenges-api-gateway` image

- .vscode/extensions.json
VS Code extensions are already installed as part of the devcontainer so there is no need to ask recommend the user to install them.
> chore: Remove duplicated VS Code extension information

- apps/openchallenges/challenge-service/config/application-local.yml
- apps/openchallenges/challenge-service/requests.http
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengeSearchQueryDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengeSortDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/CustomChallengeRepositoryImpl.java
- apps/openchallenges/challenge-service/src/main/resources/openapi.yaml
- libs/openchallenges/api-description/build/challenge.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeSearchQuery.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeSort.yaml
Closes #2133
Update the challenge service to fetch N random challenges with support for pagination. The random results are controlled by the new query parameters `sortSeed`. If the parameter is not specified, then a random seed is used.
- Add the challenge sorter `random`
- Add the challenge search query parameter `sortSeed`
Hibernate Search DSL does not allow to define the function score of a query. The solution adopted in this PR consists in implementing the query as a native JSON string.
> feat: Update API to get N random challenges

- apps/openchallenges/app/src/app/app.config.ts
Closes #2151 
Go back to using the default value for `scrollPositionRestoration`.
- The issue of search pages seems to be that modifying the filters triggers a page redirection (same page), which is why the scroll position is reset when using `scrollPositionRestoration: top` and `scrollPositionRestoration: enabled`.
> fix: Undo vertical scrolling reset in OC app

- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/api/OrganizationApiDelegateImpl.java
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/configuration/HibernateSearchIndexBuild.java
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/service/OrganizationService.java
This pull request modifies the following organization-service files to include constructor, rather than field, injection:
Issue 1392: https://github.com/Sage-Bionetworks/sage-monorepo/issues/1392
Fixes #(issue)
1392 organization-service only
- Add constructor injections see example below:
```
private final OrganizationRepository organizationRepository;
public OrganizationService(OrganizationRepository organizationRepository) {
this.organizationRepository = organizationRepository;
}
```
- Remove field injections i.e. `@Autowired OrganizationRepository organizationRepository`
> refactor: update org-service files using field injection

- apps/openchallenges/app/src/app/app.config.server.ts
- apps/openchallenges/app/src/app/app.config.ts
This is to address a warning message shown in the browser console when start the app without SSR (hydration is only useful for SSR, not CSR). This PR implements this change.
> refactor: Move client hydration provider to the server config

- libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.ts
Quick fix error on challenge profile > contributor, which causes possible undefined value for `OrganizationCards`.
- Change to use empty array as default value of `OrganizationCards`
> fix: Remove error on challenge contributors page

- apps/openchallenges/app/project.json
- apps/openchallenges/app/server.ts
- libs/openchallenges/config/src/lib/config.service.ts
Closes #2168
This PR enables the node server (Express) to read the app config file in all situations, e.g.
- when accessing the web app directly on port `4200` or via the apex on port `8000`
- when running the app dev server
- when running the app inside its container
- Use different location for the config file depending on whether app is run on the server or in the browser
App works when using
> fix: OC Apex is returning Internal Server Error

- apps/openchallenges/challenge-service/.env.example
- apps/openchallenges/organization-service/.env.example
Contributes to #2047
- Update the value of the config parameter `DB_URL` in `.env.example` for the challenge and organization service
> **Note**
> The value of `DB_URL` must be manually updated in `.env`, which is not tracked.
> **Note**
> The base branch of this PR is the feature branch `load-local-infile`.
> **Warning**
> The challenge and organization services fail to start when using this parameter. I'm assuming that it's because the server (MariaDB) is not configured yet.
> feat: Add option `allowLoadLocalInfile=true` to `DB_URL`

- libs/openchallenges/about/src/lib/about-seo-data.ts
- libs/openchallenges/about/src/lib/about.component.ts
- libs/openchallenges/challenge-search/src/lib/challenge-search-seo-data.ts
- libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
- libs/openchallenges/challenge/src/lib/challenge-seo-data.ts
- libs/openchallenges/challenge/src/lib/challenge.component.ts
- libs/openchallenges/home/src/lib/home.component.ts
- libs/openchallenges/org-profile/src/lib/org-profile-seo-data.ts
- libs/openchallenges/org-search/src/lib/org-search-seo-data.ts
- libs/openchallenges/org-search/src/lib/org-search.component.ts
- libs/openchallenges/team/src/lib/team-seo-data.ts
- libs/openchallenges/team/src/lib/team.component.ts
Closes #1962
- Add SEO metadata to the Team page
- Add SEO metadata to the About page
- Add SEO metadata to the challenge profile page
- Improve SEO metadata on the org profile page
- Add SEO metadata to the challenge search page
- Add SEO metadata to the organization search page
> **Note**
> The image is broken because the image URL points to the local Thumbor server, which the card preview tool can't reach.
> feat: Set page titles in OC app

- .github/workflows/lint-pr.yml
Closes #2226
- Configure values that the PR title scope can take
- Ensures the subject doesn't start with an uppercase character
The GH workflow updated in this PR is not affecting the title of this PR. The updated workflow should start taking effect once it's merged to `main`.
> feat(sage-monorepo): standardize PR title scope

- libs/openchallenges/home/src/lib/home.component.html
- package.json
- yarn.lock
Fixes #2187
HTML files that include self-closing tags for Angular component can now be saved without Prettier throwing an exception.
- Prettier received a major version released 5 months ago. To stay on the safe side, I decided to go with the latest `2.x.x` release. We can try upgrading to the next major version as part of the next bi-annual dependency update.
> fix(sage-monorepo): update prettier to fix self-closing HTML tags introduced in Angular v16

- libs/openchallenges/ui/src/lib/footer/footer.component.html
Fixes #2208 
* re-add link to API docs in footer
* add `title` and `rel="noopenner noreferer"` attributes to external links (per best practice recommendations)
You can't see it in the screenshot, but my mouse is hovering over the **API Docs** link:
> feat(openchallenges): add link to OC API docs

- libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.html
- libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.ts
- closes #2241 
- use `challengePlatformService` to get the total number of platforms in database
> feat(openchallenges): fetch total number of platforms from backend on Home page

- .devcontainer/devcontainer.json
- .vscode/settings.json
Closes #2261
Configure Format On Save for Python files.
- Prevent `flake8` from running when saving Python files
- Add VS Code extension [`ms-python.black-formatter`](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) to the dev container
- Configure Format On Save with Black for Python files
- See [Migration to Python Tools Extensions](https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions)
- Requires the new extension to be installed, either manually or by rebuilding the dev container.
Also, the Black extension for VS Code says:
> The bundled black is only used if there is no installed version of black found in the selected python environment.
Your Python project must still have `black` as a dev dependencies in your project …
> fix(sage-monorepo): format on save Python files with `black`

- .github/workflows/ci.yml
- apps/agora/mongo/project.json
- apps/openchallenges/apex/project.json
- apps/openchallenges/api-docs/project.json
- apps/openchallenges/api-gateway/project.json
- apps/openchallenges/app/project.json
- apps/openchallenges/challenge-service/project.json
- apps/openchallenges/config-server/project.json
- apps/openchallenges/elasticsearch/project.json
- apps/openchallenges/grafana/project.json
- apps/openchallenges/image-service/project.json
- apps/openchallenges/mariadb/project.json
- apps/openchallenges/mysqld-exporter/project.json
- apps/openchallenges/organization-service/project.json
- apps/openchallenges/prometheus/project.json
- apps/openchallenges/rstudio/project.json
- apps/openchallenges/service-registry/project.json
- apps/openchallenges/thumbor/project.json
- apps/openchallenges/vault/project.json
- apps/openchallenges/zipkin/project.json
- apps/schematic/api-docs/project.json
- apps/schematic/api/project.json
- apps/synapse/rstudio/project.json
Closes #2271
The CI workflow now builds - and publishes when pushing to `main` - all the Docker images of the affected projects. This set of images had to be reduced to a small, static number because of limited storage space available on the default GH-hosted runner. We recently upgraded Sage Monorepo to use a larger runner, which allows us to build the images of all the affected projects.
> fix(sage-monorepo): build and publish the images of all the affected projects in CI workflow

- libs/openchallenges/home/src/lib/sponsor-list/sponsor-list.component.html
- libs/openchallenges/home/src/lib/sponsor-list/sponsor-list.component.ts
> fix(openchallenges): remove Sage from sponsor list

- libs/openchallenges/challenge-search/src/lib/challenge-search.component.html
- libs/openchallenges/org-search/src/lib/org-search.component.html
- libs/openchallenges/ui/src/lib/paginator/paginator.component.ts
- closes #2094 
- hide the pageSize options (dropdown) on search pages
> feat(openchallenges): hide page size options on search pages

- libs/openchallenges/team/src/lib/team.component.html
- Change verb tense
- Fix typos in the headline
I'm not sure why the formatting is slightly different for me and @vpchung. We will address this if the format change back and forth.
> fix(openchallenges): update Team page headline

- libs/openchallenges/about/src/lib/about.component.spec.ts
- libs/openchallenges/not-found/src/lib/not-found.component.spec.ts
- libs/openchallenges/ui/src/lib/footer/footer.component.html
- libs/openchallenges/ui/src/lib/footer/footer.component.spec.ts
- libs/openchallenges/ui/src/lib/footer/footer.component.ts
- libs/openchallenges/ui/src/lib/navbar/navbar.component.html
Closes #2303
- Add the button "Team" to the right panel of the navbar
- Replace `href` by `routerLink` in the navbar and footer for links that target app pages
> **Note**
> Navigating to a page of the app with `href` destroys and reloads the app. This can be observed by looking at the navbar that flickers when navigating with `href`. Instead, navigating to pages of the app should be done with `routerLink` (requires to import the `RouterModule`). In that case, the navbar will remain and only the components that are no longer used will be destroyed, which leads to faster navigation.
> feat(openchallenges): add Team button to OC navbar

- libs/openchallenges/challenge/src/lib/_challenge-theme.scss
- libs/openchallenges/challenge/src/lib/challenge.component.html
- libs/openchallenges/themes/src/_palettes.scss
- libs/openchallenges/ui/src/lib/challenge-card/_challenge-card-theme.scss
- libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.html
- libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.scss
- libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.ts
Fixes #2240 
* add logic for calculating time difference in units of years, months, weeks, days, and hours
* display time until start date OR time until end date (depending on status), using the largest non-zero time unit
* due to limited space in the footer: re-arrange the card layout, switching placements of status and platform
* update "Incentives" icon to something more obvious (trophy)
* add fixed heights for status and headline divs; that way, cards stay uniformed in height no matter the contents
Footer icons using the same color:
OR one footer icon uses the blue color from our logo and one icon uses the other:
Alternatively, we can forgo displaying the platform altogether (something Addison mentioned as potentially not helpful information):
> feat(openchallenges): add temporal information to challenge card

- libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.ts
* add a new parameter to `calcTimeDiff`, so that hiding timeline > 3 months is optional
* use case: for active and upcoming challenges, it is still valuable to show the temporal info, even if it's beyond 3 months away 
* add type annotation for return value ([feedback](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2277#discussion_r1377770930)) 
* if an unexpected date format is given, throw an Error instead of returning an empty string ([feedback](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2277#discussion_r1377792909))
* relatedly, add a try-catch for function call
> [!NOTE]
> I had tried the other approach mentioned in the feedback, but I kept getting an error about not being able to do the arithmetic operation when approaching things that way
**Before**
**After**
> fix(openchallenges): challenge card fixes

- libs/openchallenges/challenge/src/lib/challenge-stats/challenge-stats.component.html
- libs/openchallenges/challenge/src/lib/challenge-stats/challenge-stats.component.ts
- libs/openchallenges/challenge/src/lib/challenge.component.html
Closes #2321
- Specify the `Challenge` object to the stat component with `@Input`
> fix(openchallenges): fix challenge stats on OC challenge page

- .eslintrc.json
- closes #1544
Currently, we can use "bang" operator (!) in TypeScript to bypass the null checks, but it has the potential risk, like actual null or undefined values at runtime leading to unforeseen errors.
- Instead of relying on the "bang" operator, use TypeScript's strict mode to deal with null and undefined values, so that the developers can be informed initially
Now using "bang" operator (!) will not bypass the null checks, instead we can use (?) and (??) to handle nulls.
➡️ see more details about [no-non-null-assertion](https://typescript-eslint.io/rules/no-non-null-assertion)
> feat(openchallenges): add strict eslint rule on null checks 

- libs/openchallenges/challenge-search/src/lib/challenge-search.component.scss
- libs/openchallenges/org-search/src/lib/org-search.component.scss
- libs/openchallenges/styles/src/lib/_general.scss
- fixes #2349 
- Add a responsive max-width for the multi-select dropdown filter to avoid unexpected expansion of the filter panel
Laptop screen:
Mobile screen:
> fix(openchallenges): implement responsive width for `mullti-select` filter on search pages

- libs/openchallenges/challenge/src/lib/challenge-overview/challenge-overview.component.html
Fixes #2361 
* add logic for displaying "Not available" if there are no submission types found for a challenge
> fix(openchallenges): show 'Not available' for empty submission types

- apps/openchallenges/api-docs/project.json
Closes #2366
- Make the task `build-image` of the OC API docs depend on `build`
> chore(openchallenges): make it easier to update the OC API docs image

- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/service/ChallengeAnalyticsService.java
- libs/openchallenges/home/src/_lib-theme.scss
- libs/openchallenges/home/src/lib/statistics-viewer/_statistics-viewer-theme.scss
- libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.html
- libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.scss
- libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.ts
- closes #2365 
- change html to reflect caption
- update caption text by not specifying detailed number of missing challenges
- remove challengerPerYear data after current year
> feat(openchallenges): cap challenges to 2023 on timeline plot

- apps/openchallenges/image-service/gradle.properties
Closes #2373
- Downgrade fasterxml package to fix `READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE` issue in the image service
> fix(openchallenges): fix the OC image service issue `READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE`

- .gitignore
- .vscode/extensions.json
- apps/openchallenges/app/.eslintrc.json
- apps/openchallenges/app/e2e/challenge-search-paginator.spec.ts
- apps/openchallenges/app/e2e/example.spec.ts
- apps/openchallenges/app/e2e/home.spec.ts
- apps/openchallenges/app/jest.config.ts
- apps/openchallenges/app/playwright.config.ts
- apps/openchallenges/app/project.json
- apps/openchallenges/app/tsconfig.spec.json
Closes #2377
This PR adds the task `e2e` to the project `openchallenges-app`. The e2e tests are run for different browsers with Playwright. The browsers and devices tested are defined in `playwright.config.ts`.
E2e tests with Playwright work very smoothly with our dev container. It's easy to install the browser and their dependencies (see below), even Google Chrome and Microsoft Edge.
- Add e2e tests with Playwright using Nx generator
- Configure Playwright to output results to the terminal
- Configure Playwright to not automatically open the HTML report (could be configured with an env var)
- Configure Jest to exclude e2e tests
- Update the dev container to include all browser dependencies so they are available to the CI workflow and to the developers.
- Identify the devices and browser …
> test(openchallenges): add e2e tests to OC web app

- tools/devcontainers/sage/.devcontainer/Dockerfile
Closes #2387
- Add Chromium, FF and Webkit to the dev container for e2e testing with Playwright
- Use the new recommended way to install Node.js
> test(openchallenges): add browsers for e2e testing with Playwright to the dev container

- .devcontainer/devcontainer.json
- dev-env.sh
- Closes #2390
- Contributes to #2387
- Switch to a different Jest extension for VS Code
- Update the recommended version of VS Code
- I expected the browsers themselves (FF, Chromium, Webkit) to be already installed as part of the dev container, but running `nx e2e openchallenges-app` the first time still installed them again (same location as when installed in the dev container, i.e. in the home folder of the user `vscode`).
> **Note**
> Individual tests are run by clicking on a green arrow. E2e with Playwright will also be run with the same green arrow.
Cc: @rrchai @vpchung @sagely1
> test(openchallenges): update dev container image for better TypeScript testing

- .github/workflows/schematic-api-ci.yml
- apps/schematic/api/.gitignore
- apps/schematic/api/project.json
- apps/schematic/api/pytest.ini
- apps/schematic/api/schematic_api/controllers/schema_controller_impl.py
- apps/schematic/api/schematic_api/controllers/utils.py
- apps/schematic/api/schematic_api/test/conftest.py
- apps/schematic/api/schematic_api/test/data/synapse_config_example.yaml
- apps/schematic/api/schematic_api/test/test_schema_controller_endpoints.py
- apps/schematic/api/schematic_api/test/test_schema_controller_impl.py
- apps/schematic/api/schematic_api/test/test_synapse_endpoints.py
- apps/schematic/api/schematic_api/test/test_tangled_tree_impl.py
- apps/schematic/api/schematic_api/test/test_utils.py
This is identical to [#2398](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2398) plus some fixes to the testing workflow.
This PR chas a new wrokflow that is trggred when PRs are made from the new `Schematic-API-Staging` branch into `main`.
This PR:
- fixes [fds-1288](https://sagebionetworks.jira.com/browse/FDS-1284)
- fixes [fds-1288](https://sagebionetworks.jira.com/browse/FDS-1288)
- PRs are now done from forks to Schematic-API-Staging instead of main
- PRs to Schematic-API-Staging only trigger tests that don't require secrets
- PR's are then don form Schematic-API-Staging to Main
- A new workflow that triggers when PRs are done from Schematic-API-Staging to Main that runs all tests has been added
- All non synapse tests are not mocked at all
- A new set of tests …
> feat(schematic): integration testing

- libs/openchallenges/challenge-search/src/lib/challenge-search.component.html
- libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.html
- libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.spec.ts
- libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.ts
- libs/openchallenges/home/src/lib/random-challenge-list/random-challenge-list.component.html
- libs/openchallenges/home/src/lib/random-challenge-list/random-challenge-list.component.spec.ts
- libs/openchallenges/home/src/lib/random-challenge-list/random-challenge-list.component.ts
- libs/openchallenges/org-search/src/lib/org-search.component.html
- fixes #2363 
There are two flickerings on search pages:
1. Results (0) -> Results (N)
2. Results (N) ->  Results (0) -> Results (N) - it's only occurred on [openchallenges.io](openchallenges.io) based on my observation
- replace `href` with `routerlink` - [the difference between two](https://stackoverflow.com/questions/58081360/anchor-href-vs-angular-routerlink#:~:text=Href%20is%20the%20basic%20attribute,components%20without%20reloading%20the%20page.) 
- not rendering the number of search result and pagination (when there's no data to avoid the flickering 1)
- the reason of flickering 2 is still not identified as I am not able to reproduce locally, but I found [angular's hydration](https://angular.io/guide/hydration#why-is-hydration-important) might be associated with the flickering …
> fix(openchallenges): fix flickering on search pages after clicking "see more"

- libs/openchallenges/challenge-search/src/lib/challenge-search.component.html
- libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
- libs/openchallenges/org-search/src/lib/org-search.component.html
- libs/openchallenges/org-search/src/lib/org-search.component.ts
- libs/openchallenges/ui/src/lib/paginator/paginator.component.html
- libs/openchallenges/ui/src/lib/paginator/paginator.component.ts
- fixes #2425 
As we added a new condition to not the paginator element if no data found, the variable of `paginator` is undefined initially as it is static, which caused the error ^.
- Change the `paginator` to dynamic, so its value will be set after the content is fully initialized
- Use `PrimeNG` built-in [property](https://www.primefaces.org/primeng-v14-lts/paginator) `alwaysShow=false` to hide the paginator when there is only one page
- Update page index on paginator UI once the `pageNumber` of param in a pasted url presents
- Disable the `pageSize` changes from the pasted url
> fix(openchallenges): change paginator variable to dynamic rendering

- .github/workflows/ci.yml
Contributes to #2439
The next step will be to submit and merge a PR that modifies `openchallenges-app` and see if the Sonar checks are listed by GitHub.
> ci(sage-monorepo): temporarily comment out sonar scan for pushes to main

- .github/workflows/sonar-scan.yml
The goal is to create a GH workflow that can be executed by PRs from forks and that can trigger a scan of the PR branch with Sonar (needs access to Sonar secret).
> ci(sage-monorepo): experiment with `pull_request_target`

- .github/workflows/sonar-scan.yml
- apps/openchallenges/app/src/app/app.component.html
Contributes to #2450
This PR provides a developer-friend information about the branch checked out in the sonar workflow.
```
Run echo "github.event.pull_request.head.ref: try-sonar-again"
github.event.pull_request.head.ref: try-sonar-again
repository: tschaffter/sage-monorepo
```
> ci(sage-monorepo): try new sonar scan workflow for PRs

- .devcontainer/devcontainer.json
- .github/workflows/sonar-scan.yml
- apps/openchallenges/app/src/app/app.component.html
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/OrganizationServiceApplication.java
Contributes to #2450
Modified the Sonar workflow to properly pass the environment variable to the dev container.
> ci(sage-monorepo): fix how env vars are passed to the dev container

- .github/workflows/sonar-scan.yml
- apps/openchallenges/app/src/app/app.component.html
- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/OrganizationServiceApplication.java
- tools/sonar-scanner.sh
Contributes to #2450
- Require the PR to have the label `sonar-scan-approved` to run Sonar
- Remove hard-coded PR number
This PR confirms that we can scan multiple projects with Sonar for given commit and have all the results 1) publishing in the PR thread and 2) added to the list of checks (screenshot).
> ci(sage-monorepo): try sonar scan again for PRs originating from forks

- apps/schematic/api/poetry.lock
- apps/schematic/api/pyproject.toml
- apps/schematic/api/schematic_api/controllers/manifest_validation_controller_impl.py
- apps/schematic/api/schematic_api/controllers/storage_controller_impl.py
- apps/schematic/api/schematic_api/controllers/tangled_tree_controller_impl.py
- apps/schematic/api/schematic_api/controllers/utils.py
- fixes [fds-1661](https://sagebionetworks.jira.com/browse/FDS-1661)
- Upgrades schematic to 23.12.1
- Upgrades other packages minor versions
- Incorporates typing fixes from 23.12.1
- Removes typing.Union and typing.Optional for pipe notation `Optional[str]` -> `str | None` as is standard in python 3.10 or higher
- Some docstring fixes
> feat(schematic): upgrade schematic version and fix typing

- apps/schematic/api/poetry.lock
- apps/schematic/api/pyproject.toml
- apps/schematic/api/schematic_api/controllers/manifest_validation_controller_impl.py
- apps/schematic/api/schematic_api/controllers/storage_controller_impl.py
- apps/schematic/api/schematic_api/controllers/tangled_tree_controller_impl.py
- apps/schematic/api/schematic_api/controllers/utils.py
- fixes [fds-1661](https://sagebionetworks.jira.com/browse/FDS-1661)
- Upgrades schematic to 23.12.1
- Upgrades other packages minor versions
- Incorporates typing fixes from 23.12.1
- Removes typing.Union and typing.Optional for pipe notation `Optional[str]` -> `str | None` as is standard in python 3.10 or higher
- Some docstring fixes
> feat(schematic): update scheamtic and typing fixes

- apps/iatlas/postgres/Dockerfile
- apps/iatlas/postgres/docker-healthcheck
- tools/configure-hostnames.sh
Closes #2492
- Add health check to the `iatlas-postgres` container
- Register the local hostname `iatlas-postgres`
Build the image:
```
nx build-image iatlas-postgres
```
Start the container:
```
nx serve-detach iatlas-postgres
```
Open the Docker extension for VS Code. The health of the container is now displayed.
> feat(iatlas): add health check to the `iatlas-postgres` container

- .github/workflows/update-db-csv-files.yml
- .github/workflows/update-oc-db-csv-files.yml
- .gitignore
- apps/openchallenges/db-update/update_db_csv.py
Fixes #2485
Fixes #2418
* add script for pulling data from the [OC Data](https://docs.google.com/spreadsheets/d/1XRSUVqbZk_k9_rV1vpgPVMQ0fVV0mavwY8Aqyy0C2HQ/edit#gid=1744053577) Google Sheet, cleaning it up, then dumping it into CSV files
* add CI workflow to update the DB CSV files daily and open a PR
* add Google client (GC) credentials file (needed for `gspread` Python library) to `.gitignore`
> [!NOTE]
> I need to figure out how to add and use schematic as a step, but the workflow as-is achieves the goal of updating the CSV files (see screenshots below).
> [!IMPORTANT]
> ### [See screenshots below for most recent changes.](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2489#issuecomment-1939764562)
* **Example PR:**
* **Files updated:**
The workflow uses two secrets:
* …
> feat(openchallenges): add CI workflow for updating the DB dump files on a daily cadence

- libs/openchallenges/team/src/lib/team.component.html
- libs/openchallenges/team/src/lib/team.component.ts
- libs/openchallenges/ui/src/lib/footer/footer.component.html
- libs/openchallenges/ui/src/lib/footer/footer.component.ts
* use Sage's new logo 
* remove `height` specifications; since the new logos are smaller than the previous logos, specifying the heights made the logos looked blurry, so they have been removed
* **Footer**
* **Meet the Team page**
* **Sage profile**
(this will be seen in the next DB update)
> fix(openchallenges): update Sage logo

- libs/openchallenges/home/src/lib/home.component.html
- libs/openchallenges/home/src/lib/sponsor-list/sponsor-list.component.html
- libs/openchallenges/home/src/lib/sponsor-list/sponsor-list.component.scss
- libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.html
- libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.scss
- libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.ts
Fixes #2378 
Note: this PR contains a subset of changes proposed in #2402 (now closed)
* adjust logo size of ITCR image when screen is smaller - this is what caused the black margin in the bug report
* adjust text size and label rotation in timeline plot
Once orientation of plot is determined (see screenshots below), remove the unneeded code
* **ITCR logo**
* **Timeline plot**
Alternatively, we can flip the plot so that the y-axis is the category (year) and the x-axis is the data:
> fix(openchallenges): make homepage more mobile-friendly

- libs/openchallenges/team/src/lib/team.component.html
- libs/openchallenges/team/src/lib/team.component.ts
- libs/openchallenges/ui/src/lib/footer/footer.component.html
- libs/openchallenges/ui/src/lib/footer/footer.component.ts
I misunderstood the announcement - we do not need to update the logos until after March 4th.
This reverts commit 95559b384e7994c326c7cb1a274e24bc55e5eb9d.
> fix(openchallenges): revert #2501

- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengeSubmissionTypeDto.java
- apps/openchallenges/challenge-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
- apps/openchallenges/challenge-service/src/main/resources/openapi.yaml
- apps/openchallenges/db-update/update_db_csv.py
- libs/openchallenges/api-client-angular/src/lib/model/challengeSubmissionType.ts
- libs/openchallenges/api-description/build/challenge.openapi.yaml
- libs/openchallenges/api-description/build/openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeSubmissionType.yaml
- libs/openchallenges/challenge-search/src/lib/challenge-search-filters.ts
Fixes #2509
* update OC Data spreadsheet to include `mlcube_submission` column
* update db-update script to include "mlcube_submission" in the CSV dump
* add `mlcube` as an enum value to the `challenge_submission_type` database table
* add `mlcube` to the API description
* regenerate:
* OpenAPI spec (with `nx build openchallenges-api-description`)
* Java files (with `nx run openchallenges-challenge-service:generate`)
* Angular API client (with `nx run openchallenges-api-client-angular:generate`)
* add "MLCube" as one of the facet values for **Submission Type**
* **Describe `challenge_submission_type` table:**
* **Challenge search page:**
> feat(openchallenges): add "MLCube" as a submission type

- .github/CODEOWNERS
- add Loreen and Anthony as code owner of the Schematic API client for R (requested by @andrewelamb )
> chore(sage-monorepo): add Loreen and Anthony as code owner of the Schematic API client for R

- .github/workflows/sonar-scan.yml
- add support to run Sonar on Sage Monorepo branches
> chore(sage-monorepo): add support to run Sonar on Sage Monorepo branches

- .github/workflows/sonar-scan.yml
- fix the name of a job step when pushing to an upstream branch
- temporarily run Sonar on all projects to initialize scans for upstream branches
> chore(sage-monorepo): fix Sonar workflow job names

- .github/workflows/sonar-scan.yml
- revert temporary change made to the Sonar scan workflow in #2518
> chore(sage-monorepo): run Sonar only on affected projects again

- docs/developers-guide/creating-a-commit-with-multiple-authors.md
- mkdocs.yml
Closes #2526
- [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)
> docs(sage-monorepo): fix the format of the co-author docs page

- apps/schematic/api/schematic_api/controllers/storage_controller.py
- apps/schematic/api/schematic_api/controllers/storage_controller_impl.py
- apps/schematic/api/schematic_api/openapi/openapi.yaml
- apps/schematic/api/schematic_api/test/conftest.py
- apps/schematic/api/schematic_api/test/test_storage_controller_endpoints.py
- apps/schematic/api/schematic_api/test/test_storage_controller_endpoints2.py
- apps/schematic/api/schematic_api/test/test_storage_controller_impl.py
- apps/schematic/api/schematic_api/test/test_synapse_endpoints.py
- libs/schematic/api-description/build/openapi.yaml
- libs/schematic/api-description/src/openapi.yaml
- libs/schematic/api-description/src/paths/assetTypes/@{assetType}/assetViews/@{assetViewId}/csv.yaml
- libs/schematic/api-description/src/paths/assetTypes/@{assetType}/datasets/@{datasetId}/manifestCsv.yaml
- libs/schematic/api-description/src/paths/assetTypes/@{assetType}/manifests/@{manifestId}/csv.yaml
- fixes [FDS-1688]
- Adds endpoints that return csv files
- Please review 
1. all files in `libs/schematic/api-description/src/`
2. all files in `apps/schematic/api/schematic_api/controllers/`  except  `storage_controller.py`
[FDS-1688]: https://sagebionetworks.jira.com/browse/FDS-1688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(schematic): fds-1688 add endpoints that return files

- .github/workflows/ci.yml
Close #2537
- fix how the merge commit is checked out for a PR
- update to `actions/checkout@v4`
- update to `nrwl/nx-set-shas@v4`
In the context of a pull request created from a fork, the CI workflow was checking out the source repository (fork) and branch that triggered the PR with the action `actions/checkout@v4` (now updated to v4). Instead, we should rely on the default behavior of this action to checkout a merge commit created from 1) the last commit pushed to the base branch (the official, upstream `main` branch) and 2) the last commit pushed to the source branch used to create this PR.
Example: This workflow run reports the SHA of the merged commit, `f9bc2a178306146a2278c4a171e5361b10a802f5`:
```
Disabling automatic garbage collection
Setting up auth
Fetching the repository …
```
> fix(sage-monorepo): enable `nx affected` to compare HEAD to the official main branch

- apps/openchallenges/db-update/update_db_csv.py
Complimentary PR to #2521 (more context [here](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2521#discussion_r1499886099)) and #2534
Now that we are grabbing the EDAM ontology directly from source, there is no longer a need for us to dump a CSV file for EDAM terms.
* update CSV dumping script to not dump the CSV file for EDAM terms
* remove the unneeded function
* update CSV dumping script to handle select invisible unicode characters (more context [here](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2534#issue-2154814288))
* include `operation_id` in the CSV dump, using NULL as the default value
> chore(openchallenges): update CSV dumping script

- apps/openchallenges/db-update/update_db_csv.py
* typo fix for the word joiner unicode character (`\u2060`, _not_ `\u2020`)
* specify that regex is used for unicode replacement
I have verified that these changes will update the CSVs as expected:
```python
>>> challenges = df[["id", ..., "updated_at"]]
>>> challenges.loc[460, "description"]
'The Food and Drug Administration (FDA) -\u202fCenter for Devices and Radiological Health (CDRH), Sage Bionetworks, and\u202fprecisionFDA call on ...'
>>> 
>>> challenges = (
...         challenges.replace({r"\s+$": "", r"^\s+": ""}, regex=True)
...         .replace(r"\n", " ", regex=True)
...         .replace("'", "''", regex=True)
...         .replace(u"\u2019", "''", regex=True)  # replace curly right-quote 
...         .replace(u"\u202f", " ", regex=True)  # replace narrow no-break space
... …
```
> fix(openchallenges): dumping script quick fixes

- .github/workflows/ci.yml
Fixes #2542
- switch from the detached HEAD of the merge commit to a new branch in the CI workflow triggered by a PR
> fix(sage-monorepo): fix buildx error when running on a detached HEAD

- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengeEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/EdamOperationEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/service/ChallengeService.java
Closes #2550
- enable the user to search challenges by EDAM ID and preferred name
`http://localhost:8000/challenge?searchTerms=http://edamontology.org/operation_3207`
I knew ES was tokenizing on blank space by default but not that it also tokenizes on slash. I wanted to allow users to search with only the last part of the class ID (e.g. "operation_3207") so it's nice that this feature is already implemented.
`http://localhost:8000/challenge?searchTerms=operation_3207`
BTW, this is how we can visualize how ES tokenize the property `operation.class_id`:
```
http://localhost:9200/openchallenges-challenge-000001/_termvectors/4?fields=operation.class_id
{
"_index": "openchallenges-challenge-000001",
"_type": "_doc",
"_id": "4",
"_version": 1,
"found": true,
"took": 1,
"term_vectors": { …
```
> feat(openchallenges): enable users to search challenges using EDAM operation ID and preferred label

- .github/CODEOWNERS
- apps/openchallenges/edam-etl/project.json
Closes #2565
- add the task `sonar` to the project `openchallenges-edam-etl`
- add @mdsage1 as a Code Owner of the project `openchallenges-edam-etl`
- document how to create a new project on SonarCloud.io (see ticket)
> [!NOTE]  
> This PR triggered the scans of projects that are not touched by this PR. This is because the GitHub workflow `sonar-scan.yml` uses an incorrect method to checkout the codebase. The correct method is currently implemented in `ci.yml`. This will be fixed in an incoming PR.
> feat(openchallenges): add the task `sonar` to the project `openchallenges-edam-etl`

- apps/openchallenges/api-gateway/project.json
- apps/openchallenges/auth-service/project.json
- apps/openchallenges/challenge-service/project.json
- apps/openchallenges/challenge-to-elasticsearch-service/project.json
- apps/openchallenges/config-server/project.json
- apps/openchallenges/core-service/project.json
- apps/openchallenges/image-service/project.json
- apps/openchallenges/kaggle-to-kafka-service/project.json
- apps/openchallenges/organization-service/project.json
- apps/openchallenges/service-registry/project.json
- apps/openchallenges/user-service/project.json
- docker/openchallenges/services/challenge-service.yml
- libs/openchallenges/app-config-data/project.json
- libs/openchallenges/kafka-admin/project.json
- libs/openchallenges/kafka-consumer/project.json
- libs/openchallenges/kafka-model/project.json
- libs/openchallenges/kafka-producer/project.json
- libs/shared/java/util/project.json
- nx.json
- package.json
- yarn.lock
Closes #2584
- remove the Nx plugin `@nxrocks/nx-spring-boot`
- replace Java tasks that used the plugin with direct calls to `gradlew`
- remove the container `openchallenges-edam-etl` from the stack because its image is broken
> chore(sage-monorepo): remove `@nxrocks/nx-spring-boot`

- .github/workflows/lint-pr.yml
Add the `bridge2ai` project to the scope.
> chore(sage-monorepo): add bridge2ai project scope to PR title linter

- .vscode/settings.json
- apps/openchallenges/mariadb/docker-entrypoint-initdb.d/init-db.sql
Closes #2605
- create the DB `edam` in OC MariaDB instance
- create the user `edam_etl` with write permission to this new DB
- create the user `edam_challenge_service` with read-only permission to this new DB
> chore(openchallenges): create new EDAM DB

- .github/CODEOWNERS
- tools/devcontainers/sage/.devcontainer/Dockerfile
- update ubuntu to the latest stable version, but still using a pinned version
- update Python tools installed in the devcontainer (Poetry, pyenv)
- update pre-installed Python environments
> chore(sage-monorepo): update ubuntu and Python tools in devcontainer

- .github/workflows/update-oc-db-csv-files.yml
Addresses the [comment about a label deprecation](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2641#issuecomment-2076071438).
> fix(openchallenges): remove label assignment

- apps/schematic/api/poetry.lock
- apps/schematic/api/pyproject.toml
- apps/schematic/api/schematic_api/controllers/manifest_validation_controller_impl.py
- apps/schematic/api/schematic_api/controllers/schema_controller_impl.py
- apps/schematic/api/schematic_api/test/conftest.py
- apps/schematic/api/schematic_api/test/data/manifests/biospecimen_incorrect.csv
- apps/schematic/api/schematic_api/test/test_manifest_validation_controller_impl.py
- fixes [FDS-1931]
- Upgrades schematic to 24.4.1
[FDS-1931]: https://sagebionetworks.jira.com/browse/FDS-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(schematic): fds 1931 upgrade schematic version

- docs/developers-guide/developing-on-a-remote-host.md
Update developer docs on how to connect to the EC2 instance in AWS Console
> docs(sage-monorepo): update developer docs on how to connect to the EC2 instance in AWS Console

- docs/developers-guide/developing-on-a-remote-host.md
- Update developer docs on how to connect to the EC2 instance from VS Code
- Add link to Service Catalog docs
> docs(sage-monorepo): update developer docs on how to connect to the EC2 instance from VS Code

- apps/model-ad/app/project.json
- apps/model-ad/app/src/app/app.config.ts
- apps/model-ad/app/src/app/app.routes.ts
- apps/model-ad/app/src/config/config.json
- apps/model-ad/app/src/config/config.json.template
- libs/model-ad/config/.eslintrc.json
- libs/model-ad/config/README.md
- libs/model-ad/config/jest.config.ts
- libs/model-ad/config/project.json
- libs/model-ad/config/src/index.ts
- libs/model-ad/config/src/lib/app.config.ts
- libs/model-ad/config/src/lib/config.factory.ts
- libs/model-ad/config/src/lib/config.service.ts
- libs/model-ad/config/src/test-setup.ts
- libs/model-ad/config/tsconfig.json
- libs/model-ad/config/tsconfig.lib.json
- libs/model-ad/config/tsconfig.spec.json
- libs/model-ad/not-found/src/lib/not-found.component.ts
- tsconfig.base.json
- create the library `model-ad-config`
- add config file for the development server in `src/config/config.json`
- add template config file used when the app is containerized in `src/config/config.json.template`
- load the config during the initialization of the app
- inject the config server into the constructor of the not-found page
- [The Twelve-Factor App](https://www.12factor.net/)
Today, VS Code became unresponsive. After closing and reopening VS Code, we noticed that the port 4200 was in use. I assumed that it was the development server of MODEL-AD that was still running in the background. One way to kill a process that uses a specific port is using the workspace command `workspace-kill-port {port number}`. This command failed because my assumption was incorrect: it was actually the …
> feat(model-ad): externalize the app config

- .github/CODEOWNERS
- .github/workflows/lint-pr.yml
- libs/results-visualization-framework/ui/.eslintrc.json
- libs/results-visualization-framework/ui/.storybook/main.ts
- libs/results-visualization-framework/ui/.storybook/tsconfig.json
- libs/results-visualization-framework/ui/README.md
- libs/results-visualization-framework/ui/jest.config.ts
- libs/results-visualization-framework/ui/project.json
- libs/results-visualization-framework/ui/src/index.ts
- libs/results-visualization-framework/ui/src/lib/test/test.component.html
- libs/results-visualization-framework/ui/src/lib/test/test.component.scss
- libs/results-visualization-framework/ui/src/lib/test/test.component.spec.ts
- libs/results-visualization-framework/ui/src/lib/test/test.component.stories.ts
- libs/results-visualization-framework/ui/src/lib/test/test.component.ts
- libs/results-visualization-framework/ui/src/test-setup.ts
- libs/results-visualization-framework/ui/tsconfig.json
- libs/results-visualization-framework/ui/tsconfig.lib.json
- libs/results-visualization-framework/ui/tsconfig.spec.json
- tsconfig.base.json
Adds a new UI library for components that are shared between Agora and Model-AD.
- [AG-576](https://sagebionetworks.jira.com/browse/AG-576)
- Add `results-visualization-framework-ui` component library with a test component that demonstrates Storybook and testing-library
- Run tests: `nx run results-visualization-framework-ui:test`
- Run storybook: `nx run results-visualization-framework-ui:storybook`
https://github.com/Sage-Bionetworks/sage-monorepo/assets/26949006/e0a85daa-5c9a-42bc-9301-c02b4fef3fd4
[AG-576]: https://sagebionetworks.jira.com/browse/AG-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(sage-monorepo): add results-visualization-framework ui library (AG-576)

- apps/openchallenges/api-gateway/src/main/resources/application.yml
- apps/openchallenges/challenge-service/src/main/resources/application.yml
- apps/openchallenges/challenge-to-elasticsearch-service/src/main/resources/application.yml
- apps/openchallenges/image-service/src/main/resources/application.yml
- apps/openchallenges/kaggle-to-kafka-service/src/main/resources/application.yml
- apps/openchallenges/organization-service/src/main/resources/application.yml
- apps/openchallenges/service-registry/src/main/resources/application.yml
spring boot [issue 3346](https://github.com/spring-projects/spring-boot/issues/33446)
says it's not possible to override Spring Import with SPRING_CONFIG_IMPORT env var.  The suggestion is to use confighost instead which can be overriden with a CONFIGHOST env var.
> refactor(openchallenges): overideable config-server spring import config

- apps/agora/data/project.json
Tags `agora-data` image with data release version when publishing to GHCR
Related to #2732
- Tags `agora-data` image with data release version when publishing to GHCR
> fix(agora): tag agora-data image with data release version when publishing to GHCR

- apps/openchallenges/organization-service/src/main/java/org/sagebionetworks/openchallenges/organization/service/configuration/EurekaInstanceConfiguration.java
Contributes to #2762
When deployed to AWS ECS, the value of the port of the organization service must be specified to the Eureka client. This configuration is moved from environment variables to Java code to consolidate the config.
> feat(openchallenges): update the Eureka config bean to set port for the org service

- nx.json
The remote cache was generated when using Yarn. We are now using pnpm and the remote cache leads to errors, so we should no longer rely on it for now. Here I'm disabling the remote cache until I figure out how to clear the remote cache or decide to create a new workspace if clearing the remote cache is not possible as I believe.
- Disable Nx remote cache
- Tell Nx that the package manager is pnpm
> chore(sage-monorepo): disable Nx remote cache

- apps/agora/api/Dockerfile
- apps/agora/api/project.json
Fixes #2773
- Bundle the dependencies with the `agora-api` app
- Fix the task `agora-api:build:production` (see successful CI workflow run below)
Building the app will generate several warnings. Despite the "error", those are still warnings and the command exit status is successful (0).
```console
$ nx run agora-api:build:production
...
WARNING in ../../../node_modules/.pnpm/mongodb@6.7.0_socks@2.8.3/node_modules/mongodb/lib/deps.js 45:35-75
Module not found: Error: Can't resolve '@aws-sdk/credential-providers' in '/workspaces/sage-monorepo/node_modules/.pnpm/mongodb@6.7.0_socks@2.8.3/node_modules/mongodb/lib'
WARNING in ../../../node_modules/.pnpm/mongodb@6.7.0_socks@2.8.3/node_modules/mongodb/lib/deps.js 57:35-58
Module not found: Error: Can't resolve 'gcp-metadata' in …
```
> fix(agora): build `agora-api` app as standalone app

- pnpm-workspace.yaml
- Exclude API clients for Angular from pnpm workspaces
Remaining workspaces:
```console
$ pnpm m ls --depth -1 --json
[
{
"name": "sage-monorepo",
"version": "0.0.0",
"path": "/workspaces/sage-monorepo",
"private": true
}
]
```
> fix(sage-monorepo): keep only the root workspace as pnpm workspace

- tools/devcontainers/sage/.devcontainer/devcontainer.json
Contributes to #2794
- Touch the definition of the dev container to trigger a rebuild with the new GitHub CLI GPG key
- It is expected that the CI/CD workflow will fail because the dev container image it uses is affected by the issue we are fixing here.
> fix(sage-monorepo): publish a new dev container with valid GitHub CLI GPG key

- .devcontainer/devcontainer.json
> fix(sag-monorepo): update devcontainer image to fix expired GitHub CLI GPG key

- .husky/post-checkout
- .husky/post-merge
- .husky/post-rewrite
- .husky/pre-commit
- .husky/pre-push
- apps/openchallenges/app/src/main.ts
- lint-staged.config.js
- package.json
- pnpm-lock.yaml
Closes #2799 
- Update Husky from v8 to v9
- Install and configure `lint-staged`
- Format and lint files during pre-commit (except Python files)
- Remove deprecated lines at the top of Husky git hook scripts
- Remove unused `google-java-format`
```console
$ git commit -m 'format YAML files'
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
[sage-monorepo/pre-commit-format 855b9791] format YAML files
2 files changed, 15 insertions(+), 10 deletions(-)
rewrite lint-staged.config.js (91%)
```
`nx format` is a wrapper around Prettier that needs a patch to format Java files. This patch could be removed if we end up not using `nx format`. The two instructions shown below were specified in `lint-staged` JS …
> feat(sage-monorepo): configure pre-commit hooks to format and lint files

- .gitignore
While Python projects may want to ignore this folder, we create new TypeScript projects that may have such a folder as part of the codebase. Hence, removing `lib/` from the root `.gitignore`. 
- https://github.com/github/gitignore/blob/main/Python.gitignore
> fix(sage-monorepo): remove `lib/` from .gitignore

- .github/workflows/ci.yml
[Triggering merge group checks with GitHub Actions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions)
> feat(sage-monorepo): add `on.merge_group` to the CI workflow

- .github/workflows/lint-pr.yml
- #2825 
- https://github.com/amannn/action-semantic-pull-request/issues/236
> fix(sage-monorepo): prevent the PR validation workflow to run in the merge queue

- .github/workflows/lint-pr.yml
- README.md
- Add MODEL-AD to the list of products developed in this monorepo
> [!NOTE]  
> This PR is the first one opened since enabling on the merging queue.
> docs(sage-monorepo): add MODEL-AD to the list of products

- tools/devcontainers/sage/.devcontainer/Dockerfile
This will fix the installation of hadolint, which currently is downloaded as a blank file because `curl` doesn't follow redirects by default.
> fix(sage-monorepo): ensure that `curl` follows redirections in dev container Dockerfile (ARCH-278)

- .hadolint.yaml
- lint-staged.config.js
- tools/devcontainers/sage/.devcontainer/Dockerfile
Closes https://sagebionetworks.jira.com/browse/ARCH-278
- Configure `lint-staged` to lint staged Dockerfiles with Hadolint
- Remove a rule exception from the dev container Dockerfile
- Update a comment Hadolint config file
> feat(sage-monorepo): lint staged Dockerfiles with Hadolint (ARCH-278)

- libs/agora/api-description/openapi-lint-config.yaml
- libs/model-ad/api-description/openapi-lint-config.yaml
- libs/model-ad/api-description/project.json
- libs/model-ad/api-description/spectral.yaml
- Validate MODEL-AD OpenAPI description using workspace-level configuration
- Remove the local config of the validator from `model-ad-api-description`
The workspace-level configuration and ruleset of the OpenAPI validator can be found here:
- `tools/ibm-openapi-validator/config.yaml`
- `tools/ibm-openapi-validator/spectral.yaml` (ruleset)
```console
$ nx lint model-ad-api-description
> nx run model-ad-api-description:build
> redocly bundle --output build/openapi.yaml src/openapi.yaml
bundling src/openapi.yaml...
📦 Created a bundle for src/openapi.yaml at build/openapi.yaml 44ms.
> nx run model-ad-api-description:lint
> lint-openapi --config tools/ibm-openapi-validator/config.yaml libs/model-ad/api-description/build/openapi.yaml
IBM OpenAPI Validator (validator: 1.22.1), @Copyright IBM …
```
> chore(model-ad): validate MODEL-AD OpenAPI description using workspace-level configuration 

- libs/agora/api-description/project.json
- libs/agora/api-description/spectral.yaml
- tools/ibm-openapi-validator/.spectral.js
- tools/ibm-openapi-validator/config.yaml
- tools/ibm-openapi-validator/spectral.yaml
Switch OAS validation ruleset from YAML to JS. This will enable us to further customize rules beyond just setting them to `off` and `level`. For example, we will be able to specify that path segments should be camel case with a level set to warn, then later error.
- Switch OAS validation ruleset from YAML to JS
- Update the task `agora-api-description:lint` to use the monorepo-wide OAS validation config
> feat(sage-monorepo): adopt JS for definining OAS validation ruleset

- .devcontainer/devcontainer.json
About Pyright VS Code extension:
> For most VS Code users, we recommend using the Pylance extension rather than Pyright. Pylance incorporates the Pyright type checker but features additional capabilities such as semantic token highlighting and symbol indexing. When Pylance is installed, the Pyright extension will disable itself.
- https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright
> chore(sage-monorepo): remove Pyright VS Code extension

- apps/schematic/api/Dockerfile
Fixes https://sagebionetworks.jira.com/browse/FDS-2453
The task `schematic-api:build-image` failed 3-4 hours ago. I realized that this is because 1) the base image has been updated around that time and 2) the project is using a moving tag (`python3.10`).
The underlying issue seems to be that the base image comes with a newer version of Python (3.10.15) not compatible with the version specified by the project (3.10.14). Ideally, we should be able to specify the version of Python to use in the Dockerfile, e.g. using pyenv. This would provide some flexibility so that the version used by the project is not imposed by the Python version running in the Docker image. For instance, it's preferable to use one of the Python version pre-installed in the Sage monorepo dev container for running tasks …
> fix(sage-monorepo): fix `schematic-api:build-image` issue by using a non-moving tag (FDS-2453)

- apps/sandbox/angular-app/src/app/app.component.html
- apps/sandbox/angular-app/src/app/app.component.ts
- libs/sandbox/angular-lib/.eslintrc.json
- libs/sandbox/angular-lib/README.md
- libs/sandbox/angular-lib/jest.config.ts
- libs/sandbox/angular-lib/project.json
- libs/sandbox/angular-lib/src/index.ts
- libs/sandbox/angular-lib/src/lib/sandbox-angular-lib/sandbox-angular-lib.component.html
- libs/sandbox/angular-lib/src/lib/sandbox-angular-lib/sandbox-angular-lib.component.spec.ts
- libs/sandbox/angular-lib/src/lib/sandbox-angular-lib/sandbox-angular-lib.component.ts
- libs/sandbox/angular-lib/src/test-setup.ts
- libs/sandbox/angular-lib/tsconfig.json
- libs/sandbox/angular-lib/tsconfig.lib.json
- libs/sandbox/angular-lib/tsconfig.spec.json
- tsconfig.base.json
Closes https://sagebionetworks.jira.com/browse/ARCH-285
- Add the `sandbox-angular-lib` project
- Import the single component from the lib into `sandbox-angular-app`
- https://nx.dev/nx-api/angular/generators/library
- #2843
```console
nx g @nx/angular:library sandbox-angular-lib \
--directory libs/sandbox/angular-lib \
--prefix sandbox \
--projectNameAndRootFormat as-provided \
--dry-run
```
Then, I prefixed the key for this project with `@sagebionetworks/` in `tsconfig.base.json` located in the root folder. This enables to import the library as `@sagebionetworks/sandbox-angular-lib`.
```console
nx serve sandbox-angular-app
```
> feat(sandbox): create the `sandox-angular-lib` project (ARCH-285)

- apps/agora/api-docs/Dockerfile
- apps/model-ad/api-docs/Dockerfile
- apps/openchallenges/api-docs/Dockerfile
- apps/schematic/api-docs/Dockerfile
I had a look at all the API docs sites and they look good.
> chore(sage-monorepo): update API docs image to `redocly/redoc:v2.1.5`

- apps/openchallenges/thumbor/Dockerfile
- apps/openchallenges/thumbor/docker-entrypoint.sh
Fixes https://sagebionetworks.jira.com/browse/IT-3908
This PR implements a temporary fix to the issue reported in https://github.com/beeyev/thumbor-s3-docker/issues/35.
> fix(openchallenges): patch the entry point script of Thumbor to replace 'None' by None

- .prettierrc.yml
- package.json
- pnpm-lock.yaml
Contributes to https://sagebionetworks.jira.com/browse/ARCH-294
- Add the npm package `prettier-plugin-tailwindcss`
- https://www.freecodecamp.org/news/how-to-set-up-eslint-prettier-stylelint-and-lint-staged-in-nextjs
In `apps/sandbox/angular-app/src/app/nx-welcome.component.ts`, order the classes as shown below:
```html
<div id="learning-materials" class="shadow rounded">
```
Prettier is applied upon saving the file to order the classes in alphabetical order:
```html
<div id="learning-materials" class="rounded shadow">
```
> feat(sage-monorepo): add the Tailwind CSS plugin for Prettier to ensure consistent formatting in our styles (ARCH-294)

- apps/agora/app/src/app/app.component.html
- apps/agora/app/src/app/app.component.ts
- libs/agora/ui/src/index.ts
- libs/agora/ui/src/lib/components/footer/footer.component.html
- libs/agora/ui/src/lib/components/footer/footer.component.spec.ts
- libs/agora/ui/src/lib/components/footer/footer.component.ts
- libs/agora/ui/src/lib/components/header/header.component.html
- libs/agora/ui/src/lib/components/header/header.component.scss
- libs/agora/ui/src/lib/components/header/header.component.spec.ts
- libs/agora/ui/src/lib/components/header/header.component.ts
- libs/agora/ui/src/lib/models/navigation-link.ts
Migration of Header component
**Note: Header styling does not match original repo (yet).  There is too much margin above the header.
Also, gene search box will be implemented in a future PR: https://sagebionetworks.jira.com/browse/AG-1550
- Header has been added
- fixed minor bugs in footer.
https://sagebionetworks.jira.com/browse/AG-1549
`nx test agora-ui`
Navigate to:
http://localhost:4200
Desktop width
Mobile width and with hamburger menu opened.
> feat(agora): migrate Header component and utils (AG-1549)

- apps/openchallenges/apex/project.json
- `metadata.images` must be specified in any configuration that defines `metadata.tags`
> fix(sage-monorepo): try again `semver` in the release workflow

- .github/actions/setup-dev-container/action.yml
This is an attempt at troubleshooting why the CI workflow fails in #2884
> chore(sage-monorepo): disable pnpm cache in CI workflow to troubleshoot error

- apps/agora/apex/project.json
- apps/agora/api-docs/project.json
- apps/agora/api/project.json
- apps/agora/app/project.json
- apps/agora/data/project.json
- apps/agora/mongo/project.json
- libs/sage-monorepo/nx-plugin/src/plugins/plugin.ts
- libs/sage-monorepo/nx-plugin/src/plugins/project-metadata.ts
Closes https://sagebionetworks.jira.com/browse/ARCH-307
- Update the Nx plugin to support Agora apps
- Remove the task `build-image` from the `project.json` files
The Agora apps can still be dockerized even if their `project.json` files no longer define the task `build-image`, which is now defined in the Sage Monorepo Nx plugin.
```console
$ agora-build-images
$ docker images
REPOSITORY                                TAG           IMAGE ID       CREATED          SIZE
ghcr.io/sage-bionetworks/agora-data       local         fa10d1fc58fb   5 seconds ago    219MB
ghcr.io/sage-bionetworks/agora-data       sha-f70dfb0   fa10d1fc58fb   5 seconds ago    219MB
ghcr.io/sage-bionetworks/agora-api        local         95eb65d77850   26 seconds ago   141MB
ghcr.io/sage-bionetworks/agora-api …
```
> feat(agora): centralize the task definition `build-image` (ARCH-307)

- .devcontainer/devcontainer.json
Closes https://sagebionetworks.jira.com/browse/ARCH-314
- Add the VS Code extension [Python Environment Manager](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python-environment-manager) to the dev container
The extension lists all the venvs created in the monorepo:
Other features:
1. **Single-click venv activation via ⭐ icon**:
- **Feature Description**: The user can easily activate a virtual environment by clicking a star (⭐) icon associated with the environment, instead of navigating the VS Code command palette.
- **Purpose**: This makes the process of selecting and activating a Python interpreter more user-friendly and quicker compared to using the command palette.
2. **Installed package list with version status**:
- **Feature Description**: The extension displays a …
> feat(sage-monorepo): add VS Code extension to manage Python venvs (ARCH-314)

- .github/workflows/scan-images.yml
Closes https://sagebionetworks.jira.com/browse/ARCH-321
> fix(sage-monorepo): specify Trivy ECR repositories instead of default ones (ARCH-321)

- .github/workflows/scan-repo.yml
Same as #2904 but for the GH workflow that scans the repo with Trivy.
> fix(sage-monorepo): use ECR DB when scanning repo with Trivy

- .github/workflows/ci.yml
Contributes to https://sagebionetworks.jira.com/browse/ARCH-336
> fix(sage-monorepo): replace the task `publish-image` by `build-image` in CI worflow

- apps/openchallenges/thumbor/project.json
Contributes to https://sagebionetworks.jira.com/browse/ARCH-336
Test if the new `build-image` task used in the main CI workflow successfully push the image to GHCR.
> fix(openchallenges): remove the task `openchallenges-thumbor:publish-image`

- nx.json
References:
- https://nx.dev/deprecated/legacy-cache
- https://github.com/nrwl/nx/issues/28434
> chore(sage-monorepo): remove Nx custom task runner to avoid repeating deprecation warnings

- tools/devcontainers/sage/.devcontainer/Dockerfile
Closes [ARCH-350](https://sagebionetworks.jira.com/browse/ARCH-350)
```console
devcontainer up --workspace-folder .
devcontainer exec --workspace-folder . sam --version
SAM CLI, version 1.131.0
```
[ARCH-350]: https://sagebionetworks.jira.com/browse/ARCH-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(sage-monorepo): add AWS SAM CLI to the devcontainer (ARCH-350)

- .devcontainer/devcontainer.json
- Remove the Nx Console extension for VS Code because of its high CPU usage.
This may be a one off issue but since we are not actively using this extension, it's better to remove it to keep the dev environment lean.
> fix(sage-monorepo): remove Nx Console extension for VS Code

- libs/openchallenges/themes/src/_index.scss
Fixes #2950 
* Add an import for the Material icons font to the main scss
**Before**
**After**
> fix(openchallenges): display Material icons on the app

- .github/workflows/scan-images.yml
Update actions/upload-artifact to v4, since v3 is [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). For example, see failing workflow [here](https://github.com/Sage-Bionetworks/sage-monorepo/actions/runs/12695095805/job/35386933297?pr=2956).
> fix(sage-monorepo): update actions/upload-artifact version

- libs/shared/typescript/charts-angular/project.json
- libs/shared/typescript/charts-angular/src/lib/boxplot/boxplot.directive.spec.ts
Fixes the `shared-typescript-angular-charts:test` target that was failing after the monorepo update to Angular 19, see discussion [here](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2958#discussion_r1909449657). 
Example output from `nx run shared-typescript-angular-charts:test`:
```
PASS   shared-typescript-charts-angular  libs/shared/typescript/charts-angular/src/lib/boxplot/boxplot.directive.spec.ts (5.366 s)
BoxplotDirective
✓ should render no data placeholder when no data is passed (369 ms)
✓ should render boxplot with static summaries (133 ms)
✓ should render boxplot with dynamic summaries (101 ms)
----------------------|---------|----------|---------|---------|-------------------
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```
> fix(agora): fix shared-typescript-angular-charts:test target after Angular update (AG-1610)

- .github/workflows/update-oc-db-csv-files.yml
Ubuntu-24.04 image will be used as the default image for `ubuntu-latest` [[ref](https://github.com/actions/runner-images/issues/10636)]
* remove the need to specifically use Python 3.10, since schematic is not used (3.10 is cached in Ubuntu-24.04 anyway)
* general actions versions update
Tested the CI update in my test repo and the changes work as expected (that is, no unintentional change to the workflow is seen):
> chore(openchallenges): update CI for update-db-csv

- .github/.devcontainer/Dockerfile
- .github/.devcontainer/README.md
- .github/.devcontainer/devcontainer.json
- .github/workflows/build-and-push-devcontainer-image.yml
- Generate a new dev container prebuild image with up-to-date tools.
- Migrate to Ubuntu 24.04.
- Add `uv`.
- Add Go toolchain.
- Add Kubectl, minikube, and Helm.
- Prebuild the dev container feature Docker-in-Docker.
- Sign the Docker image with Cosine.
- Generate SBOM for the Docker image.
- Attach an SBOM attestation to the Docker image.
- Publish the SBOM to GitHub's dependency graph.
> refactor: update dev container with a new, signed prebuild image

- .github/.devcontainer/Dockerfile
- .github/workflows/build-and-push-devcontainer-image.yml
- Publish the attestation of the dev container image build with GitHub.
- Install the system dependencies needed by `canvas` on Ubuntu 24.04.
> chore: publish the attestation of the dev container prebuilt image with GH

- .github/workflows/build-and-push-devcontainer-image.yml
The workflow previously failed to generate and publish the build attestation because the permission `id-token: write` was missing.
> chore: create `attest` job for the dev container prebuilt image

- .github/.devcontainer/Dockerfile
- .github/.devcontainer/devcontainer.json
Contributes to https://sagebionetworks.jira.com/browse/SMR-1
Build the dev container Docker image locally.
```console
devcontainer build   --workspace-folder .github   --image-name ghcr.io/sage-bionetworks/sage-monorepo-devcontainer:local
```
Scan the image for CVEs.
```console
$ trivy image --severity CRITICAL ghcr.io/sage-bionetworks/sage-monorepo-devcontainer:local
2025-01-27T21:44:23Z    INFO    [vuln] Vulnerability scanning is enabled
2025-01-27T21:44:23Z    INFO    [secret] Secret scanning is enabled
2025-01-27T21:44:23Z    INFO    [secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2025-01-27T21:44:23Z    INFO    [secret] Please see also https://aquasecurity.github.io/trivy/v0.54/docs/scanner/secret#recommendation for faster secret detection …
```
> chore: fix critical CVEs in the dev container Docker image (SMR-1)

- apps/openchallenges/data-lambda/Dockerfile
* Due to #2978, update Dockerfile so that v3.11 is used to install dependencies
**Before Dockerfile update**
```
$ nx run openchallenges-data-lambda:invoke --event events/event.json
> nx run openchallenges-data-lambda:invoke --event events/event.json
> curl -X POST 'http://localhost:9000/2015-03-31/functions/function/invocations' --data @events/event.json
{"errorMessage": "Unable to import module 'app': No module named 'gspread'", "errorType": "Runtime.ImportModuleError", "requestId": "", "stackTrace": []}
```
**After**
```
$ nx run openchallenges-data-lambda:invoke --event events/event.json
> nx run openchallenges-data-lambda:invoke --event events/event.json
> curl -X POST 'http://localhost:9000/2015-03-31/functions/function/invocations' --data @events/event.json
{"statusCode": 200, …
```
> fix(openchallenges): specify older version of python to match pyproject

- libs/agora/api-client-angular/src/lib/model/proteomicsDistribution.ts
- libs/agora/api-description/build/openapi.yaml
- libs/agora/api-description/src/components/schemas/ProteomicsDistribution.yaml
- libs/agora/charts/src/lib/box-plot-chart/box-plot-chart.component.ts
- libs/agora/genes/src/lib/components/gene-evidence-proteomics/gene-evidence-proteomics.component.ts
- libs/agora/genes/src/lib/components/gene-evidence-rna/gene-evidence-rna.component.ts
Fixes bug where boxplot data would persist after changing the model. 
- [AG-1673](https://sagebionetworks.jira.com/browse/AG-1673)
- Resets boxplot chart data when input data is updated
- Adds types in RNA and Protein component methods
Build agora images: `agora-build-images`
Run app: `nx run agora-apex:serve-detach`
Navigate to PLEC RNA tab: http://localhost:8000/genes/ENSG00000178209/evidence/rna --
https://github.com/user-attachments/assets/5540c223-767b-470b-9763-5c3d7c6744be
Navigate to PLEC Protein page: http://localhost:8000/genes/ENSG00000178209/evidence/protein -- 
https://github.com/user-attachments/assets/8b62f17a-cf64-4f64-ac98-3937f0fc604d
[AG-1673]: https://sagebionetworks.jira.com/browse/AG-1673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …
> fix(agora): reset boxplot before updating data (AG-1673)

- libs/shared/typescript/charts/src/lib/boxplot-chart/boxplot-chart.ts
Aligns the boxplot y-axis and x-axis end with other charts
- [AG-1659](https://sagebionetworks.jira.com/browse/AG-1659)
Run agora: `agora-build-images && nx run agora-apex:serve-detach`
Navigate to RNA genes page: http://localhost:8000/genes/ENSG00000171862/evidence/rna
[AG-1659]: https://sagebionetworks.jira.com/browse/AG-1659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AG-1659]: https://sagebionetworks.jira.com/browse/AG-1659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(agora): align boxplot y-axis and x-axis end with other charts (AG-1659)

- libs/agora/teams/src/lib/team-member-list/team-member-list.component.scss
Team member link styling was using browser defaults.
This change fixes the styling and co-locates the hyperlink styling logic.  
Before:
After:
> fix(agora): fixing team member link styling (AG-1646)

- libs/agora/charts/src/lib/box-plot-chart/box-plot-chart.component.html
- libs/agora/charts/src/lib/box-plot-chart/box-plot-chart.component.ts
- libs/agora/genes/src/lib/components/gene-evidence-rna/gene-evidence-rna.component.html
- libs/shared/typescript/charts/src/lib/boxplot-chart/boxplot-chart.ts
Increases max width of each boxplot and overall height of boxplot chart to more closely align with current Agora boxplot chart.
- [AG-1678](https://sagebionetworks.jira.com/browse/AG-1678)
Build and run agora: `agora-build-images && nx run agora-apex:serve-detach`.
Navigate to RNA boxplot to see increased plot height: http://localhost:8000/genes/ENSG00000171862/evidence/rna
Navigate to Protein boxplot to see increased boxplot width: http://localhost:8000/genes/ENSG00000178209/evidence/protein
type | current agora | new agora | fixed new agora
:---:|:---:|:---:|:---:
RNA | <img width="1543" alt="develop-rna" src="https://github.com/user-attachments/assets/fd503c06-055f-43e2-92bd-b5f28b872c46" /> | <img width="1544" alt="newdevelop-rna" …
> fix(agora): increase boxplot height and allow boxes to take up more space as in current agora (AG-1678)

- apps/agora/api/src/models/teams.ts
- libs/agora/api-client-angular/src/lib/model/teamMember.ts
- libs/agora/api-description/build/openapi.yaml
- libs/agora/api-description/src/components/schemas/TeamMember.yaml
- libs/agora/teams/src/lib/team-member-list/team-member-list.component.spec.ts
- libs/agora/teams/src/lib/team-member-list/team-member-list.component.ts
Fixed bug in team member names not sorting correctly due to a property not matching the casing in MongoDB (isprimaryinvestigator).
Note: In the future, for consistency we should consider coordinating with @JessterB to use snake casing to match other properties in the database.
> fix(agora): fix team members sorting (AG-1650)

- .github/CODEOWNERS
- .github/workflows/e2e-agora.yaml
- apps/agora/app/playwright.config.ts
Adds a GHA workflow to run Agora's e2e tests on push to main in Sage's sage-monorepo and on push to any branch in user owned forks of sage-monorepo.
- [AG-1623](https://sagebionetworks.jira.com/browse/AG-1623)
See a successful workflow run [in my fork](https://github.com/hallieswan/sage-monorepo/actions/runs/13319316907).
View report by: 1) downloading "playwright-report" artifact, 2) opening zip, 3) opening index.html file in browser.
To run the workflow in sage-monorepo (or your own fork): 
1. Create a new Synapse PAT with view/download permissions for the `synapse-service-agora-e2e` user 
2. Add the PAT as an Actions Secret named `AGORA_DATA_SYNAPSE_AUTH_TOKEN` to sage-monorepo
Job speed is greatly impacted by time to download data from Synapse in the "Start Agora" step, but improving …
> feat(agora): run agora e2e tests in CI (AG-1623)

- .github/workflows/e2e-agora.yaml
- tools/setup-projects.sh
The Agora e2e job failed [on merge to main](https://github.com/Sage-Bionetworks/sage-monorepo/actions/runs/13338951817/job/37260035903) because the `setup-dev-container` action only preps affected projects and only `agora-app` was marked as affected, so the config file for `agora-data` wasn’t created and the agora stack couldn’t be started. This PR adjusts the workflow to prep all agora projects, rather than the affected projects, so the full stack can be built for e2e tests to run against. 
- [AG-1623](https://sagebionetworks.jira.com/browse/AG-1623)
- Sets up all projects in the agora stack, rather than only affected projects
- Adds a tool to run set up tasks (`create-config`, `prepare`) for all projects in a particular stack
- Changes the Agora e2e workflow to check whether any agora …
> fix(agora): setup all projects when running agora e2e, not just affected projects (AG-1623)

- .github/workflows/e2e-agora.yaml
- .github/workflows/sonar-scan-pull-request.yml
Replicates the `pull_request_target` functionality of the existing `sonar-scan-pull-request` workflow, which allows a job triggered by a PR from a forked repo to access secrets when the run is approved by an authorized user.
- [SMR-17](https://sagebionetworks.jira.com/browse/SMR-17)
This PR replicates the setup of the existing sonar job, but utilizes two environments (`agora`, `agora-pr`) rather than separating into two jobs (`sonar-scan-pull-request`, `sonar-scan-push`) . Plan to validate once this PR has been merged and a new Agora PR from a forked repo is synchronized, e.g. #3015.
[SMR-17]: https://sagebionetworks.jira.com/browse/SMR-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(agora): run agora e2e on PRs when approved by authorized user (SMR-17)

- .github/workflows/e2e-agora.yaml
The Agora e2e workflow [failed to build Agora](https://github.com/Sage-Bionetworks/sage-monorepo/actions/runs/13442764721/job/37560942742?pr=3015) because `NX   Cannot find detached HEAD ref in "HEAD"`. We need to checkout a branch so buildx works, as demonstrated in the [ci pull request job](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/.github/workflows/ci.yml#L89-L98). 
We also need to ensure that the correct ref is checked out when pushing to main.
> fix(agora): ensure correct ref is checked out and that buildx works (SMR-17)

- apps/agora/app/.env.example
- apps/agora/app/src/config/config.json
- apps/agora/data/.env.example
`agora-app` displays two values for the Site Version in the footer: an app version and a commit SHA (looked up using a tag name). These values are set to the current release in [the infra code](https://github.com/Sage-Bionetworks-IT/agora-infra-v3/blob/dev/app.py#L140-L145). However, keeping the example values in `.env.example` and `config.json` aligned with the actual latest release adds extra overhead. Instead, we would like to use "edge" as the placeholder in these files.
Separately, the data manifest version was recently updated in [agora-data-manager](https://github.com/Sage-Bionetworks/agora-data-manager/pull/133). This PR updates the `agora-data` value to match.
- [AG-1681](https://sagebionetworks.jira.com/browse/AG-1681)
Update `APP_VERSION` and `TAG_NAME` in `apps/agora/app/.env` …
> chore(agora): use edge for app version and tag name placeholder, update data version to align with agora-data-manger (AG-1681)

- .github/actions/setup-dev-container/action.yml
- .github/workflows/ci.yml
- .github/workflows/e2e-agora.yaml
- .github/workflows/release.yml
- .github/workflows/sonar-scan-pull-request.yml
- .github/workflows/sonar-scan-push.yml
Closes https://sagebionetworks.jira.com/browse/SMR-18
- Remove the preparation of affected projects from `setup-dev-container`.
- Update the `setup-dev-container` to return the list of affected projects.
- Update the Agora e2e workflow to use the list of affected projects from `setup-dev-container`.
> chore: decouple setup dev container from preparing projects (SMR-18)

- .github/workflows/e2e-agora.yaml
We should only show Agora's e2e workflow as "waiting" on PRs that affect Agora.
Here is a run in [my fork](https://github.com/hallieswan/sage-monorepo/actions/runs/13554103650/attempts/1) that shows the two jobs and that Agora e2e tests run when Agora is affected.
> fix(agora): only show agora's e2e workflow as waiting on PRs that affect agora (SMR-19)

- apps/agora/app/project.json
- apps/agora/app/src/config/config.json
- apps/agora/app/src/proxy.conf.json
We would like to take advantage of live reloading when developing locally in Agora by serving the app with the development server and running all other services in their Docker containers. However, the app requests to the API result in CORS errors. This PR configures the [Angular development server proxy](https://angular.dev/tools/cli/serve) to handle API requests.
- [AG-1707](https://sagebionetworks.jira.com/browse/AG-1707)
Setup: 
- Build and run containerized stack: `agora-build-images && nx run agora-apex:serve-detach`
- Remove app container: `docker rm -f agora-app`
- Start app with dev server: `nx run agora-app:serve`
- View homepage at https://localhost:4200
Validate app can fetch data from API: 
- data version and file id should be displayed in footer, e.g. something like this: 
- …
> feat(agora): configure agora-app dev server proxy to handle agora-api requests (AG-1707)

- apps/agora/app/src/app/myPrimeNGPreset.ts
- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-how-to-panel/gene-comparison-tool-how-to-panel.component.html
- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-how-to-panel/gene-comparison-tool-how-to-panel.component.ts
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.html
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.scss
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.ts
- libs/agora/genes/src/lib/components/download-dom-image/download-dom-image.component.html
- libs/agora/genes/src/lib/components/download-dom-image/download-dom-image.component.scss
- libs/agora/genes/src/lib/components/gene-details/gene-details.component.html
- libs/agora/genes/src/lib/components/gene-details/gene-details.component.ts
- libs/agora/genes/src/lib/components/gene-model-selector/gene-model-selector.component.html
- libs/agora/genes/src/lib/components/gene-model-selector/gene-model-selector.component.ts
- libs/agora/genes/src/lib/components/gene-protein-selector/gene-protein-selector.component.html
- libs/agora/genes/src/lib/components/gene-protein-selector/gene-protein-selector.component.ts
- libs/agora/shared/src/lib/modal-link/modal-link.component.scss
- libs/agora/styles/src/lib/components/_dropdown.scss
- libs/agora/styles/src/lib/components/_radio.scss
- libs/agora/styles/src/lib/components/_typography.scss
We recently transitioned to using PrimeNG to v19 and a preset theme, which broke some existing styling. 
- [AG-1658](https://sagebionetworks.jira.com/browse/AG-1658)
- [AG-1701](https://sagebionetworks.jira.com/browse/AG-1701)
- Floats download button and modal-link to the right
- Converts p-dropdown to p-select and updates styles accordingly
- Updates p-select preset style to remove focus style to match current dev style
- Makes dropdowns on gene RNA and protein evidence pages full width
- Fixes font awesome icon imports
- Rounds GCT buttons
page | change | current dev | new dev | fix
:---:|:---:|:---:|:---:|:---:
GCT help | font awesome icon | <img width="621" alt="gct_help_currentdev" src="https://github.com/user-attachments/assets/88c4b596-4bf0-49c3-b21f-2beaea86a63f" /> | <img …
> fix(agora): float download button and modal-link right (AG-1658), round buttons (AG-1701), fix icons, style dropdowns

- .github/workflows/e2e-agora.yaml
- .github/workflows/sonar-scan-pull-request.yml
Workflows that are triggered by `pull_request_target` are failing (see [here](https://github.com/Sage-Bionetworks/sage-monorepo/actions/runs/13727614427/job/38397544419?pr=3027)) due to an error in `nrwl/nx-set-shas@v4.3.0` (see nrwl/nx-set-shas#186). For now, we will pin the action to the previous version of `nrwl/nx-set-shas`.
> fix(common): pin nrwl/nx-set-shas to v4.2.1

- apps/iatlas/data/README.md
- apps/iatlas/data/project.json
- apps/iatlas/postgres/README.md
Closes [ARCH-380](https://sagebionetworks.jira.com/browse/ARCH-380)
- Add the task `iatlas-data:serve-detach` and `iatlas-data:serve`.
- Update the READMEs of `iatlas-data` and `iatlas-postgres`.
The tasks `iatlas-data:serve-detach` and `iatlas-data:serve` have not been tested yet due to their long execution time. @andrewelamb will test them separately as part of a dedicated effort.
[ARCH-380]: https://sagebionetworks.jira.com/browse/ARCH-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(iatlas): add the task `iatlas-data:serve-detach` and update docs (ARCH-380)

- .devcontainer/devcontainer.json
- apps/iatlas/api/Dockerfile
- apps/iatlas/api/README.md
- apps/iatlas/data/README.md
- apps/iatlas/data/docker-entrypoint.sh
- apps/iatlas/postgres/README.md
- docker/iatlas/services/api.yml
Closes https://sagebionetworks.jira.com/browse/ARCH-381
- Update the Dockerfile to build uWSGI and add it to the PATH.
- Update the `docker-entrypoint.sh` to support `uwsgi` commands.
- Update the README of the project `iatlas-api`.
- Update `iatlas-api` container and the dev container to forward to port 2000 instead of 5000.
Build the Docker images:
```console
iatlas-build-images
```
Start the database and GraphQL API containers:
```console
nx serve-detach iatlas-api
```
Navigate to `http://localhost:2000/graphiql` and enter the following query in the GraphQL Playground:
```graphql
{
__schema {
queryType {
name
}
}
}
```
- VS Code was forwarding to port 5001 instead of 5000 for unknown reason (reserved port?). An quick solution to have the dev container forward to the same port as the …
> fix(iatlas): migrate iAtlas API Dockerfile to uv (ARCH-381)

- apps/agora/app/src/app/myPrimeNGPreset.ts
- libs/agora/charts/src/lib/score-barchart/score-barchart.component.scss
- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-details-panel/gene-comparison-tool-details-panel.component.html
- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-details-panel/gene-comparison-tool-details-panel.component.scss
- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-details-panel/gene-comparison-tool-details-panel.component.ts
- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-filter-panel/gene-comparison-tool-filter-panel.component.scss
- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-score-panel/gene-comparison-tool-score-panel.component.html
- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-score-panel/gene-comparison-tool-score-panel.component.scss
- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-score-panel/gene-comparison-tool-score-panel.component.ts
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.html
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.scss
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.ts
- libs/agora/genes/src/lib/components/download-dom-image/download-dom-image.component.html
- libs/agora/genes/src/lib/components/download-dom-image/download-dom-image.component.scss
- libs/agora/genes/src/lib/components/download-dom-image/download-dom-image.component.ts
- libs/agora/genes/src/lib/components/popover-link/popover-link.component.html
- libs/agora/genes/src/lib/components/popover-link/popover-link.component.scss
- libs/agora/styles/src/lib/components/_shame.scss
We recently updated to PrimeNG v19 from v17. There were a number of changes to the component names and style classes from v17 to v18+, see [here](https://primeng.org/guides/migration). The `OverlayPanel` component was renamed `Popover`. This PR updates all Agora components to use `Popover` instead of `OverlayPanel`.
- [AG-1703](https://sagebionetworks.jira.com/browse/AG-1703)
- Migrates all Agora components to use `Popover` instead of `OverlayPanel`
- Moves global popover styles into preset or colocate with targeted component
- Updates SASS files to use `@use` rather than [deprecated `@import`](https://sass-lang.com/blog/import-is-deprecated/)
component | currentdev | newdev | fix
:---:|:---:|:---:|:---:
download dom image | <img width="323" alt="currentdev_downloaddomimage" …
> fix(agora):  migrate primeng overlaypanel to popover (AG-1703)

- apps/agora/app/e2e/gene-details.spec.ts
- apps/agora/app/e2e/nominated-targets.spec.ts
- apps/agora/app/src/app/app.config.ts
- apps/agora/app/src/app/app.custom-uri-serializer.ts
Current Agora redirects legacy URLs to their current URLs. The migrated Agora app should replicate this behavior.
- [AG-1712](https://sagebionetworks.jira.com/browse/AG-1712)
- Add [CustomUrlSerializer](https://github.com/Sage-Bionetworks/Agora/blob/develop/src/app/app.custom-uri-serializer.ts) from current Agora to strip parentheses from legacy URLs
- Add e2e tests to confirm that redirect works as expected
Build and run agora: `agora-build-images && nx serve-detach agora-apex`
Navigate to legacy URLs and see that you are redirected: 
http://localhost:8000/genes/(genes-router:genes-list)  -> http://localhost:8000/genes/nominated-targets
https://github.com/user-attachments/assets/6fa773a4-0a9f-4939-851e-597ac8fc2263
http://localhost:8000/genes/(genes-router:gene-details/ENSG00000135940) …
> fix(agora): handle legacy page URLs (AG-1712)

- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.html
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.scss
We need to update the GCT paginator styling to match the current dev site after the PrimeNG update.
- [AG-1700](https://sagebionetworks.jira.com/browse/AG-1700)
Build and serve agora: `agora-build-images && nx serve-detach agora-apex`
Navigate to GCT via home page
View paginator: 
current dev | new dev | fix
:---:|:---:|:---:
[AG-1700]: https://sagebionetworks.jira.com/browse/AG-1700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(agora): fix GCT paginator styling (AG-1700)

- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.ts
The current Agora shows a loading screen when loading new GCT data, whereas the new Agora continues showing the site header while the data loads. However, the row of pinned genes data is displayed while the new data loads. This PR resets the pinned genes table so that only the loader is displayed while new data loads.
- [AG-1727](https://sagebionetworks.jira.com/browse/AG-1727)
Build and serve agora: `agora-build-images && nx serve-detach agora-apex`
Navigate to GCT
Pin a gene, then change the model
New agora:
https://github.com/user-attachments/assets/875b9119-37ec-4779-8a4a-32d84ac5ae06
Fix:
https://github.com/user-attachments/assets/dc12b7ec-71b4-48f0-bd82-aa7fda4c36ba
[AG-1727]: https://sagebionetworks.jira.com/browse/AG-1727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> fix(agora): reset GCT pinned genes when loading new data (AG-1727)

- apps/openchallenges/app/src/app/app.config.ts
- libs/openchallenges/challenge-search/src/lib/challenge-search.component.html
- libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts
- Migrate PrimeNG's calendar to datePicker
```
Old names are deprecated but still functional, migrate to new import paths instead e.g. primeng/calendar becomes primeng/datepicker.
Calendar -> DatePicker.
```
> fix(openchallenges): migrate primeng calendar to datepicker [SMR-31]

- .gitignore
- .vscode/extensions.json
Closes https://sagebionetworks.jira.com/browse/SMR-36
- Remove `extensions.json`.
- Configure Git to no longer track `extensions.json`.
> chore: remove VS Code extensions.json from Git tracking (SMR-36)

- apps/agora/app/src/app/myPrimeNGPreset.ts
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.scss
Small changes to align styling of GCT with current Agora.
- [AG-1651](https://sagebionetworks.jira.com/browse/AG-1651)
- Remove unwanted scrollbars
- Remove header bar background color 
- Align search input with header bar
current dev | new dev | fix 
:---:|:---:|:---:
[AG-1651]: https://sagebionetworks.jira.com/browse/AG-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(agora): remove horizontal scroll bars on table, align styling with current GCT (AG-1651)

- libs/agora/genes/src/lib/components/gene-table/gene-table.component.html
- libs/agora/genes/src/lib/components/gene-table/gene-table.component.ts
- libs/agora/util/src/index.ts
- libs/agora/util/src/lib/pipes/capitalize-boolean.pipe.ts
- libs/agora/util/src/lib/pipes/capitalize.pipe.ts
This PR standardizes the display of boolean values that use the shared component gene-table to capitalize the first letter of boolean values.  To accomplish this a custom pipe was created as the value may be a boolean or a string.  Some columns are booleans and some are tri-state (true, false or 'No data').
The shared component is used on the /genes/{gene}/similar and /genes/nominated-targets routes.
Both were tested for issues.
Before:
After:
> fix(agora): standardizing display of true and false values (AG-1665)

- .github/ISSUE_TEMPLATE/1-bug.yml
- .github/ISSUE_TEMPLATE/2-feature.yml
- .github/ISSUE_TEMPLATE/3-documentation.yml
- .github/ISSUE_TEMPLATE/4-story.yml
- .github/workflows/lint-pr.yml
- .github/workflows/release.yml
- dev-env.sh
- Update GitHub workflows to support the AMP-ALS product.
- Add "AMP-ALS" to the list of products in GitHub issue templates.
- Add the command `amp-als-build-images`.
> chore: configure the monorepo to support the AMP-ALS product

- .devcontainer/devcontainer.json
- apps/amp-als/elasticsearch/Dockerfile
- apps/amp-als/elasticsearch/docker-healthcheck
- apps/amp-als/elasticsearch/project.json
- apps/amp-als/mariadb/docker-healthcheck
- docker/amp-als/serve-detach.sh
- docker/amp-als/services/elasticsearch.yml
- docker/amp-als/services/mariadb.yml
- tools/configure-hostnames.sh
Closes https://sagebionetworks.jira.com/browse/SMR-40
Create the `amp-als-elasticsearch` project based on the existing `openchallenges-elasticsearch` project. This Elasticsearch instance will support integration with the upcoming Dataset service. If the project evolves further, we anticipate migrating to the latest version of OpenSearch.
- Create the project `amp-als-elasticsearch`.
- Setup Docker Compose to deploy `amp-als-elasticsearch`.
- Configure Elasticsearch to listen to port 8402 (internal container port and host-mapped port).
- Publish the Docker image `ghcr.io/sage-bionetworks/amp-als-elasticsearch:{edge,sha-xxxxxxx}`.
- Add the hostnames `amp-als-{mariadb,elasticsearch}` to `tools/configure-hostnames.sh`.
- Configure `amp-als-mariadb` to listen to port 8401.
- Forward the dev …
> feat(amp-als): add Elasticsearch and update MariaDB port

- .vscode/settings.json
Closes https://sagebionetworks.jira.com/browse/SMR-41
Add SQLTools connection profile for AMP-ALS MariaDB instance.
> chore: add SQLTools connection profile for AMP-ALS MariaDB instance (SMR-41)

- apps/agora/app/e2e/gene-comparison-tool.spec.ts
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.ts
When searching for a gene in the GCT, the full list of genes should not be shown after entering a comma. Note: the newly added e2e test will not run until #3041 is merged.
- [AG-1704](https://sagebionetworks.jira.com/browse/AG-1704)
https://github.com/user-attachments/assets/03577410-a571-4ab9-800f-6c0a2b9a7d55
[AG-1704]: https://sagebionetworks.jira.com/browse/AG-1704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(agora): entering a comma in search does not show all genes (AG-1704)

- .github/workflows/scan-images.yml
- .github/workflows/scan-repo.yml
`Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101.`
- [SMR-47](https://sagebionetworks.jira.com/browse/SMR-47)
[SMR-47]: https://sagebionetworks.jira.com/browse/SMR-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(sage): upgrade to latest GHA-hosted runner (SMR-47)

- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/api/DatasetApi.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/api/DatasetApiDelegate.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/api/DatasetApiDelegateImpl.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/exception/DatasetNotFoundException.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/exception/ErrorConstants.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/exception/SimpleDatasetGlobalException.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/entity/DatasetEntity.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/mapper/DatasetMapper.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/repository/DatasetRepository.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/service/DatasetService.java
Closes https://sagebionetworks.jira.com/browse/SMR-49
- Implement the endpoint to get dataset by ID.
Before this PR:
```console
$ curl -X 'GET' \
'http://amp-als-apex:8400/api/v1/datasets/1' \
-H 'accept: application/json' \
-w "\nHTTP status: %{http_code}\n"
HTTP status: 501
```
With this PR:
```console
$ curl -X 'GET' \
'http://amp-als-apex:8400/api/v1/datasets/1' \
-H 'accept: application/json
{"id":1,"name":"Mock Dataset 1","description":"Clinical data from patients with cardiovascular conditions","createdAt":"2025-04-01T23:08:59Z","updatedAt":"2025-04-01T23:08:59Z"}
```
Using Swagger UI:
> feat(amp-als): update the AMP-ALS dataset service to return datasets by ID (SMR-49)

- apps/amp-als/dataset-service/build.gradle
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/configuration/HibernateSearchIndexBuild.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/entity/DatasetEntity.java
- apps/amp-als/dataset-service/src/main/resources/application.yml
- docker/amp-als/services/dataset-service.yml
- docker/amp-als/services/elasticsearch.yml
Closes https://sagebionetworks.jira.com/browse/SMR-46
- Index the name, description and creation date of datasets in Elasticsearch.
- Organize dependencies in `build.gradle`.
- Update the configuration of Elasticsearch for single node setup.
```bash
amp-als-build-images
```
```bash
nx serve-detach amp-als-dataset-service
```
Stop and remove the container if you prefer to start the development server of the dataset service. This is preferred for development to benefit from live reloading.
```bash
docker rm -f amp-als-dataset-service
```
```bash
nx serve amp-als-dataset-service
```
```console
$ curl -X GET "http://amp-als-elasticsearch:8402/_cat/indices?v"
health status index                  uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open …
```
> feat(amp-als): index datasets in Elasticsearch on AMP-ALS dataset service startup (SMR-46)

- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/DatasetServiceApplication.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/api/DatasetApiDelegateImpl.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/configuration/FlywayConfiguration.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/exception/BadRequestException.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/repository/CustomDatasetRepository.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/repository/CustomDatasetRepositoryImpl.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/repository/DatasetRepository.java
- apps/amp-als/dataset-service/src/main/java/org/sagebionetworks/amp/als/dataset/service/service/DatasetService.java
Closes https://sagebionetworks.jira.com/browse/SMR-50
- List datasets with full-text search and sorting powered by Hibernate Search and Elasticsearch.
- Support paginated responses (`pageSize` and `pageNumber`).
- Sort results with different strategies (`created`, `random`, `relevance`).
- Order the results in ascending or descending order (`asc` and `desc`).
- Full-test search (`searchTerms`).
- Search for the keyword "clinical"
- Sort the results 1) by their creation date and time and 2) in ascending order.
- Set the page size to 10.
- Request the first page (page number 0).
```console
$ curl -X 'GET' \
'http://localhost:8404/v1/datasets?pageNumber=0&pageSize=10&sort=created&direction=asc&searchTerms=clinical' \
-H 'accept: application/json' …
```
> feat(amp-als): implements listDatasets endpoint with full-text search and sorting powered by Elasticsearch (SMR-50)

- apps/agora/app/e2e/gene-comparison-tool-pinning-cache.spec.ts
- apps/agora/app/e2e/gene-comparison-tool-pinning-url.spec.ts
- apps/agora/app/e2e/gene-comparison-tool.spec.ts
- apps/agora/app/e2e/gene-details.spec.ts
- apps/agora/app/src/app/app.config.ts
- libs/agora/gene-comparison-tool/src/lib/gene-comparison-tool.component.ts
- libs/agora/genes/src/lib/components/gene-details/gene-details.component.ts
- libs/agora/genes/src/lib/components/gene-model-selector/gene-model-selector.component.ts
- libs/agora/genes/src/lib/components/gene-similar/gene-similar.component.ts
We recently updated Agora to use `@Input` to bind route information to components (#3042), but ran into a number of issues (see #3075). We need to create additional tests to capture the expected functionality related to URL/route handling in the GCT and Gene Details components to prevent unexpected regressions before attempting the refactor recommended in [AG-1713](https://sagebionetworks.jira.com/browse/AG-1713). For now, we will revert to using `ActivatedRoute` in GCT and Gene Details components.
- [AG-1713](https://sagebionetworks.jira.com/browse/AG-1713)
- [AG-1739](https://sagebionetworks.jira.com/browse/AG-1739)
- [AG-1745](https://sagebionetworks.jira.com/browse/AG-1745)
- Reverts changes from #3042 to GCT and GeneDetails components, but keeps `MetaTagService`
- Adds e2e test for …
> fix(agora): revert changes from AG-1713 related to @Input, keep MetaTagService, add e2e tests

- apps/agora/app/src/test-setup.ts
- apps/model-ad/app/src/test-setup.ts
- apps/openchallenges/app/src/test-setup.ts
- apps/sandbox/angular-app/src/test-setup.ts
- libs/sandbox/angular-lib/src/test-setup.ts
Setting `testEnvironmentOptions` via `globalThis.ngJest` has been deprecated, so we should provide `testEnvironmentOptions` via `setupZoneTestEnv` instead. 
- [SMR-56](https://sagebionetworks.jira.com/browse/SMR-56)
- Provide `testEnvironmentOptions` via `setupZoneTestEnv`.
[SMR-56]: https://sagebionetworks.jira.com/browse/SMR-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(sage): provide testEnvironmentOptions via setupZoneTestEnv (SMR-56)

- libs/agora/styles/src/lib/components/_table.scss
Fixes the header row formatting and table height of the gene tables (nominated targets, similar genes).
- [AG-1743](https://sagebionetworks.jira.com/browse/AG-1743) 
path | current dev | new dev | fix
:---:|:---:|:---:|:---:
similar genes |  <img width="1759" alt="currentdev_similar_genes" src="https://github.com/user-attachments/assets/aa52fc94-8838-42ab-a0c0-81211af9bc7a" /> | <img width="1770" alt="newdev_similar_genes" src="https://github.com/user-attachments/assets/78bada2d-7c61-465f-b9d8-c58548320586" /> | <img width="1763" alt="fix_similar_genes" src="https://github.com/user-attachments/assets/f1e28326-a309-4ebc-ae9c-30b8117e0def" />
nominated targets | <img width="1655" alt="currentdev_nominated_targets" src="https://github.com/user-attachments/assets/4e29d1db-0435-4616-a6c0-3c3b94 …
> fix(agora): fix gene-table column header row formatting and height (AG-1743)

- libs/agora/gene-comparison-tool/src/lib/components/gene-comparison-tool-filter-list/gene-comparison-tool-filter-list.component.html
Fixes a bug where removing a chiclet filter did not update the GCT.
- [AG-1750](https://sagebionetworks.jira.com/browse/AG-1750)
https://github.com/user-attachments/assets/c03552b7-65f1-4bb1-bc8b-481ba71b2b31
[AG-1750]: https://sagebionetworks.jira.com/browse/AG-1750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(agora): removing chiclet updates GCT (AG-1750)

- apps/amp-als/dataset-service-next/Dockerfile
- apps/amp-als/dataset-service-next/build.gradle.kts
- docker/amp-als/serve-detach.sh
- docker/amp-als/services/dataset-service-next.yml
- libs/sage-monorepo/nx-plugin/src/plugins/project-metadata.ts
Closes https://sagebionetworks.jira.com/browse/SMR-63
The Docker image is built in two stages:
1. Using Paketo to create a lean and secure image.
2. Using an Nx Docker plugin to manage image tagging more effectively.
A current limitation is that images built with the latest version of Paketo do not include a shell (e.g., sh) or a package manager. This design choice helps minimize the attack surface but prevents us from easily installing tools like `curl` and `jq`, which are typically used for health check commands in Spring Boot 2 applications.
For now, I’ve chosen to align with Paketo’s philosophy and omit a `HEALTHCHECK` instruction from the Docker image. We can revisit this decision if it becomes a problem in the future.
- Dockerize the project `amp-als-dataset-service-next`.
- Update …
> feat(amp-als): dockerize the Spring Boot 3 stub for AMP-ALS dataset service (SMR-63)

- apps/amp-als/dataset-service-next/.openapi-generator/FILES
- apps/amp-als/dataset-service-next/build.gradle.kts
- apps/amp-als/dataset-service-next/gradle/libs.versions.toml
- apps/amp-als/dataset-service-next/openapitools.json
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/api/DatasetApiDelegateImpl.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/configuration/SecurityConfiguration.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/exception/BadRequestException.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/exception/DatasetNotFoundException.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/exception/ErrorConstants.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/exception/SimpleDatasetGlobalException.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/dto/BasicErrorDto.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/dto/DatasetDto.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/dto/DatasetSearchQueryDto.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/dto/DatasetsPageDto.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/dto/PageMetadataDto.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/mapper/DatasetMapper.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/repository/CustomDatasetRepository.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/repository/CustomDatasetRepositoryImpl.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/model/repository/DatasetRepository.java
- apps/amp-als/dataset-service-next/src/main/java/org/sagebionetworks/amp/als/dataset/service/service/DatasetService.java
Closes https://sagebionetworks.jira.com/browse/SMR-65
- Copy the logic of `amp-als-dataset-service` (Spring Boot 2) to `amp-als-dataset-service-next`.
- Adapt Security Configuration for Spring Boot 3.
> [!TIP]
> Builders were previously added to DTOs using custom template and Lombok. It is now possible to generate builders by settings the OpenAPI generator option `generateBuilders` to `true`.
```bash
curl -X 'GET' \
'http://localhost:8404/v1/datasets?pageNumber=0&pageSize=10&sort=created&sortSeed=2147483647&direction=asc&searchTerms=clinical' \
-H 'accept: application/json' | jq
```
Output:
```json
{
"number": 0,
"size": 10,
"totalElements": 2,
"datasets": [
{
"id": 3,
"name": "Mock Dataset 3",
"description": "Registry of patients …
```
> feat(amp-als): migrate AMP-ALS dataset service logic from Spring Boot 2 to 3 (SMR-65)

- apps/agora/api/src/components/comparison.ts
- libs/agora/api-client-angular/src/lib/model/targetNomination.ts
- libs/agora/api-description/build/openapi.yaml
- libs/agora/api-description/src/components/schemas/TargetNomination.yaml
We would like to remove the duplicate values displayed for the Experimental Validation filter in the GCT.
- [AG-1758](https://sagebionetworks.jira.com/browse/AG-1758)
- Update API to specify that `validation_study_details` is a nullable field
- Clean `validation_study_details` values before adding to set of available filters
Confirmed that `validation_study_details` is a nullable field with this query:  
```
agora> db.geneinfo.countDocuments({  $or: [    { "target_nominations.validation_study_details": null },    { "target_nominations.validation_study_details": { $exists: false } }  ]})
35036
```
Experimental Validation filters have been updated: 
current dev | fix
:---:|:---:
And applying the single filter vs combination of filters that differ only in whitespace or capitalization results …
> fix(agora): fix duplicate experimental validation filter values (AG-1758)

- .github/CODEOWNERS
Updates `model-ad` codeowners to the `@Sage-Bionetworks/sage-monorepo-agora` team.
> chore(model-ad): update model-ad codeowners

- libs/model-ad/home/src/lib/home.component.spec.ts
- libs/model-ad/home/src/test-setup.ts
- libs/model-ad/not-found/src/lib/not-found.component.spec.ts
- libs/model-ad/not-found/src/test-setup.ts
- libs/model-ad/ui/src/lib/footer/footer.component.spec.ts
- libs/model-ad/ui/src/lib/header/header.component.spec.ts
- libs/model-ad/ui/src/test-setup.ts
Use [`@testing-library/angular`](https://testing-library.com/docs/angular-testing-library/intro/) for `model-ad` tests.
- [MG-81](https://sagebionetworks.jira.com/browse/MG-81)
- Converts `model-ad` tests to use `@testing-library/angular`
Run all `model-ad` tests: 
```
$ nx run-many --target=test --projects=model-ad-* --skip-nx-cache
NX   The following projects do not have a configuration for any of the provided targets ("test")
- model-ad-api-description
- model-ad-api-docs
- model-ad-styles
- model-ad-themes
- model-ad-mongo
- model-ad-apex
✔  nx run shared-java-util:build (4s)
✔  nx run model-ad-config:test (4s)
✔  nx run shared-java-util:install (3s)
✔  nx run model-ad-util:test (4s)
✔  nx run model-ad-api-client-angular:test (5s)
✔  nx run model-ad-ui:test (16s)
✔  nx run …
```
> feat(model-ad): use @testing-library/angular for model-ad unit tests (MG-81)

- .github/CODEOWNERS
- .github/workflows/lint-pr.yml
We recently added the `explorers` project to house components shared between `agora` and `model-ad`. This PR sets the `@Sage-Bionetworks/sage-monorepo-agora` team as the CODEOWNER for `explorers` and adds `explorers` as a valid PR scope, so we can use `explorers` as a PR title when the changes are specific to these shared components.
> chore(sage): update explorers codeowners and add explorers to pr scope

- libs/openchallenges/api-client-angular/project.json
Remove a remainder that is no longer needed after updating to OpenAPI Generator v7.11.0.
> chore(openchallenges): remove the remainder about updating `*JsonLd.ts` models

- libs/synapse/api-client-angular/project.json
The paths in `synapse/api-client-angular` incorrectly point at the `openchallenges` project, so the build is failing since #3135 removed `ng-package.json` from `openchallenges`. This PR corrects the `synapse/api-client-angular` paths.
> fix(synapse): fix synapse-api-client-angular build

- apps/openchallenges/mcp-server/Dockerfile
- apps/openchallenges/mcp-server/build.gradle.kts
- apps/openchallenges/mcp-server/project.json
- docker/openchallenges/serve-detach.sh
- docker/openchallenges/services/apex.yml
- docker/openchallenges/services/mcp-server.yml
- closes https://sagebionetworks.jira.com/browse/SMR-101
- closes https://sagebionetworks.jira.com/browse/SMR-108
- containerize the OC MCP server
Build the Docker image of MCP Server
```console
nx build-image openchallenges-mcp-server
```
Start the MCP Server container in detach mode
```console
nx serve-detach openchallenges-mcp-server
> nx run openchallenges-mcp-server:serve-detach
> docker/openchallenges/serve-detach.sh openchallenges-mcp-server
[+] Running 8/8
✔ Network openchallenges                      Created                                                                                        0.1s 
✔ Container openchallenges-config-server      Healthy                                                                                       21.3s 
✔ Container …
```
> feat(openchallenges): containerize the OC MCP Server (SMR-101, SMR-108)

- .github/.devcontainer/devcontainer.json
- Contributes to https://sagebionetworks.jira.com/browse/SMR-111
```console
ubuntu@ea7541c96628:/$ sdk list java | grep installed
|     | 21.0.7       | graal   | installed  | 21.0.7-graal        
Microsoft     | >>> | 21.0.7       | ms      | installed  | 21.0.7-ms
```
> chore(sage-monorepo): update JDK ms distrib and install GraalVM-enabled distrib

- .vscode/settings.json
- checkstyle-suppressions.xml
- checkstyle.xml
- https://sagebionetworks.jira.com/browse/SMR-123
- Update the Checkstyle version in `.vscode/settings.json`.
- Replace `checkstyle.xml` with the [latest version from Google](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml).
- Suppress the Checkstyle warning about incorrect indent.
- Java developers
> chore(sage-monorepo): update Checkstyle and disable incorrect indentation level warnings (SMR-123)

- .github/.devcontainer/Dockerfile
Add musl system packages to the dev container to build statically linked binaries such as the native images build with GraalVM.
- Contributes to https://sagebionetworks.jira.com/browse/SMR-113
- Add musl dev system libraries to the dev container.
- Build zlib with musl from source and place it where GraalVM's `native-image` builder will find it.
> chore(sage-monorepo): add musl to the dev container (SMR-113)

- apps/openchallenges/mcp-server/Dockerfile
- apps/openchallenges/mcp-server/build.gradle.kts
- apps/openchallenges/mcp-server/gradle/libs.versions.toml
- apps/openchallenges/mcp-server/project.json
- apps/openchallenges/mcp-server/src/main/java/org/sagebionetworks/openchallenges/mcp/server/ChallengeAnalyticsService.java
- apps/openchallenges/mcp-server/src/main/java/org/sagebionetworks/openchallenges/mcp/server/ChallengesPerYear.java
- apps/openchallenges/mcp-server/src/main/java/org/sagebionetworks/openchallenges/mcp/server/config/OpenChallengesApiClientConfig.java
- apps/openchallenges/mcp-server/src/main/java/org/sagebionetworks/openchallenges/mcp/server/config/ReflectionHintsConfig.java
This PR uses the new Java API client for OC generated with OpenAPI Generator to fetch data for an MCP tool.
- Closes https://sagebionetworks.jira.com/browse/SMR-104
- Update `openchallenges-mcp-server:build` to build the native image with GraalVM.
- Update `openchallenges-mcp-server:build-image` to package the native image generated by the `build` task.
- Import the Java API client for OC into the MCP server project.
- Use the Java API client for OC to fetch data from the OC challenge analytics data endpoint.
> refactor(openchallenges): integrate the Java API client for OC into the MCP server (SMR-104)

- libs/sage-monorepo/nx-plugin/src/plugins/build-image-target.ts
- https://sagebionetworks.jira.com/browse/SMR-126
The task `build-image` now depends on the task `build` in addition to `build-image-base`.
```bash
nx show project openchallenges-mcp-server
```
> [!NOTE]
> Technically, we have two types of projects: 1) built with JVM and 2) built with GraalVM. The former tasks need to run `build-image-base` only. the latter tasks need to run `build` only. There is currently a bit of wasted resources for the former type of projects. The latter projects do not waste resources because they don't implement `build-image-base`. The efficiency will be improved in a future PR. This PR aims to fix a broken chain of dependencies so that developers can continue to contribute.
> fix(sage-monorepo): run the `build` task before `build-image` for Java projects built with GraalVM (SMR-126)

- apps/openchallenges/mcp-server/gradle/libs.versions.toml
- apps/openchallenges/mcp-server/src/main/java/org/sagebionetworks/openchallenges/mcp/server/McpServerApplication.java
- Rename `tools` by `toolCallbacks` as documented in the M8 release notes (see References).
- https://github.com/spring-projects/spring-ai/tags
- https://spring.io/blog/2025/04/30/spring-ai-1-0-0-m8-released
> chore(openchallenges): update to Spring AI 1.0.0 M8

- apps/openchallenges/mcp-server/Dockerfile
- apps/openchallenges/mcp-server/build.gradle.kts
- apps/openchallenges/mcp-server/project.json
- libs/sage-monorepo/nx-plugin/src/plugins/build-image-target.ts
The goal of this PR is to revert to building the OC MCP server for JVM, for which building a Docker image is much faster than building it with GraalVM for optimizing the cold start of the server. This change is motivated by the fact the deployment of the MCP server to production is delayed as the server is still too early in its development phase.
By then, I'm hoping to find a way so that the developer don't have to build the server with GraalVM when deploying the app with Docker Compose inside the development environment. Instead, the MCP server should be built and tested with GraalVM by the CI/CD workflow.
- Revert back to the standard way to build Docker images for Gradle projects.
- Remove the dependency of `build-image` on `build` for Java projects.
> refactor(openchallenges): revert to building MCP server for JVM to improve DevEx

- .devcontainer/devcontainer.json
This PR adds the official VS Code extension for Caddy files.
- Prevent the issue described in the related ticket.
- Provides syntax highlight and intellisense.
- Closes https://sagebionetworks.jira.com/browse/SMR-128
> chore(sage-monorepo): add VS Code extension for Caddyfiles

- .eslintrc.json
Update the global ESLint configuration to warn where new Angular control flow should be used.
To see the warnings, the developers must run the `lint` tasks on their projects, e.g.:
```bash
nx run-many --target=lint --projects=agora-*
```
> [!NOTE]
> `lint-staged` lints the affected projects when committing code. `lint-staged` does not show the warning messages from the linter but will show the errors. Moreover, note that only the affected projects are linted by `lint-staged`. To lint all the Agora projects, e.g., run the command provide above.
- https://sagebionetworks.jira.com/browse/SMR-136
> chore(sage-monorepo): warn where new Angular control flow should be used

- .devcontainer/devcontainer.json
- libs/amp-als/api-description/project.json
- libs/model-ad/api-description/project.json
- libs/openchallenges/api-description/project.json
- libs/synapse/api-description/project.json
- redocly.yaml
- Closes https://sagebionetworks.jira.com/browse/SMR-130
- Add the VS Code extension Redocly OpenAPI to the dev container.
- Move the Redocly configuration to the workspace folder where the extension can find it.
The OpenAPI description files are not interactive.
Hints on how to fix validation warnings are shown upon placing the pointer over them.
On Mac: **Hold Command + move the pointer over a reference** to show its preview in a tooltip.
On Mac: **Hold Command + click on a reference** to open its definition.
Alternatively, **right-click a reference** and select **Peek** > **Peek Definition** to view and edit the definition directly within the current YAML file. No need to open it in a separate file.
> feat(sage-monorepo): add VS Code extension for Redolcy OpenAPI

- apps/openchallenges/mcp-server/.env.example
- apps/openchallenges/mcp-server/build.gradle.kts
- apps/openchallenges/mcp-server/gradle/libs.versions.toml
- apps/openchallenges/mcp-server/src/main/java/org/sagebionetworks/openchallenges/mcp/server/McpServerApplication.java
- apps/openchallenges/mcp-server/src/main/java/org/sagebionetworks/openchallenges/mcp/server/config/McpServerConfigData.java
- apps/openchallenges/mcp-server/src/main/java/org/sagebionetworks/openchallenges/mcp/server/config/OpenChallengesApiClientConfig.java
- apps/openchallenges/mcp-server/src/main/resources/application.yml
closes https://sagebionetworks.jira.com/browse/SMR-112
- Config API base url via the environment variable for `openchallenges-mcp-server`
- Add a welcome message for `openchallenges-mcp-server`
I tested three configuration binding approaches below in the `application.yml`, while keeping `.env` file with snake-cased variables (e.g., `WELCOME_MESSAGE`):
- Dotted case - [9dc4990](https://github.com/Sage-Bionetworks/sage-monorepo/pull/3180/commits/9dc499001afcdf071c7e2373fad60c33906914be)
- Kebab case - [11032ad](https://github.com/Sage-Bionetworks/sage-monorepo/pull/3180/commits/11032ad7aea1d7a9cb7c780f1c1b6d717704f07d)
- Camel case - [2d9050f](https://github.com/Sage-Bionetworks/sage-monorepo/pull/3180/commits/2d9050fe30cf0f3838ae4c1ad00a23a1e5449b5e)
Selected approach is ~~**Camel case**~~ …
> feat(openchallenges): create project-specific config for the OC MCP server (SMR-112)

- docker/agora/serve-detach.sh
- docker/amp-als/serve-detach.sh
- docker/iatlas/serve-detach.sh
- docker/model-ad/serve-detach.sh
- docker/observability/serve-detach.sh
- docker/openchallenges/serve-detach.sh
- docker/openchallenges/serve.sh
- docker/sage/serve-detach.sh
- docker/sandbox/serve-detach.sh
- docker/sandbox/serve.sh
- docker/synapse/serve-detach.sh
- https://sagebionetworks.jira.com/browse/SMR-150
- Remove `--remove-orphans` from Docker Compose files.
- Add `--project-name {project-name}` to Docker Compose files.
- Parametrize the product name in Docker Compose files.
The containers will appeared grouped by product/stack name in the Containers Tool extension for VS Code:
Before this PR, starting a stack with `nx serve-detach` would stop any containers that had been started with `nx serve-detach`. For example:
```console
$ nx serve-detach observability-tempo
> nx run observability-tempo:serve-detach
> docker/observability/serve-detach.sh observability-tempo
[+] Running 7/7
✔ Container agora-mongo          Removed                                                                                                       1.0s 
✔ Container …
```
> feat(sage-monorepo): enable developers to start multiple stacks with Docker Compose (SMR-150)

- apps/agora/gene-api/src/main/java/org/sagebionetworks/agora/gene/api/service/GCTGenesService.java
- Replace two full scans by maps for fast O(1) lookups.
- Document the process of using profiling data in Grafana to optimize execution time in Java code.
The initial (quasi) rewrite of the Gene Comparison Tool (GCT) endpoint for RNA took 1.98 minutes to execute its main function `getComparisonGenes`. This is illustrated in the [flame graph](https://github.com/brendangregg/FlameGraph) below, which was captured using Pyroscope and visualized in Grafana.
A previous version of this view revealed that most of the execution time was spent in Java lambdas. Since several lambdas were used within the same function, Grafana displayed a generic name for their execution, making it difficult to correlate the profiling data with the specific Java stream calls. This issue can be resolved by extracting …
> docs(observability,agora): show how to use Profiles data in Grafana to streamline GCT endpoint implementation

- apps/observability/grafana/datasources/datasources.yml
- docker/observability/services/grafana.yml
Configure Grafana data sources for Loki, Tempo, Prometheus and Pyroscope in Grafana using a YAML config file.
- [SMR-156](https://sagebionetworks.jira.com/browse/SMR-156)
- Configure Grafana data sources using a YAML configuration file.
[SMR-156]: https://sagebionetworks.jira.com/browse/SMR-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Build and start the observability stack:
```bash
observability-build-images
observability-docker-start
```
2. In a browser, navigate to the Grafana web UI at http://localhost:8501.
3. Log in using the default credentials: admin / admin.
4. Click Skip to bypass setting new credentials.
5. In the left-hand menu, go to Connections > Data sources.
6. You should see data sources listed for Pyroscope, Loki, …
> feat(observability): configure Grafana data sources using a YAML configuration file (SMR-156)

- apps/agora/app/src/app/app.component.html
- apps/model-ad/app/src/app/app.component.html
- apps/model-ad/app/src/app/app.component.ts
- apps/model-ad/app/src/app/app.config.ts
- libs/explorers/comparison-tools/src/index.ts
- libs/explorers/comparison-tools/src/lib/comparison-tool-header/comparison-tool-filter-results-button/comparison-tool-filter-results-button.component.html
- libs/explorers/comparison-tools/src/lib/comparison-tool-header/comparison-tool-filter-results-button/comparison-tool-filter-results-button.component.ts
- libs/explorers/comparison-tools/src/lib/comparison-tool-header/comparison-tool-header.component.html
- libs/explorers/comparison-tools/src/lib/comparison-tool-header/comparison-tool-header.component.scss
- libs/explorers/comparison-tools/src/lib/comparison-tool-header/comparison-tool-header.component.ts
- libs/explorers/comparison-tools/src/lib/comparison-tool-header/comparison-tool-share-url-button/comparison-tool-share-url-button.component.html
- libs/explorers/comparison-tools/src/lib/comparison-tool-header/comparison-tool-share-url-button/comparison-tool-share-url-button.component.ts
- libs/explorers/comparison-tools/src/lib/help-links/help-links.component.scss
- libs/explorers/shared/src/lib/components/not-found/not-found.component.scss
- libs/explorers/shared/src/lib/components/wiki-hero/wiki-hero.component.scss
- libs/explorers/styles/src/index.scss
- libs/explorers/styles/src/lib/components/_tooltip.scss
- libs/model-ad/disease-correlation-comparison-tool/src/lib/disease-correlation-comparison-tool.component.html
- libs/model-ad/disease-correlation-comparison-tool/src/lib/disease-correlation-comparison-tool.component.scss
- libs/model-ad/disease-correlation-comparison-tool/src/lib/disease-correlation-comparison-tool.component.spec.ts
- libs/model-ad/disease-correlation-comparison-tool/src/lib/disease-correlation-comparison-tool.component.ts
- libs/model-ad/gene-expression-comparison-tool/src/lib/gene-expression-comparison-tool.component.html
- libs/model-ad/gene-expression-comparison-tool/src/lib/gene-expression-comparison-tool.component.scss
- libs/model-ad/gene-expression-comparison-tool/src/lib/gene-expression-comparison-tool.component.spec.ts
- libs/model-ad/gene-expression-comparison-tool/src/lib/gene-expression-comparison-tool.component.ts
- libs/model-ad/model-overview-comparison-tool/src/lib/model-overview-comparison-tool.component.html
- libs/model-ad/model-overview-comparison-tool/src/lib/model-overview-comparison-tool.component.scss
- libs/model-ad/model-overview-comparison-tool/src/lib/model-overview-comparison-tool.component.spec.ts
- libs/model-ad/model-overview-comparison-tool/src/lib/model-overview-comparison-tool.component.ts
- libs/model-ad/util/src/lib/navigation-links.ts
This adds a CT header component with a "Filter Results" button, header title and "Share URL" button.
[MG-245](https://sagebionetworks.jira.com/jira/software/c/projects/MG/boards/243?assignee=633b138697148a8301fe2c72&selectedIssue=MG-245)
- Filter Results button: (partial implementation) This button will be fully functional with [MG-246](https://sagebionetworks.jira.com/browse/MG-246).  This button will only show an alert at this time but otherwise should follow the design in Figma.
- Header Title is now part of the ComparisonToolHeaderComponent
- Share URL button: A button that creates a toast and copies the URL into the clipboard.
- Tooltips will show placeholder text but will be refined in a future update (pending).
- Fixed styling in not-found component (404) and wiki-hero component …
> feat(model-ad): adding comparison tool header component and buttons (MG-245)

- apps/model-ad/app/e2e/model-details.spec.ts
- apps/model-ad/app/playwright.config.ts
- apps/model-ad/app/src/app/app.routes.ts
- apps/model-ad/data/.env.example
- libs/explorers/models/src/index.ts
- libs/explorers/models/src/lib/panel.ts
- libs/explorers/services/src/index.ts
- libs/explorers/services/src/lib/helper.service.spec.ts
- libs/explorers/services/src/lib/helper.service.ts
- libs/explorers/styles/src/lib/_mixins.scss
- libs/explorers/ui/src/index.ts
- libs/explorers/ui/src/lib/components/panel-navigation/panel-navigation.component.html
- libs/explorers/ui/src/lib/components/panel-navigation/panel-navigation.component.scss
- libs/explorers/ui/src/lib/components/panel-navigation/panel-navigation.component.spec.ts
- libs/explorers/ui/src/lib/components/panel-navigation/panel-navigation.component.stories.ts
- libs/explorers/ui/src/lib/components/panel-navigation/panel-navigation.component.ts
- libs/model-ad/model-details/src/lib/model-details.component.html
- libs/model-ad/model-details/src/lib/model-details.component.scss
- libs/model-ad/model-details/src/lib/model-details.component.spec.ts
- libs/model-ad/model-details/src/lib/model-details.component.ts
- libs/model-ad/testing/src/lib/mocks/config-mocks.ts
- libs/model-ad/testing/src/lib/mocks/index.ts
- tsconfig.base.json
Updates model details to include panel navigation tabs.
- [MG-244](https://sagebionetworks.jira.com/browse/MG-244)
- Updates model details to include panel navigation tabs
- Adds shared panel navigation component, based on Agora's [gene-details component](https://github.com/Sage-Bionetworks/sage-monorepo/tree/main/libs/agora/genes/src/lib/components/gene-details)
- Adds shared helper service to support panel navigation component, based on Agora's [helper service](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/libs/agora/services/src/lib/helper.service.ts)
- Updates model-details routes to allow URLs with `:tab` and `:subtab` parameters
- Adds model details e2e tests
- Updates `model-ad-data`'s `.env.example` to use a newer data version
- Adds missing path for …
> feat(model-ad): add panel navigation tabs to model details (MG-244)

- apps/model-ad/app/e2e/model-details.spec.ts
- libs/explorers/styles/src/lib/_section.scss
- libs/explorers/styles/src/lib/_variables.scss
- libs/explorers/ui/src/lib/components/resource-card/resource-card.component.scss
- libs/model-ad/model-details/src/lib/components/model-details-omics/model-details-omics.component.scss
- libs/model-ad/model-details/src/lib/components/model-details-resources/model-details-resources.component.html
- libs/model-ad/model-details/src/lib/components/model-details-resources/model-details-resources.component.scss
- libs/model-ad/model-details/src/lib/components/model-details-resources/model-details-resources.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-resources/model-details-resources.component.ts
- libs/model-ad/model-details/src/lib/model-details.component.html
- libs/model-ad/model-details/src/lib/model-details.component.ts
Adds the resources panel content to the model details page.
- [MG-214](https://sagebionetworks.jira.com/browse/MG-214)
- Adds `model-details-resources` component
- Ensures that `resource-card`s in the same row have the same height
1. Build and run Model-AD: `model-ad-build-images && model-ad-docker-start`
2. Navigate to a model details page: http://localhost:8000/models/3xTg-AD/resources
[MG-214]: https://sagebionetworks.jira.com/browse/MG-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MG-214]: https://sagebionetworks.jira.com/browse/MG-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(model-ad): add model details resources panel content (MG-214)

- libs/model-ad/model-details/src/lib/components/model-details-resources/model-details-resources.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-resources/model-details-resources.component.ts
Some models do not have an `alzforum_id`. We should hide the corresponding resource card in this case.
- [MG-259](https://sagebionetworks.jira.com/browse/MG-259)
- Hides ALZFORUM resource card when id is missing
Run `model-ad-build-images && model-ad-docker-start`
Navigate to `http://localhost:8000/models/Abca7*V1599M/resources`
Alzforum card should not be shown: 
[MG-259]: https://sagebionetworks.jira.com/browse/MG-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(model-ad): hide alzforum resource card when id is missing (MG-259)

- libs/openchallenges/api-description/openapi/challenge.openapi.yaml
- libs/openchallenges/api-description/openapi/openapi.yaml
- libs/openchallenges/api-description/openapi/organization.openapi.yaml
- libs/openchallenges/api-description/src/challenge.openapi.yaml
- libs/openchallenges/api-description/src/components/responses/Forbidden.yaml
- libs/openchallenges/api-description/src/organization.openapi.yaml
This PR lays the groundwork for adding "write" endpoints to the OC REST APIs
* add new schema for Forbidden response object for `403` status
* add `securitySchema` to the `challenge` and `organization` OpenAPI specs
> feat(openchallenges): base changes for api-description

- libs/openchallenges/home/src/lib/home.component.html
- libs/openchallenges/home/src/lib/home.component.ts
- [SMR-54](https://sagebionetworks.jira.com/browse/SMR-54)
- Replace the `sageAppShellNoRender` directive by `@defer` block in OC.
[SMR-54]: https://sagebionetworks.jira.com/browse/SMR-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(openchallenges): replace the `sageAppShellNoRender` directive by `@defer` block (SMR-54)

- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/projection/YearlyChallengeCount.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/repository/ChallengeRepository.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/service/ChallengeAnalyticsService.java
- docker/openchallenges/services/challenge-service.yml
- libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.html
- [SMR-233](https://sagebionetworks.jira.com/browse/SMR-233)
- Compute the home page plot data with an SQL query in the challenge service.
- Update the plot title.
```java
public ChallengesPerYearDto getChallengesPerYear() {
List<String> years = Arrays.asList(
"2007",
"2008",
"2009",
"2010",
"2011",
"2012",
"2013",
"2014",
"2015",
"2016",
"2017",
"2018",
"2019",
"2020",
"2021",
"2022",
"2023",
"2024",
"2025"
);
// The following line will be auto-updated by a script and should NOT be modified manually.
List<Integer> challengeCounts = /* AUTO-UPDATE MARKER */Arrays.asList(11, 17, 25, 34, 45, 53, 61, 73, 85, 100, 138, 155, 178, 203, 254, 316, 387, 452, 484);
Integer undatedChallengeCount = 171;
```
```json
{
"years": [
"1999",
"2000",
"2002",
"2003",
"2004",
"2005",
"2006",
"2007",
"2008", …
```
> refactor(openchallenges): compute the home page plot data dynamically to prevent data drift (SMR-233)

- libs/openchallenges/challenge/src/lib/challenge-overview/challenge-overview.component.ts
- libs/openchallenges/challenge/src/lib/challenge-stargazers/challenge-stargazers.component.ts
- libs/openchallenges/challenge/src/lib/challenge.component.ts
- libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.ts
- libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.ts
- libs/openchallenges/home/src/lib/featured-challenge-list/featured-challenge-list.component.ts
- libs/openchallenges/home/src/lib/platforms/platforms.component.ts
- libs/openchallenges/home/src/lib/random-challenge-list/random-challenge-list.component.ts
- libs/openchallenges/home/src/lib/sponsor-list/sponsor-list.component.ts
- libs/openchallenges/home/src/lib/topics-viewer/topics-viewer.component.ts
- libs/openchallenges/org-profile/src/lib/org-profile-overview/org-profile-overview.component.ts
- libs/openchallenges/org-profile/src/lib/org-profile-stats/org-profile-stats.component.ts
- libs/openchallenges/org-profile/src/lib/org-profile.component.ts
- libs/openchallenges/team/src/lib/team.component.ts
- libs/openchallenges/ui/src/lib/button-github/button-github.component.ts
- libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.ts
- libs/openchallenges/ui/src/lib/footer/footer.component.ts
- libs/openchallenges/ui/src/lib/organization-card/organization-card.component.ts
- libs/openchallenges/ui/src/lib/user-button/user-button.component.ts
- [SMR-242](https://sagebionetworks.jira.com/browse/SMR-242)
Fixes #(issue)
- Remove `CommonModule` from OC Angular components.
[SMR-242]: https://sagebionetworks.jira.com/browse/SMR-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(openchallenges): remove `CommonModule` from OC Angular components (SMR-242)

- apps/agora/app/Dockerfile
Align the major version number of Node.js used as the base Docker image of the Model-AD web app to the version installed inside the dev environment. The update also fixes a [critical CVE.](https://hub.docker.com/layers/library/node/20.7.0-alpine/images/sha256-ad38de8de343e0fed46efcb5b8df47f4996da2a3fb359eef3f53243b1670b50e)
- [SMR-201](https://sagebionetworks.jira.com/browse/SMR-201)
- Update `model-ad-app` base Docker image to Node.js 22.
```
$ docker exec agora-app node --version
v22.17.0
```
[SMR-202]: https://sagebionetworks.jira.com/browse/SMR-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SMR-201]: https://sagebionetworks.jira.com/browse/SMR-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
> chore(agora): update dockerfile to node.js 22 (SMR-201)

- libs/explorers/ui/src/lib/components/header/header.component.scss
This fixes few style lint warnings in the console when running the Model-AD web app.
[MG-294](https://sagebionetworks.jira.com/browse/MG-294)
Style lint warnings were triggered by the placement of @media queries.  Reordering the media queries fixes the error.
[MG-294]: https://sagebionetworks.jira.com/browse/MG-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(model-ad): fix style lint warnings in header (MG-294)

- apps/openchallenges/opensearch-dashboards/Dockerfile
- apps/openchallenges/opensearch-dashboards/project.json
- docker/openchallenges/serve-detach.sh
- docker/openchallenges/services/opensearch-dashboards.yml
This dashboard will be used to visualize the data current indexed in OpenSearch as well as new data that will be indexed soon from external sites like Kaggle.
- [SMR-220](https://sagebionetworks.jira.com/browse/SMR-220)
- Add the project `openchallenges-opensearch-dashboards`.
- Add Docker Compose files to start the new app.
- Reuse the existing dev container port `5601`.
- Document how to create an index pattern in OS Dashboads and explore OC data.
```bash
nx serve-detach openchallenges-{apex,opensearch-dashboards} --parallel 1
```
At startup, the challenge and organization microservices index their data into OpenSearch. The indices can be listed using the command below. For example, we can see that the index `openchallenges-challenge-000001` includes 679 …
> feat(openchallenges): add OpenSearch Dashboards to OC (SMR-220)

- .vscode/settings.json
Create `github.copilot.chat.agent.terminal` `allowList` and `denyList`.
- [SMR-264](https://sagebionetworks.jira.com/browse/SMR-264)
- Adds terminal commands that the Copilot Agent can run without approval (`allowList`) or must always ask for approval before running (`denyList`)
> [!NOTE] 
> Feature became available in the June 2025 release of VS Code. Ensure that your VS Code is on version 1.102.0 before attempting to test.
The video below demonstrates the feature -- `git log` runs without approval (`allowList`), whereas `eval` requires approval (`denyList`).
https://github.com/user-attachments/assets/3f75854f-da04-4b03-8a8d-18873595f0f9
[SMR-264]: https://sagebionetworks.jira.com/browse/SMR-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(sage): create github.copilot.chat.agent.terminal.allowList and denyList (SMR-264)

- libs/agora/charts/src/lib/box-plot-chart/box-plot-chart.component.ts
- libs/explorers/util/src/lib/pipes/decode-greek-entity.pipe.spec.ts
- libs/explorers/util/src/lib/pipes/decode-greek-entity.pipe.ts
- libs/explorers/util/src/lib/pipes/index.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.html
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.scss
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-grid/model-details-boxplots-grid.component.html
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-grid/model-details-boxplots-grid.component.scss
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-grid/model-details-boxplots-grid.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-grid/model-details-boxplots-grid.component.ts
- libs/model-ad/model-details/src/lib/model-details.component.html
- libs/model-ad/model-details/src/lib/model-details.component.ts
- libs/model-ad/model-details/src/test-setup.ts
- libs/shared/typescript/charts-angular/src/lib/boxplot/boxplot.directive.spec.ts
- libs/shared/typescript/charts-angular/src/lib/boxplot/boxplot.directive.stories.ts
- libs/shared/typescript/charts-angular/src/lib/boxplot/boxplot.directive.ts
- libs/shared/typescript/charts/src/lib/boxplot-chart/boxplot-chart.ts
- libs/shared/typescript/charts/src/lib/models/boxplot.ts
- libs/shared/typescript/charts/src/lib/utils/boxplot-utils.spec.ts
- libs/shared/typescript/charts/src/lib/utils/boxplot-utils.ts
This PR adds the Model-AD boxplot and grid for displaying related boxplots. Also updates shared boxplot styling options, including allowing configuration of point opacity and ensuring that points maintain their expected color/shape when filtering.
> [!NOTE] 
> 1. The boxplots are rendered in the model details page for demonstration purposes only, so may not be appropriately grouped (e.g. multiple tissues included in the same grid). Filters and grids grouped by tissue will be added in a future PR. 
> 2. The boxplot style will be addressed in [MG-298](https://sagebionetworks.jira.com/browse/MG-298).
- [MG-274](https://sagebionetworks.jira.com/browse/MG-274)
- [MG-299](https://sagebionetworks.jira.com/browse/MG-299)
- Creates Model-AD boxplot and grid component for displaying multiple …
> feat(model-ad): add model-ad boxplot and update boxplot styling options (MG-274, MG-299)

- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengeEntity.java
Index `challenge.website_url` in OpenSearch to make it easier to visit a challenge web page from results displayed in OpenSearch Dashboards. The property is indexed but is set as non-searchable to make searches faster.
- [SMR-275](https://sagebionetworks.jira.com/browse/SMR-275)
- [SMR-276](https://sagebionetworks.jira.com/browse/SMR-276)
- Index `challenge.website_url` in OpenSearch.
Start the OC stack:
```bash
```
Start OpenSearch Dashboards, which is not deployed with the main stack:
```bash
nx serve-detach openchallenges-opensearch-dashboards
```
1. Navigate to http://localhost:5601.
2. Open the three-bar menu >Management > Select "Dashboards Management".
3. Click on "Index Patterns".
4. Click on "Create index pattern". …
> feat(openchallenges): index `challenge.website_url` in OpenSearch (SMR-275, SMR-276)

- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/SimpleChallengePlatformEntity.java
Make challenge.platform.slug and challenge.platform.name aggregatable.
- [SMR-274](https://sagebionetworks.jira.com/browse/SMR-274)
- Make challenge.platform.slug and challenge.platform.name aggregatable.
We can now generate a pie chart directly in OpenSearch Dashboards, where categories are created automatically. This is a significant improvement over the [previous diagram](https://github.com/Sage-Bionetworks/sage-monorepo/pull/3283#pullrequestreview-3007220395), which required manual category creation by the user.
[SMR-274]: https://sagebionetworks.jira.com/browse/SMR-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(openchallenges): make challenge.platform.slug and challenge.platform.name aggregatable (SMR-274)

- .github/workflows/ci.yml
Fix `NX_BRANCH` value in the CI workflow when merging to `main`.
- [SMR-280](https://sagebionetworks.jira.com/browse/SMR-280)
- Fix `NX_BRANCH` value in the CI workflow when merging to `main`.
- Remove references to Renovate from the CI workflow.
The job steps are properly annotated with the PR number when the jobs are triggered by pushing a commit to a PR.
However, there are no results when searching for the `main` branch. The jobs that ran when pushing to the `main` branch exist, but they are annotated with "no branch".
[SMR-280]: https://sagebionetworks.jira.com/browse/SMR-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(sage-monorepo): fix `NX_BRANCH` value in the main CI workflow when merging to `main` (SMR-280)

- apps/model-ad/data/.env.example
- libs/explorers/services/src/index.ts
- libs/explorers/services/src/lib/breakpoint-config.service.spec.ts
- libs/explorers/services/src/lib/breakpoint-config.service.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.html
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-grid/model-details-boxplots-grid.component.html
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-grid/model-details-boxplots-grid.component.scss
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-grid/model-details-boxplots-grid.component.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.html
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.scss
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.ts
- libs/model-ad/model-details/src/lib/model-details.component.html
- libs/model-ad/model-details/src/lib/model-details.component.scss
- libs/model-ad/model-details/src/lib/model-details.component.ts
- libs/model-ad/styles/src/_index.scss
- libs/model-ad/styles/src/lib/components/_typography.scss
- libs/shared/typescript/charts-angular/src/lib/boxplot/boxplot.directive.spec.ts
- libs/shared/typescript/charts-angular/src/lib/boxplot/boxplot.directive.stories.ts
- libs/shared/typescript/charts-angular/src/lib/boxplot/boxplot.directive.ts
- libs/shared/typescript/charts/src/index.ts
- libs/shared/typescript/charts/src/lib/boxplot-chart/boxplot-chart.ts
- libs/shared/typescript/charts/src/lib/models/boxplot.ts
- libs/shared/typescript/charts/src/lib/utils/chart-utils.ts
Adds the model details boxplot selector and content to the model details biomarkers and pathology tabs.
> [!NOTE]
> The boxplot style and selector's download buttons, complete table of contents, and share links will be added in future tickets.
- [MG-216](https://sagebionetworks.jira.com/browse/MG-216)
- [MG-217](https://sagebionetworks.jira.com/browse/MG-217)
- [MG-219](https://sagebionetworks.jira.com/browse/MG-219)
- Adds model details boxplot selector
- Adds content to model details biomarkers and pathology tabs
- Ensures legend is shown on correct model details boxplot when there is an even number of plots in both one and two column layouts
- Wraps very long model details boxplot y-axis titles
- Wraps model details boxplot x-axis labels to align with design via new boxplot input: …
> feat(model-ad): add model details boxplot selector and model details biomarkers/pathology content (MG-216, MG-217, MG-219)

- .github/instructions/nx.instructions.md
- .vscode/mcp.json
Add Atlassian remote MCP server to `mcp.json` to extract information and manage resources in Jira and Confluence.
- [SMR-267](https://sagebionetworks.jira.com/browse/SMR-267)
There are two ways to install a (remote) MCP server:
1. By adding its configuration directly to `.vscode/mcp.json`.
2. Using the Extension menu of VS Code
- Open the Extension menu
- Open the section "MCP Servers - Installed"
- Place the cursor on this menu section to reveal the "globe" button named "Browse MCP Servers"
- You are redirected to a web page that list MCP server.
- Click on the "Install" button of the MCP server you want to install, e.g. GitHub or Atlassian
- Back to VS Code, the MCP server will be listed as shown below
The preferred method is to define the MCP server in `mcp.json` so that developers …
> feat(sage-monorepo): add Atlassian remote MCP server to `mcp.json` (SMR-267)

- apps/openchallenges/apex/Caddyfile
Prevent Caddy from adding trailing slash to the API docs URL.
- [SMR-305](https://sagebionetworks.jira.com/browse/SMR-305)
[SMR-305]: https://sagebionetworks.jira.com/browse/SMR-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(openchallenges): prevent Caddy from adding trailing slash to the API docs url (SMR-305)

- package.json
- pnpm-lock.yaml
Update `@redocly/cli` and remove `redoc` override ahead of refactoring OC OpenAPI files to support public and internal endpoints (`nx run-many -p *-api-description -t build`).
> [!NOTE]
> `@redocly/cli` v2 has been released a few hours ago. I've used it to build all the OpenAPI descriptions in the monorepo and none were affected by the update.
- Update `@redocly/cli` and remove `redoc` override.
Build all OpenAPI descriptions of all the products in the monorepo:
```bash
nx run-many -p *-api-description -t build
```
```bash
nx run-many -p *-api-docs -t build --skip-nx-cache
```
The output of `git status` shows that none of the generated OpenAPI files have been modified.
These HTML files are currently not tracked with Git.
The HTML file for OC looks as expected.
> chore: update @redocly/cli and remove redoc override

- .github/workflows/e2e-explorer.yaml
We pinned a minor version of `nrwl/nx-set-shas` action in the `e2e-explorer.yaml` workflow due to a bug in how `pull_request_target` triggers were handled. The bug has been fixed, so we can pin the major version in the workflow instead.
- [SMR-307](https://sagebionetworks.jira.com/browse/SMR-307)
- Use major version of `nrwl/nx-set-shas` in `e2e-explorer.yaml`
[SMR-307]: https://sagebionetworks.jira.com/browse/SMR-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(explorers): use major version of nrwl/nx-set-shas (SMR-307)

- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/dto/ChallengeUpdateRequestDto.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/service/ChallengeService.java
- apps/openchallenges/challenge-service/src/main/resources/openapi.yaml
- libs/openchallenges/api-client-angular/src/lib/model/challengeUpdateRequest.ts
- libs/openchallenges/api-client-python/docs/ChallengeUpdateRequest.md
- libs/openchallenges/api-client-python/openchallenges_api_client_python/models/challenge_update_request.py
- libs/openchallenges/api-client-python/test/test_challenge_update_request.py
- libs/openchallenges/api-description/openapi/challenge-public.openapi.yaml
- libs/openchallenges/api-description/openapi/challenge-service.openapi.yaml
- libs/openchallenges/api-description/openapi/openapi.yaml
- libs/openchallenges/api-description/src/components/schemas/ChallengeUpdateRequest.yaml
Enable the user to update the challenge input data types and operation.
- [SMR-371](https://sagebionetworks.jira.com/browse/SMR-371)
- Enable the user to update the challenge input data types and operation.
- Update the API clients and server stubs.
[SMR-371]: https://sagebionetworks.jira.com/browse/SMR-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(openchallenges): enable the user to update the challenge input data types and operation (SMR-371)

- apps/amp-als/dataset-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
- apps/openchallenges/auth-service/src/main/java/org/sagebionetworks/openchallenges/auth/service/model/entity/ApiKey.java
- apps/openchallenges/auth-service/src/main/java/org/sagebionetworks/openchallenges/auth/service/model/entity/User.java
- apps/openchallenges/auth-service/src/main/resources/db/migration/V1.0.0__create_initial_schema.sql
- apps/openchallenges/auth-service/src/main/resources/db/migration/V1.0.1__insert_default_users.sql
- apps/openchallenges/auth-service/src/main/resources/db/migration/V1.0.2__insert_service_dev_api_keys.sql
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengeEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengeIncentiveEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengeInputDataTypeEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengePlatformEntity.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengeStar.java
- apps/openchallenges/challenge-service/src/main/java/org/sagebionetworks/openchallenges/challenge/service/model/entity/ChallengeSubmissionTypeEntity.java
- apps/openchallenges/challenge-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
- apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
Ensure that data indexed in OpenSearch are up-to-date with the latest data changes.
- [SMR-344](https://sagebionetworks.jira.com/browse/SMR-344)
- No longer use `ON CASCADE DELETE` at the database level.
- Use `TIMESTAMP WITH TIME ZONE` everywhere.
- Set creation and update timestamp values in the Java code.
[SMR-344]: https://sagebionetworks.jira.com/browse/SMR-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(openchallenges): ensure that data indexed in OpenSearch are up-to-date with the latest data changes (SMR-344)

- apps/model-ad/api/src/models/models.ts
- libs/model-ad/api-description/openapi/api-public.openapi.yaml
- libs/model-ad/api-description/openapi/api-service.openapi.yaml
- libs/model-ad/api-description/openapi/openapi.yaml
- libs/model-ad/api-description/src/components/schemas/IndividualData.yaml
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-grid/model-details-boxplots-grid.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.ts
'Female' should be listed first in combined sex dropdown.
- [MG-346](https://sagebionetworks.jira.com/browse/MG-346)
- Female is listed first in combined sex dropdown and in API enum
`https://dev.modeladexplorer.org/models/3xTg-AD/biomarkers` | `http://localhost:8000/models/3xTg-AD/biomarkers`
:---: | :---:
[MG-346]: https://sagebionetworks.jira.com/browse/MG-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(model-ad): female should be listed first in combined sex dropdown (MG-346)

- libs/agora/teams/src/lib/teams.component.ts
The teams page has a memory leak that can be fixed by using Angular 16+ DestroyRef feature.
[AG-1843](https://sagebionetworks.jira.com/browse/AG-1843)
- Use DestroyRef to address memory leak
[AG-1843]: https://sagebionetworks.jira.com/browse/AG-1843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(agora): fix teams page memory leak (AG-1843)

- apps/bixarena/api/src/main/resources/openapi.yaml
- libs/bixarena/api-description/openapi/api-public.openapi.yaml
- libs/bixarena/api-description/openapi/api-service.openapi.yaml
- libs/bixarena/api-description/openapi/openapi.yaml
- libs/bixarena/api-description/src/components/schemas/BasicError.yaml
Remove unused x-java-class-annotations from OpenAPI files.
- [SMR-385](https://sagebionetworks.jira.com/browse/SMR-385)
- Remove unused x-java-class-annotations from OpenAPI files.
- Generate the API clients (`nx run-many -p bixarena-* -t generate`).
[SMR-385]: https://sagebionetworks.jira.com/browse/SMR-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(bixarena): remove unused x-java-class-annotations from OpenAPI files (SMR-385)

- libs/agora/api-description/openapi/api-public.openapi.yaml
- libs/agora/api-description/openapi/api-service.openapi.yaml
- libs/agora/api-description/openapi/gene-public.openapi.yaml
- libs/agora/api-description/openapi/gene-service.openapi.yaml
- libs/agora/api-description/openapi/openapi.yaml
- libs/agora/api-description/src/components/schemas/BasicError.yaml
Remove unused x-java-class-annotations from OpenAPI files.
- [SMR-385](https://sagebionetworks.jira.com/browse/SMR-385)
- Remove unused x-java-class-annotations from OpenAPI files.
- Generate the API clients (`nx run-many -p agora-* -t generate`).
[SMR-385]: https://sagebionetworks.jira.com/browse/SMR-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(agora): remove unused x-java-class-annotations from OpenAPI files (SMR-385)

- libs/model-ad/api-description/openapi/api-public.openapi.yaml
- libs/model-ad/api-description/openapi/api-service.openapi.yaml
- libs/model-ad/api-description/openapi/openapi.yaml
- libs/model-ad/api-description/src/components/schemas/BasicError.yaml
Remove unused x-java-class-annotations from OpenAPI files.
- [SMR-385](https://sagebionetworks.jira.com/browse/SMR-385)
- Remove unused x-java-class-annotations from OpenAPI files.
- Generate the API clients (`nx run-many -p model-ad-* -t generate`).
[SMR-385]: https://sagebionetworks.jira.com/browse/SMR-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(model-ad): remove unused x-java-class-annotations from OpenAPI files (SMR-385)

- apps/model-ad/data/src/data/collections-indexes.json
We recently released mv70 in [MG-322](https://sagebionetworks.jira.com/browse/MG-322), which included renaming model to name across collections. We should rename the indexes to match the new field name.
- [MG-322](https://sagebionetworks.jira.com/browse/MG-322)
- Use `name` instead of `model` in model-ad-data indexes
[MG-322]: https://sagebionetworks.jira.com/browse/MG-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MG-322]: https://sagebionetworks.jira.com/browse/MG-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(model-ad): use name instead of model for indexes (MG-322)

- apps/agora/data/.env.example
- libs/agora/genes/src/lib/components/gene-soe/gene-soe.component.html
Defers rendering of gene details summary charts to the browser to fix bug where biological domain mappings were not selectable. Suspect this bug is related to the Vite migration, where we addressed [similar issues for other charts](https://github.com/Sage-Bionetworks/sage-monorepo/pull/3243#discussion_r2181049739) in other gene details tabs.
Also bumps data version to align with latest release.
- [AG-1858](https://sagebionetworks.jira.com/browse/AG-1858)
- Defers rendering of charts to the browser to fix bug where biological domain mappings were not selectable
- Bumps data version to align with latest release to align with latest release
https://github.com/user-attachments/assets/3c134d48-e321-4d85-9d0d-74a769c91e6c
[AG-1858]: https://sagebionetworks.jira.com/browse/AG-1858?atlOrigin=eyJpI …
> fix(agora): defer rendering of gene details summary charts to the browser, bump data version to align with latest release (AG-1858)

- gradle/libs.versions.toml
Update Java dependencies (August 2025).
- Update Java dependencies (August 2025).
As a reminder:
- I experience error when upgrading to Gradle 9 in the past because of Paketo. They initially said that they won't support Gradle 9 until Spring Boot 4 is released.
- Migrating to Hibernate Search 8 will require us to migrate to Spring Boot 4 and its ORM 6 when it's released.
> chore(sage-monorepo): update Java dependencies (August 2025)

- .husky/pre-commit
- .husky/pre-push
- lint-staged.config.js
Keep hooks fast and let CI be the gate for tests.
- No longer run tests on affected projects during during pre-commit.
- Document recommendations on which processes should run during pre-commit and pre-push.
> chore(sage-monorepo): make the pre-commit hook more snappy

- apps/agora/app/src/app/app.component.ts
- libs/agora/config/src/lib/constants.ts
- libs/explorers/util/src/lib/loading-icon/loading-icon.component.scss
Specify shared loading icon colors for Agora and remove unnecessary explorers styles import to fix bug where explorers action-primary color overrode Agora's action-primary color.
- [AG-1860](https://sagebionetworks.jira.com/browse/AG-1860)
- Specifies colors for shared loading icon in Agora
- Removes unnecessary explorers style import from loading icon component
`agora-build-images && agora-docker-start`
The search input search result hover color is not purple after loading terms of service page: 
https://github.com/user-attachments/assets/821c09cb-cf1d-4c46-9dac-cf319112f771
[AG-1860]: https://sagebionetworks.jira.com/browse/AG-1860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(agora): specify shared loading icon colors for agora, remove unnecessary explorers styles import (AG-1860)

- libs/sage-monorepo/nx-plugin/src/plugins/build-image-target.ts
- libs/sage-monorepo/nx-plugin/src/plugins/project-metadata.ts
The bug described in [SMR-430](https://sagebionetworks.jira.com/browse/SMR-430) occurs because the plugin references the Dockerfile using an incorrect path. Specifically, the code was resolving the path relative to the Docker context instead of the project folder, where the Dockerfile actually resides.
- [SMR-430](https://sagebionetworks.jira.com/browse/SMR-430)
- Fix the path to the Dockerfile used when building the images.
- Detect when projects use `esbuild` as the builder (not related to the bug).
```bash
agora-build-images
model-ad-build-images
```
[SMR-430]: https://sagebionetworks.jira.com/browse/SMR-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SMR-430]: https://sagebionetworks.jira.com/browse/SMR-430?atlOrigin=eyJpIjoiNWRkNTljNzY …
> fix(sage-monorepo): detect projects built with esbuild and fix Dockerfile location for image build (SMR-430)

- .devcontainer/devcontainer.json
Remove VS Code extension `nrwl.angular-console` that may include malicious code at this time. We are still monitoring the situation.
See https://sagebionetworks.jira.com/browse/IT-4585 for more details.
> chore: remove VS Code extension `nrwl.angular-console`

- apps/model-ad/api/src/models/modelOverviewComparisonTool.ts
- apps/model-ad/data/.env.example
- libs/model-ad/api-client-angular/src/lib/model/modelOverview.ts
- libs/model-ad/api-description/openapi/api-public.openapi.yaml
- libs/model-ad/api-description/openapi/api-service.openapi.yaml
- libs/model-ad/api-description/openapi/openapi.yaml
- libs/model-ad/api-description/src/components/schemas/ModelOverview.yaml
- libs/model-ad/api-description/src/components/schemas/ModelOverviewLink.yaml
- libs/model-ad/model-overview-comparison-tool/src/lib/components/model-overview-main-table/model-overview-main-table.component.html
- libs/model-ad/model-overview-comparison-tool/src/lib/components/model-overview-main-table/model-overview-main-table.component.ts
Bump model-ad-data to mv84 and align models with updated data structure. 
> [!NOTE]
> The "no data" boxplot placeholder styling will be handled in [MG-317](https://sagebionetworks.jira.com/browse/MG-317).
- [MG-362](https://sagebionetworks.jira.com/browse/MG-362)
- [MG-356](https://sagebionetworks.jira.com/browse/MG-356)
- [MG-329](https://sagebionetworks.jira.com/browse/MG-329)
- Bumps model-ad-data to mv84
- Remove mutual exclusivity from model overview link schema; `link_text` and `link_url` are not mutually exclusive in mv83 (see [MG-356](https://sagebionetworks.jira.com/browse/MG-356))
- Change model overview `matched_controls` from a string to a list to align with mv84 (see [MG-329](https://sagebionetworks.jira.com/browse/MG-329)) …
> chore(model-ad): bump model-ad-data to mv84 and align models with updated data structure (MG-362)

- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.ts
Model details boxplots were not displayed when a tissue was selected that included more evidence types than the previous tissue because the code attempted to access the `nativeElement` before the new boxplot elements had been added to the DOM.
The same bug is also preventing the boxplots from updating when changing the tissue type.
- [MG-387](https://sagebionetworks.jira.com/browse/MG-387)
- [MG-392](https://sagebionetworks.jira.com/browse/MG-392)
- Fixes bug preventing the display of model details boxplots
All evidence types shown: 
https://github.com/user-attachments/assets/497e3165-f692-4d73-9ad5-7f41b5c788ee
Boxplots are updated when tissue is changed: 
https://github.com/user-attachments/assets/8b28ac71-0ce0-4259-906f-368f73fd08ef
[MG-387]: …
> fix(model-ad): fix bug preventing display of all boxplots (MG-387, MG-392)

- libs/model-ad/model-details/src/lib/components/model-details-boxplots-grid/model-details-boxplots-grid.component.scss
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.scss
Allow the model details boxplots container to stretch wider than the section width, so the plots will transition to a 3x1 grid when the page is very wide.
[MG-330](https://sagebionetworks.jira.com/browse/MG-330)
- Allow model details boxplots container to stretch wider than the section width
`http://localhost:8000/models/Abca7*V1599M/biomarkers`
https://github.com/user-attachments/assets/afd78808-2d35-4cd3-b023-9e6d9dd442e1
[MG-330]: https://sagebionetworks.jira.com/browse/MG-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(model-ad): allow model details boxplots container to stretch wider than the section (MG-330)

- libs/explorers/shared/src/lib/components/terms-of-service/terms-of-service.component.scss
- libs/explorers/shared/src/lib/components/terms-of-service/terms-of-service.component.ts
We should style the TOS content.
[MG-296](https://sagebionetworks.jira.com/browse/MG-296)
- Override global CSS reset so the TOS content is styled
- Disable view encapsulation for the TOS component, so the CSS rules can properly target the dynamically generated content in the markdown component
dev (current) | this PR (updated)
:---: | :---: 
[MG-296]: https://sagebionetworks.jira.com/browse/MG-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(model-ad): style terms of service content (MG-296)

- apps/model-ad/api/src/components/modelSearch.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.html
- libs/explorers/ui/src/lib/components/search-input/search-input.component.scss
- libs/explorers/ui/src/lib/components/search-input/search-input.component.spec.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.ts
Add highlighting of the search query in the search results and general improvements to the search input component.
- [MG-360](https://sagebionetworks.jira.com/browse/MG-360)
- [MG-2](https://sagebionetworks.jira.com/browse/MG-2)
- Highlights search query in search results
- Modernizes search input component to use signals rather than decorators
- Improves accessibility of search result options by adding aria labels and buttons
- Fixes display of long search results
- Removes trimming of query on server -- space is an allowed search character
https://github.com/user-attachments/assets/77852712-4534-41ea-9907-4b6408fae07b
https://github.com/user-attachments/assets/88e17366-701f-4ea0-9736-b30470055928
[MG-360]: …
> feat(model-ad): highlight search query in search results, modernize search input to use signals, fix display of long search results (MG-360)

- libs/model-ad/model-details/src/lib/components/model-details-hero/model-details-hero.component.html
- libs/model-ad/model-details/src/lib/components/model-details-hero/model-details-hero.component.ts
Link matched control values to JAX in model details hero.
[MG-397](https://sagebionetworks.jira.com/browse/MG-397)
- Link matched control values to JAX in model details hero
`http://localhost:8000/models/Abca7*V1599M`
dev (before) | this PR (after)
:---: | :---: 
Demonstration of links: 
https://github.com/user-attachments/assets/9d17f9c9-f784-4194-8a8c-6fbeea850cf7
[MG-397]: https://sagebionetworks.jira.com/browse/MG-397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(model-ad): matched control(s) value(s) in hero link to JAX (MG-397)

- apps/model-ad/app/e2e/helpers.ts
- apps/model-ad/app/e2e/model-details.spec.ts
- apps/model-ad/app/e2e/search.spec.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.html
- libs/explorers/ui/src/lib/components/search-input/search-input.component.scss
- libs/explorers/ui/src/lib/components/search-input/search-input.component.spec.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.ts
The user should be able to navigate and select a search result using the mouse or the keyboard.
[MG-361](https://sagebionetworks.jira.com/browse/MG-361)
- Allow the user to navigate and select a search result using the keyboard
Using the mouse: 
https://github.com/user-attachments/assets/684ace3f-fa01-4df4-8b37-b56001e9410a
Using the keyboard: 
https://github.com/user-attachments/assets/bf375b90-f26f-4aea-8b62-0b63d039f498
[MG-361]: https://sagebionetworks.jira.com/browse/MG-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(model-ad): allow search results to be selected with mouse or keyboard (MG-361)

- libs/explorers/charts-angular/src/lib/boxplot/boxplot.directive.spec.ts
- libs/explorers/charts-angular/src/lib/boxplot/boxplot.directive.stories.ts
- libs/explorers/charts-angular/src/lib/boxplot/boxplot.directive.ts
- libs/explorers/charts/src/lib/boxplot-chart/boxplot-chart.ts
- libs/explorers/charts/src/lib/models/boxplot.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.html
- libs/model-ad/model-details/src/lib/components/model-details-boxplot/model-details-boxplot.component.ts
We would like to align the model details boxplots style with the design.
[MG-298](https://sagebionetworks.jira.com/browse/MG-298)
- Adds boxplot `chartStyle` options -- `minimal` to maintain style for Agora and `grayGrid` for the Model-AD design with grid lines and gray background behind boxes
- Left-aligns text and updates marker to a square in model details boxplot tooltips
This PR updates the chart and tooltip style to align more closely with the design:
dev (current) | this PR (updated) 
:---: | :---: 
This PR does not change the styling of the Agora boxplot:
`agora-build-images && agora-docker-start`
dev (current) | this PR (updated) 
:---: | :---:
[MG-298]: https://sagebionetworks.jira.com/browse/MG-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
> feat(model-ad): align boxplot style with design (MG-298)

- .github/workflows/e2e-explorer.yaml
Explorer e2e GitHub Actions jobs have been failing with a "Nx Cloud: Workspace is unable to be authorized. Exiting run." error. The failing step uniquely sets the `CI=true` environment variable, which is used to prevent Playwright reports from opening on test failures in CI environments. Since the e2e workflow doesn't set `NX_CLOUD_ACCESS_TOKEN` to authenticate with Nx Cloud, we will disable Nx Cloud for the explorer e2e tests for now. 
[SMR-463](https://sagebionetworks.jira.com/browse/SMR-463)
- Disables Nx Cloud for explorer e2e tests
Start Model-AD: `model-ad-build-images && model-ad-docker-start`
Run e2e tests without disabling Nx Cloud to see the current failure state: 
```
$ CI=true nx run model-ad-app:e2e
NX   Nx Cloud: Workspace is unable to be authorized. Exiting run.
You are not …
```
> fix(explorers): skip nx cloud for e2e tests (SMR-463)

- apps/agora/app/project.json
- apps/agora/app/src/proxy.conf.json
- apps/model-ad/app/project.json
- apps/model-ad/app/src/proxy.conf.json
- apps/openchallenges/app/project.json
- docker/agora/services/apex.yml
- docker/model-ad/services/apex.yml
- docker/openchallenges/services/apex.yml
- tools/configure-hostnames.sh
Introducing Docker Compose `extra_hosts` to OC and Agora apexes to enable swapping upstream apps (e.g., API server, Angular app) between their containers and their development servers.
Consider the following case where the Agora stack is deployed locally with Docker Compose.
1. Build the Docker images and deploy the stack with Docker Compose
```bash
agora-build-images
nx serve-detach agora-apex
```
2. Access the web app via the Caddy reverse proxy at `http://localhost:8000`.
3. Stop or remove the `agora-app` container.
```bash
nx stop agora-app
```
4. Start the web app development server.
```bash
nx serve agora-app
````
5. Accessing the web app via the reverse proxy fails. ❌
Currently, developers must access the web app directly at `localhost:4200` during active development. The same …
> feat: add Docker Compose `extra_hosts` to OC, Agora and Model-AD apexes (SMR-384)

- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.html
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.scss
The boxplots download should include all boxplots. We recently updated the boxplots grid to allow the boxplots to rearrange to 1, 2, or 3 plots per row, but the styling caused issues with the DOM capture library. This PR adds a wrapper div around the grid, so the grid remains in the normal document flow for proper DOM capture while maintaining the existing functionality.
- [MG-407](https://sagebionetworks.jira.com/browse/MG-407)
- Fixes issue where only partial plots were captured in downloads
- Add wrapper div around model-details-boxplots-grid component
- Move full-width positioning styles from grid component to wrapper
- Keep grid component in normal document flow for proper DOM capture
`model-ad-build-images && model-ad-docker-build`
Downloaded image contains all plots: 
Maintains …
> fix(model-ad): wrap boxplots grid to enable complete image downloads (MG-407)

- apps/model-ad/app/e2e/search.spec.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.spec.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.ts
We would like to update the 'no results' message in the search input.
[MG-409](https://sagebionetworks.jira.com/browse/MG-409)
- Update 'no results' message in search input
[MG-409]: https://sagebionetworks.jira.com/browse/MG-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(model-ad): update 'no results' message in search input (MG-409)

- apps/model-ad/app/e2e/search.spec.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.spec.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.ts
Currently, the frontend performs sanitization to remove special characters from the search query. However, some special characters are valid, e.g. a period is a character in a model name. The backend already performs regex escaping, so the frontend sanitization is unnecessarily restrictive and prevents users from searching for characters in valid model names. We will remove the frontend sanitization in favor of the backend query handling.
[MG-408](https://sagebionetworks.jira.com/browse/MG-408)
- Remove frontend search query sanitization in favor of backend query handling
https://github.com/user-attachments/assets/af0e6678-fac9-436b-b7ab-e9bed5065ead
[MG-408]: https://sagebionetworks.jira.com/browse/MG-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> fix(model-ad): remove frontend search query sanitization in favor of backend query escaping

- apps/agora/app/src/config/config.json
- apps/model-ad/app/src/config/config.json
Fix `csrApiUrl` for explorers to use extra_host feature.
[SMR-473](https://sagebionetworks.jira.com/browse/SMR-473)
- Update `csrApiUrl` for model-ad-app and explorers-app to work with extra_host feature
`model-ad-build-images && model-ad-docker-start && docker rm -f model-ad-app && nx serve model-ad-app`
Navigate to a page that makes an API call to model-ad-api, e.g. `http://localhost:8000/models/3xTg-AD`
Page should load: 
[SMR-473]: https://sagebionetworks.jira.com/browse/SMR-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(explorers): fix csrApiUrl for explorers to use extra_host feature (SMR-473)

- apps/agora/app/tsconfig.spec.json
- apps/openchallenges/app/tsconfig.json
- apps/openchallenges/app/tsconfig.spec.json
- libs/amp-als/api-client-angular/tsconfig.json
- libs/amp-als/api-client-angular/tsconfig.lib.json
- libs/amp-als/api-client-angular/tsconfig.lib.prod.json
- libs/explorers/charts-angular/tsconfig.json
- libs/explorers/charts/tsconfig.json
- libs/openchallenges/about/tsconfig.json
- libs/openchallenges/api-client-angular/tsconfig.json
- libs/openchallenges/api-client-angular/tsconfig.spec.json
- libs/openchallenges/challenge-search/tsconfig.json
- libs/openchallenges/challenge/tsconfig.json
- libs/openchallenges/config/tsconfig.json
- libs/openchallenges/home/tsconfig.json
- libs/openchallenges/not-found/tsconfig.json
- libs/openchallenges/org-profile/tsconfig.json
- libs/openchallenges/org-search/tsconfig.json
- libs/openchallenges/ui/tsconfig.json
- libs/results-visualization-framework/ui/tsconfig.json
- libs/sandbox/angular-lib/tsconfig.json
- libs/sandbox/angular-lib/tsconfig.spec.json
- libs/shared/typescript/util/tsconfig.json
- libs/synapse/api-client-angular/tsconfig.json
- libs/synapse/api-client-angular/tsconfig.spec.json
- tools/tsconfig.tools.json
Update all es targets to `es2024`.
- [SMR-284](https://sagebionetworks.jira.com/browse/SMR-284)
Update all es targets to `es2024`.
[SMR-284]: https://sagebionetworks.jira.com/browse/SMR-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): update all es targets to `es2024` (SMR-284)

- apps/openchallenges/app/project.json
Add missing Nx task `openchallenges-app:create-config`.
- [SMR-459](https://sagebionetworks.jira.com/browse/SMR-459)
- Add missing Nx task `openchallenges-app:create-config`.
[SMR-459]: https://sagebionetworks.jira.com/browse/SMR-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(openchallenges): add missing Nx task `openchallenges-app:create-config` (SMR-459)

- apps/model-ad/app/e2e/model-details.spec.ts
- libs/explorers/services/src/lib/helper.service.ts
- libs/model-ad/model-details/src/lib/model-details.component.ts
We would like to hide the omics tab from the model details page when there is no omics data. We would also like to gracefully handle the case where the URL contains a tab that does not exist or is disabled for the current model.
- [MG-282](https://sagebionetworks.jira.com/browse/MG-282)
- [MG-415](https://sagebionetworks.jira.com/browse/MG-415)
- Adds conditional disabling of the Omics tab
- Implements fallback logic to redirect users from invalid/disabled tabs to the first available tab and update the URL
- Changes the default activePanel from 'omics' to empty string to ensure proper fallback behavior instead of assuming omics is always available
- Moves URL parsing from ngOnInit to inside the HTTP response handler so panel validation occurs after model data is loaded
Start the app: …
> fix(model-ad): conditionally display omics tab, fallback to default tab when invalid or disabled tab in URL (MG-282, MG-415)

- apps/model-ad/app/e2e/model-details.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.ts
Copying model details section links shouldn't change the current URL.
[MG-412](https://sagebionetworks.jira.com/browse/MG-412)
- Copying model details section links no longer updates the current URL
https://github.com/user-attachments/assets/e62cb7f6-de43-4220-85fb-b8122a9b090f
[MG-412]: https://sagebionetworks.jira.com/browse/MG-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(model-ad): copying section links shouldn't change the current URL (MG-412)

- apps/model-ad/app/e2e/model-details.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.ts
We would like to clean up the model details section link fragments.
- [MG-414](https://sagebionetworks.jira.com/browse/MG-414)
- Cleans up section link fragments
Note the updated fragments in the URL:
https://github.com/user-attachments/assets/fc80029d-0bce-4901-b5b4-d24ef24d8d3d
[MG-414]: https://sagebionetworks.jira.com/browse/MG-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(model-ad): clean up section link fragments (MG-414)

- apps/model-ad/app/e2e/model-details.spec.ts
- libs/model-ad/model-details/src/lib/components/model-details-boxplots-selector/model-details-boxplots-selector.component.ts
Currently, when a model details URL contains a hash fragment, the page scrolls to the appropriate section on full page reload (e.g. Cmd + Shift + R on a Mac), but not on a same-document navigation (e.g. moving cursor to the address bar, then pressing enter) because the same-document navigation doesn’t trigger Angular component lifecycle methods which we've used to trigger the scroll. This PR adds a listener for the `popstate` event so the page will scroll after same-document navigation.
[MG-413](https://sagebionetworks.jira.com/browse/MG-413)
- Scroll to section in model details page after same-document navigation with valid hash fragment
- Remove hash fragment from url after same-document navigation with invalid hash fragment
- Fixes expectations for scroll position in e2e tests …
> fix(model-ad): ensure scroll to section after same-document navigation (MG-413)

- libs/explorers/testing/src/lib/mocks/search-result-mocks.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.html
- libs/explorers/ui/src/lib/components/search-input/search-input.component.scss
- libs/explorers/ui/src/lib/components/search-input/search-input.component.spec.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.stories.ts
- libs/explorers/ui/src/lib/components/search-input/search-input.component.ts
The shared `search-input` currently supports displaying one block of text per search result. However, Agora displays subtext below the text of each search result in a grey color. We need to extend the `search-input` to allow Agora to provide subtext for each search result. 
Note: the goal of this PR is to replicate the functionality and design of the current Agora search. 
[AG-1878](https://sagebionetworks.jira.com/browse/AG-1878)
- Extend search-input to allow subtext beneath result text
`nx storybook explorers-storybook` 
current Agora search | explorers search component
:----: | :----: 
[AG-1878]: https://sagebionetworks.jira.com/browse/AG-1878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(explorers): extend search-input to allow subtext beneath result text

- .github/workflows/update-synapse-api.yml
Fix GitHub workflow that updates Synapse API. The issue occurred because the workflow committed the changes outside of the dev container where the tools needed by the git hooks were not available.
- [SMR-435](https://sagebionetworks.jira.com/browse/SMR-435)
- Fix GitHub workflow that updates Synapse API.
[SMR-435]: https://sagebionetworks.jira.com/browse/SMR-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(synapse): fix GitHub workflow that updates Synapse API (SMR-435)

- .github/workflows/update-synapse-api.yml
Simplifies the commit message of the workflow that update the Synapse API.
- [SMR-435](https://sagebionetworks.jira.com/browse/SMR-435)
- Fix GitHub workflow that updates Synapse API.
[SMR-435]: https://sagebionetworks.jira.com/browse/SMR-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(synapse): fix GitHub workflow that updates Synapse API - Take 4 (SMR-435)

- .github/workflows/update-synapse-api.yml
Specify base branch in workflow that updates the Synapse API. The workflow previously failed because the current branch, which `peter-evans/create-pull-request@v7` use as the base branch by default, was the same as `branch`.
> fix(synapse): specify base branch in workflow that updates the API

- package.json
- pnpm-lock.yaml
Update packages to resolve high and moderate security vulnerabilities identified with `pnpm audit` or create tickets to track where update is not possible.
[SMR-469](https://sagebionetworks.jira.com/browse/SMR-469)
- Update packages to resolve high and moderate vulnerabilities identified with `pnpm audit`
- Open tickets for vulnerabilities that cannot be resolved by updating packages
- `d3-color` high vulnerability: [SMR-506](https://sagebionetworks.jira.com/browse/SMR-506)
- `request` and `tough-cookie` moderate vulnerabilities: [SMR-505](https://sagebionetworks.jira.com/browse/SMR-505)
Run `pnpm audit` then use `pnpm why` to identify if and how we can resolve each security vulnerability. 
```bash
$ pnpm audit
┌─────────────────────┬──────────────────────────────────────────────────────── …
```
> chore(deps): update dependencies with security vulnerabilities (SMR-469)

- libs/agora/gene-comparison-tool/jest.config.ts
- libs/agora/genes/jest.config.ts
- libs/agora/home/jest.config.ts
- libs/agora/nominated-targets/jest.config.ts
- libs/agora/ui/jest.config.ts
- libs/explorers/comparison-tools/jest.config.ts
- libs/explorers/services/src/lib/github.service.spec.ts
- libs/explorers/services/src/lib/github.service.ts
- libs/explorers/services/src/lib/version.service.spec.ts
- libs/explorers/services/src/lib/version.service.ts
- libs/explorers/shared/jest.config.ts
- libs/explorers/ui/jest.config.ts
- libs/explorers/util/jest.config.ts
- libs/model-ad/disease-correlation-comparison-tool/jest.config.ts
- libs/model-ad/gene-expression-comparison-tool/jest.config.ts
- libs/model-ad/home/jest.config.ts
- libs/model-ad/model-details/jest.config.ts
- libs/model-ad/model-overview-comparison-tool/jest.config.ts
- libs/model-ad/ui/jest.config.ts
The [explorers github tags service](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/libs/explorers/services/src/lib/github.service.ts) currently returns the first page of tags. However, the tag of interest may not be on the first page. We should iterate through each page until the tag of interest is found or the last page is reached.
[MG-418](https://sagebionetworks.jira.com/browse/MG-418)
- Handles paginated response from GitHub tags service
Set `APP_VERSION="4.1.0-rc2"` and `TAG_NAME="agora/v4.1.0-rc2"` in `apps/agora/app/.env`
Build and run the app: `agora-build-images && agora-docker-start`
current (prod) | updated (this PR) 
:---: | :---: 
[MG-418]: https://sagebionetworks.jira.com/browse/MG-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> fix(explorers): handle paginated response from GitHub tags service (MG-418)

- .github/workflows/update-synapse-api.yml
This PR fix the broken workflow that updates the Synapse API description and its generated artifacts.
As part of the solution, this PR explored another way to run tasks and GitHub Actions inside the dev container provided by the monorepo.
The benefit of this approach is it's "simplicity", compared to when using the dev container CLI, its faster dev container setup runtime, and the ability to using GitHub actions that depends on tools installed inside the dev container (here `peter-evans/create-pull-request@v7` that creates commits and push to a remote, triggering git hooks that executes tools provided by the dev container).
- [SMR-435](https://sagebionetworks.jira.com/browse/SMR-435)
The new approach takes about 3 minutes to setup the dev container and run `workspace-install`.
This is …
> fix(synapse): use alternative method to run the dev container to update Synapse API (SMR-435)

- apps/bixarena/app/project.json
Updates BixArena app configuration to support different serving modes:
- `nx serve bixarena-app` task: serve the demo app (original `serve-demo`)
- `nx run bixarena-app:serve-legacy` task: serve the original FastChat app based on `gradio_web_server_multi` module
- switch `bixarena-app` task names to serve different versions
> chore(bixarena): switch bixarena-app task names to serve different versions

- .github/workflows/ci.yml
- .github/workflows/lint-pr.yml
- .github/workflows/update-synapse-api.yml
Update the Synapse API workflow to create PR that triggers downstream workflows.
- [SMR-507](https://sagebionetworks.jira.com/browse/SMR-507)
- Open PRs that update the Synapse API in draft mode.
- Run the main CI/CD workflow triggered by internal and external PRs.
- Trigger the Lint PR workflow by internal PRs.
- Add `concurrency` config to the Lint PR workflow to run only the latest lint task per PR.
[SMR-507]: https://sagebionetworks.jira.com/browse/SMR-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(synapse): update the Synapse API workflow to create PR that triggers downstream workflows (SMR-507)

- .github/workflows/update-synapse-api.yml
Set `COREPACK_ENABLE_DOWNLOAD_PROMPT` in Synapse API workflow to fix a recent issue that stems from having a version of pnpm in `package.json` that is different from the one installed in the Docker image of the dev container.
- [SMR-507](https://sagebionetworks.jira.com/browse/SMR-507)
[SMR-507]: https://sagebionetworks.jira.com/browse/SMR-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(synapse): set `COREPACK_ENABLE_DOWNLOAD_PROMPT` in Synapse API workflow (SMR-507)

- package.json
pnpm is installed at two different places:
- In the Dockerfile of the dev container
- In `package,json` (property `packageManager`)
Until now, updating `packageManager` provided a convenient way to update `pnpm` without waiting for the release of a new dev container. However, a recent issue in the Synapse API workflow occurred when the two versions of pnpm defined above mismatched, hence triggering the installation of the version of pnpm specified in `package.json`. In that case, the issue comes from the fact that the Synapse API workflow is written in a way that disallow the writing of files outside of the repo workspace folder by the non-root user "ubuntu". This could be considered a lack of flexibility of the Synapse API workflow that may be addressed in the future.
More fundamentally, …
> chore(deps): remove `packageManager` from `package.json`

- .github/workflows/update-synapse-api.yml
The motivation is to get rid of a potential cache poisoning issue. However, we have run out of Nx Cloud free credits and remote caching is already supposed to have been disabled. There should also not be any local caching.
- Disable Nx Cloud caching in the Synapse API workflow.
> chore(synapse): disable Nx Cloud in the Synapse API workflow

- apps/bixarena/ai-service/pyproject.toml
- uv.lock
Relax `orjson` version in `bixarena-ai-service` to fix the task `bixarena-app:build-image`. The new version constraint is the same as the one specified by `gradio` in `bixarena-app`.
See the linked Jira ticket for details about the issue and the proposed solution.
- [SMR-522](https://sagebionetworks.jira.com/browse/SMR-522)
Relax `orjson` version in `bixarena-ai-service` to fix the task `bixarena-app:build-image`.
The image of `bixarena-app` can be built successfully again.
```bash
nx build-image bixarena-app --skip-nx-cache
```
> [!NOTE]
> The changes made in this PR do not trigger the task `bixarena-app:build-image` in the CI workflow. Marking all/some Python project as affected when touching the `uv.lock` could be a future improvement.
[SMR-522]: …
> fix(bixarena): relax `orjson` version in `bixarena-ai-service` (SMR-522)

- apps/bixarena/ai-service/Dockerfile
- apps/bixarena/ai-service/bixarena_ai_service/__main__.py
- apps/bixarena/ai-service/docker-entrypoint.sh
- apps/bixarena/ai-service/project.json
- apps/bixarena/ai-service/pyproject.toml
- docker/bixarena/serve-detach.sh
- docker/bixarena/services/ai-service.yml
- docker/bixarena/services/api-gateway.yml
- [SMR-519](https://sagebionetworks.jira.com/browse/SMR-519)
- Depends on #3553
- Define a console script in `pyproject.toml` to start the app with `uv run bixarena-ai-service ...`.
- Add `Dockerfile` and entry point file to enable the `build-image` task.
```bash
nx build-image bixarena-ai-service
```
Notes that `usjon` requires `g++`, which would make the Docker image 1.32 GB. By separating the build and runtime stage in the Dockerfile, the resulting image is only 256 GB.
Includes the image of the AI service:
```bash
bixarena-build-images
```
Output:
```console
NX   Running target build-image for 6 projects and 9 tasks they depend on
→  Executing 3/13 remaining tasks in parallel...
✔  nx run bixarena-api-description:build (3s)
✔  nx run bixarena-app:build (2s)
✔  nx run …
```
> feat(bixarena): containerize the AI service (SMR-519)

- apps/bixarena/app/pyproject.toml
- uv.lock
Clean up unused dependencies and reduce the Docker image building time for BixArena App
[SMR-512](https://sagebionetworks.jira.com/browse/SMR-512)
- Remove unused dependencies for BixArena App
```
nx build-image bixarena-app --skip-nx-cache
```
Before
```console
...
#12 [stage-1 6/8] RUN uv pip install /tmp/*.tar.gz --system
#12 0.430 Using Python 3.13.3 environment at: /usr/local
#12 1.218 Resolved 109 packages in 786ms
#12 39.22 Prepared 109 packages in 37.99s
#12 40.01 Installed 109 packages in 794ms
#12 40.01  + accelerate==1.10.1
#12 40.01  + aiofiles==23.1.0
#12 40.01  + aiohappyeyeballs==2.6.1
#12 40.01  + aiohttp==3.13.0
#12 40.01  + aiosignal==1.4.0
#12 40.01  + annotated-types==0.7.0
#12 40.02  + anyio==4.11.0
#12 40.02  + attrs==25.4.0
#12 40.02  + audioop-lts==0.2.2
#12 40.02 …
```
> refactor(bixarena): remove unused dependencies for BixArena App (SMR-512)
